-- =============================================================================
-- JustFit — Cycling Workouts Seed (Executable Snapshot)
-- File: migrations/baseline/1030_seed_cycling.sql
-- Generated: 2026-05-03T12:48:51.853Z
--
-- Bootstrap order: run AFTER 1010_schema_training.sql
--
-- Canonical current state of:
--   cycling_workouts : 29 rows
--   (migrations 0035 initial 23 workouts + 0037 Phase 3a 6 new + 3 updated)
--
-- Uses INSERT OR IGNORE — idempotent on a fresh or existing DB.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- cycling_workouts (29 rows)
-- ---------------------------------------------------------------------------

INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw01', 'cw-z2-45', 'Zone 2 · 45 min', 'build_fitness', 'endurance', 32, 45, '[{"label":"Zone 2","duration_sec":2700,"power_pct_low":55,"power_pct_high":75,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw02', 'cw-ss-2x12', 'Sweet Spot · 2×12 min', 'build_fitness', 'sweet_spot', 45, 47, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":50,"power_pct_high":65,"sets":1},{"label":"Sweet spot","duration_sec":720,"power_pct_low":88,"power_pct_high":93,"sets":2},{"label":"Recovery","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":2},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw03', 'cw-tempo-30', 'Tempo · 30 min', 'build_fitness', 'threshold', 42, 45, '[{"label":"Warm-up","duration_sec":480,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Tempo","duration_sec":1800,"power_pct_low":76,"power_pct_high":90,"sets":1},{"label":"Cool-down","duration_sec":420,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw04', 'cw-cadence-pyramid', 'Cadence Pyramid · 35 min', 'build_fitness', 'endurance', 25, 35, '[{"label":"Warm-up","duration_sec":300,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Cadence block","duration_sec":300,"power_pct_low":60,"power_pct_high":75,"sets":5},{"label":"Recovery","duration_sec":120,"power_pct_low":50,"power_pct_high":60,"sets":5},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw05', 'cw-threshold-2x10', 'Threshold · 2×10 min', 'climbing', 'threshold', 47, 50, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Threshold","duration_sec":600,"power_pct_low":95,"power_pct_high":100,"sets":2},{"label":"Recovery","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":2},{"label":"Cool-down","duration_sec":600,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw06', 'cw-vo2max-4x4', 'VO2max · 4×4 min', 'climbing', 'vo2max', 50, 52, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"VO2max","duration_sec":240,"power_pct_low":106,"power_pct_high":120,"sets":4,"min_sets":2,"max_sets":6},{"label":"Recovery","duration_sec":240,"power_pct_low":45,"power_pct_high":55,"sets":4,"min_sets":2,"max_sets":6},{"label":"Cool-down","duration_sec":480,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw07', 'cw-over-unders-3x9', 'Over-Unders · 3×9 min', 'climbing', 'threshold', 60, 55, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Over-under set","duration_sec":540,"power_pct_low":88,"power_pct_high":108,"sets":3},{"label":"Recovery","duration_sec":360,"power_pct_low":45,"power_pct_high":55,"sets":3},{"label":"Cool-down","duration_sec":420,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw08', 'cw-threshold-30', 'Long Threshold · 30 min', 'climbing', 'threshold', 58, 50, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Threshold","duration_sec":1800,"power_pct_low":95,"power_pct_high":100,"sets":1},{"label":"Cool-down","duration_sec":600,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw09', 'cw-sprint-vo2-sprint', 'Sprint–VO2–Sprint · 3 rounds', 'sprint', 'anaerobic', 42, 40, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Sprint","duration_sec":30,"power_pct_low":150,"power_pct_high":200,"sets":3},{"label":"VO2 effort","duration_sec":180,"power_pct_low":108,"power_pct_high":120,"sets":3},{"label":"Recovery","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":3},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw10', 'cw-anaerobic-6x30s', 'Anaerobic · 6×30 s', 'sprint', 'anaerobic', 29, 35, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Anaerobic","duration_sec":30,"power_pct_low":130,"power_pct_high":160,"sets":6,"min_sets":3,"max_sets":8},{"label":"Recovery","duration_sec":240,"power_pct_low":45,"power_pct_high":55,"sets":6,"min_sets":3,"max_sets":8},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw11', 'cw-cadence-builds', 'Cadence Builds · 5×4 min', 'sprint', 'endurance', 25, 35, '[{"label":"Warm-up","duration_sec":300,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Cadence build","duration_sec":240,"power_pct_low":60,"power_pct_high":75,"sets":5},{"label":"Recovery","duration_sec":120,"power_pct_low":45,"power_pct_high":55,"sets":5},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw12', 'cw-neuromuscular-10x10s', 'Neuromuscular · 10×10 s', 'sprint', 'anaerobic', 25, 30, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Sprint","duration_sec":10,"power_pct_low":150,"power_pct_high":200,"sets":10},{"label":"Recovery","duration_sec":120,"power_pct_low":45,"power_pct_high":55,"sets":10},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw13', 'cw-z2-45-base', 'Zone 2 · 45 min', 'aerobic_base', 'endurance', 32, 45, '[{"label":"Zone 2","duration_sec":2700,"power_pct_low":55,"power_pct_high":75,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw14', 'cw-z2-60', 'Zone 2 · 60 min', 'aerobic_base', 'endurance', 42, 60, '[{"label":"Zone 2","duration_sec":3600,"power_pct_low":55,"power_pct_high":75,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw15', 'cw-z2-90', 'Zone 2 · 90 min', 'aerobic_base', 'endurance', 63, 90, '[{"label":"Zone 2","duration_sec":5400,"power_pct_low":55,"power_pct_high":75,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw16', 'cw-recovery-spin', 'Recovery Spin · 30 min', 'aerobic_base', 'endurance', 15, 30, '[{"label":"Recovery","duration_sec":1800,"power_pct_low":45,"power_pct_high":60,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw17', 'cw-z2-60-race', 'Zone 2 · 60 min', 'race_fitness', 'endurance', 42, 60, '[{"label":"Zone 2","duration_sec":3600,"power_pct_low":55,"power_pct_high":75,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw18', 'cw-vo2max-5x5', 'VO2max · 5×5 min', 'race_fitness', 'vo2max', 74, 65, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"VO2max","duration_sec":300,"power_pct_low":106,"power_pct_high":120,"sets":5,"min_sets":3,"max_sets":7},{"label":"Recovery","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":5,"min_sets":3,"max_sets":7},{"label":"Cool-down","duration_sec":600,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw19', 'cw-z2-sprints', 'Zone 2 + Sprints · 60 min', 'race_fitness', 'endurance', 46, 62, '[{"label":"Zone 2","duration_sec":3240,"power_pct_low":55,"power_pct_high":75,"sets":1},{"label":"Sprint","duration_sec":10,"power_pct_low":130,"power_pct_high":160,"sets":6},{"label":"Recovery","duration_sec":60,"power_pct_low":50,"power_pct_high":60,"sets":6}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw20', 'cw-race-sim', 'Race Simulation · 60 min', 'race_fitness', 'threshold', 62, 60, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Race effort","duration_sec":2700,"power_pct_low":80,"power_pct_high":90,"sets":1},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw21', 'cw-test-ramp', 'Ramp Test', 'any', 'test', 45, 25, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":50,"power_pct_high":65,"sets":1},{"label":"Ramp step","duration_sec":60,"power_pct_low":50,"power_pct_high":130,"sets":16},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw22', 'cw-test-12min', '12-min FTP Test', 'any', 'test', 38, 32, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":70,"sets":1},{"label":"Pacing effort","duration_sec":300,"power_pct_low":100,"power_pct_high":110,"sets":1},{"label":"12-min all-out","duration_sec":720,"power_pct_low":95,"power_pct_high":110,"sets":1},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw23', 'cw-test-20min', '20-min FTP Test', 'any', 'test', 52, 40, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":70,"sets":1},{"label":"Pacing effort","duration_sec":300,"power_pct_low":100,"power_pct_high":110,"sets":1},{"label":"20-min all-out","duration_sec":1200,"power_pct_low":95,"power_pct_high":105,"sets":1},{"label":"Cool-down","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw24', 'cw-vo2max-pyramid', 'VO2max Pyramid · 30 min', 'climbing', 'vo2max', 26, 30, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":75,"sets":1},{"label":"Zone 3 ramp","duration_sec":120,"power_pct_low":83,"power_pct_high":89,"sets":1},{"label":"Zone 4 ramp","duration_sec":120,"power_pct_low":93,"power_pct_high":99,"sets":1},{"label":"VO2max peak","duration_sec":120,"power_pct_low":103,"power_pct_high":109,"sets":1},{"label":"Zone 4 descent","duration_sec":120,"power_pct_low":93,"power_pct_high":99,"sets":1},{"label":"Zone 3 descent","duration_sec":120,"power_pct_low":83,"power_pct_high":89,"sets":1},{"label":"Cool-down","duration_sec":600,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw25', 'cw-sprint-vo2-sprint-30', 'Sprint–VO2–Sprint · 30 min', 'sprint', 'anaerobic', 26, 30, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Sprint","duration_sec":10,"power_pct_low":160,"power_pct_high":200,"sets":4},{"label":"VO2 bridge","duration_sec":100,"power_pct_low":120,"power_pct_high":140,"sets":2},{"label":"Block recovery","duration_sec":360,"power_pct_low":45,"power_pct_high":55,"sets":1},{"label":"Cool-down","duration_sec":600,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw26', 'cw-sprint-pyramid', 'Sprint Pyramid · 46 min', 'sprint', 'anaerobic', 31, 46, '[{"label":"Warm-up","duration_sec":900,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Sprint","duration_sec":11,"power_pct_low":160,"power_pct_high":200,"sets":10},{"label":"Sprint recovery","duration_sec":55,"power_pct_low":45,"power_pct_high":55,"sets":10},{"label":"Pyramid recovery","duration_sec":300,"power_pct_low":45,"power_pct_high":55,"sets":1},{"label":"Cool-down","duration_sec":900,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw27', 'cw-40-20-climbing', '40-20 s VO2max · 30 min base', 'climbing', 'vo2max', 29, 30, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"VO2max interval","duration_sec":40,"power_pct_low":120,"power_pct_high":130,"sets":10,"min_sets":5,"max_sets":15},{"label":"Recovery","duration_sec":20,"power_pct_low":45,"power_pct_high":55,"sets":10,"min_sets":5,"max_sets":15},{"label":"Cool-down","duration_sec":600,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw28', 'cw-40-20-race', '40-20 s VO2max · 30 min base', 'race_fitness', 'vo2max', 29, 30, '[{"label":"Warm-up","duration_sec":600,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"VO2max interval","duration_sec":40,"power_pct_low":120,"power_pct_high":130,"sets":10,"min_sets":5,"max_sets":15},{"label":"Recovery","duration_sec":20,"power_pct_low":45,"power_pct_high":55,"sets":10,"min_sets":5,"max_sets":15},{"label":"Cool-down","duration_sec":600,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);
INSERT OR IGNORE INTO cycling_workouts (id, slug, name, sub_goal, workout_type, tss_estimate, duration_min, intervals_json, is_active) VALUES
  ('cw29', 'cw-flamme-rouge', 'Flamme Rouge · 46 min base', 'race_fitness', 'vo2max', 40, 46, '[{"label":"Warm-up","duration_sec":900,"power_pct_low":55,"power_pct_high":65,"sets":1},{"label":"Threshold","duration_sec":30,"power_pct_low":90,"power_pct_high":100,"sets":12,"min_sets":6,"max_sets":18},{"label":"VO2max surge","duration_sec":20,"power_pct_low":103,"power_pct_high":109,"sets":12,"min_sets":6,"max_sets":18},{"label":"Sprint","duration_sec":10,"power_pct_low":130,"power_pct_high":150,"sets":12,"min_sets":6,"max_sets":18},{"label":"Recovery","duration_sec":20,"power_pct_low":45,"power_pct_high":55,"sets":12,"min_sets":6,"max_sets":18},{"label":"Cool-down","duration_sec":900,"power_pct_low":45,"power_pct_high":55,"sets":1}]', 1);

