-- 35 new exercises (brings total to ~50)
-- Tags used by planner: low_impact, no_floor, no_sweat, floor, high_impact, bodyweight, dumbbell, quiet
-- equipment_required_json: ["none"] | ["dumbbell"] | ["chair"]

INSERT INTO exercises (id, slug, name, category, primary_muscles_json, tags_json, equipment_required_json, instructions_json, metrics_json, is_active, created_at_ms, updated_at_ms) VALUES

-- ── STRENGTH · BODYWEIGHT ──────────────────────────────────────────────────

('ex_wall_pushup','wall-push-up','Wall Push-up','strength',
 '["chest","triceps","shoulders"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Stand arm-length from wall","Place palms flat, shoulder-width","Lower chest to wall, elbows at 45°","Push back to start"],"cues":["Keep body straight","Breathe out on push"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_diamond_pushup','diamond-push-up','Diamond Push-up','strength',
 '["triceps","chest","shoulders"]',
 '["bodyweight","floor","high_impact"]',
 '["none"]',
 '{"steps":["Hands together under chest in diamond shape","Lower chest to hands","Push back up"],"cues":["Keep elbows close","Squeeze triceps at top"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_tricep_dip','tricep-chair-dip','Tricep Chair Dip','strength',
 '["triceps","shoulders"]',
 '["bodyweight","no_floor","low_impact"]',
 '["chair"]',
 '{"steps":["Sit on edge of chair, hands gripping edge","Slide off, arms straight","Bend elbows to 90°","Push back up"],"cues":["Keep back close to chair","Don''t shrug shoulders"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_calf_raise','calf-raise','Calf Raise','strength',
 '["calves"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Stand with feet hip-width","Rise onto toes","Hold 1 second","Lower slowly"],"cues":["Hold wall for balance if needed","Slow descent for more effect"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_wall_sit','wall-sit','Wall Sit','strength',
 '["quadriceps","glutes"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Back flat against wall","Slide down until thighs parallel","Hold position"],"cues":["Knees at 90°","Keep weight in heels"]}',
 '{"supports":["time","sets"]}',
 1,1767830400000,1767830400000),

('ex_superman','superman-hold','Superman Hold','strength',
 '["lower_back","glutes","hamstrings"]',
 '["bodyweight","floor","low_impact"]',
 '["none"]',
 '{"steps":["Lie face down, arms extended overhead","Lift arms, chest, and legs off floor simultaneously","Hold 2 seconds","Lower slowly"],"cues":["Keep neck neutral","Squeeze glutes at top"]}',
 '{"supports":["reps","sets","time"]}',
 1,1767830400000,1767830400000),

('ex_bird_dog','bird-dog','Bird Dog','strength',
 '["core","lower_back","glutes"]',
 '["bodyweight","floor","low_impact","quiet"]',
 '["none"]',
 '{"steps":["On all fours, wrists under shoulders","Extend right arm and left leg simultaneously","Hold 2 seconds","Switch sides"],"cues":["Keep hips square","Move slowly and deliberately"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_dead_bug','dead-bug','Dead Bug','strength',
 '["core","transverse_abdominis"]',
 '["bodyweight","floor","low_impact","quiet"]',
 '["none"]',
 '{"steps":["Lie on back, arms up, knees at 90°","Lower right arm and left leg towards floor","Return to start","Switch sides"],"cues":["Keep lower back pressed to floor","Move slowly"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_reverse_lunge','reverse-lunge','Reverse Lunge','strength',
 '["quadriceps","glutes","hamstrings"]',
 '["bodyweight","no_floor","low_impact"]',
 '["none"]',
 '{"steps":["Stand tall, feet hip-width","Step back with right foot","Lower back knee toward floor","Push through front heel to return"],"cues":["Keep front knee over ankle","Stay upright"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_incline_pushup','incline-push-up','Incline Push-up','strength',
 '["chest","triceps","shoulders"]',
 '["bodyweight","no_floor","low_impact"]',
 '["chair"]',
 '{"steps":["Hands on edge of chair or bench","Body straight from head to heels","Lower chest to surface","Push back up"],"cues":["Easier than floor push-up","Great for beginners"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

-- ── STRENGTH · DUMBBELL ───────────────────────────────────────────────────

('ex_db_curl','dumbbell-bicep-curl','Dumbbell Bicep Curl','strength',
 '["biceps","forearms"]',
 '["dumbbell","no_floor","low_impact","no_sweat","quiet"]',
 '["dumbbell"]',
 '{"steps":["Stand or sit, dumbbells at sides, palms forward","Curl weights to shoulders","Squeeze at top","Lower slowly"],"cues":["Keep elbows fixed at sides","Full range of motion"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_db_shoulder_press','dumbbell-shoulder-press','Dumbbell Shoulder Press','strength',
 '["shoulders","triceps"]',
 '["dumbbell","no_floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Sit or stand, dumbbells at shoulder height, palms forward","Press overhead until arms nearly straight","Lower to start"],"cues":["Don''t lock elbows","Brace core throughout"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_db_lateral_raise','dumbbell-lateral-raise','Dumbbell Lateral Raise','strength',
 '["shoulders","traps"]',
 '["dumbbell","no_floor","low_impact","no_sweat","quiet"]',
 '["dumbbell"]',
 '{"steps":["Stand, dumbbells at sides","Raise arms to shoulder height with slight elbow bend","Lower slowly"],"cues":["Lead with elbows","Stop at shoulder height"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_db_deadlift','dumbbell-deadlift','Dumbbell Deadlift','strength',
 '["hamstrings","glutes","lower_back"]',
 '["dumbbell","no_floor"]',
 '["dumbbell"]',
 '{"steps":["Stand, dumbbells in front of thighs","Hinge at hips, sending them back","Lower weights along legs to mid-shin","Drive hips forward to return"],"cues":["Flat back throughout","Squeeze glutes at top"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

('ex_db_tricep_kickback','dumbbell-tricep-kickback','Dumbbell Tricep Kickback','strength',
 '["triceps"]',
 '["dumbbell","no_floor","low_impact","no_sweat","quiet"]',
 '["dumbbell"]',
 '{"steps":["Hinge forward 45°, upper arm parallel to floor","Extend forearm back until arm is straight","Squeeze tricep","Return slowly"],"cues":["Keep upper arm still","Full extension"]}',
 '{"supports":["reps","sets"]}',
 1,1767830400000,1767830400000),

-- ── CARDIO ────────────────────────────────────────────────────────────────

('ex_march_in_place','march-in-place','March in Place','cardio',
 '["legs","core"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Stand tall","Alternate lifting knees to hip height","Swing opposite arm","Keep steady rhythm"],"cues":["Great warm-up or low-impact cardio","No jumping required"]}',
 '{"supports":["time","reps"]}',
 1,1767830400000,1767830400000),

('ex_step_touch','step-touch','Step Touch','cardio',
 '["legs","glutes"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Step right foot to the right","Bring left foot to meet it","Step left, bring right to meet","Add arm swing for intensity"],"cues":["Silent — great for no_clothing days","Comfortable pace"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_skater_hop','skater-hop','Skater Hop','cardio',
 '["glutes","quadriceps","calves"]',
 '["bodyweight","no_floor","high_impact"]',
 '["none"]',
 '{"steps":["Jump laterally to the right, landing on right foot","Swing left leg behind","Jump left, landing on left foot","Repeat with rhythm"],"cues":["Keep chest up","Land softly"]}',
 '{"supports":["reps","time"]}',
 1,1767830400000,1767830400000),

('ex_box_step','box-step-up','Step Up','cardio',
 '["quadriceps","glutes","calves"]',
 '["bodyweight","no_floor","low_impact"]',
 '["chair"]',
 '{"steps":["Step right foot onto chair/step","Bring left foot up","Step right foot down","Bring left foot down","Alternate lead foot"],"cues":["Control the descent","Use sturdy surface only"]}',
 '{"supports":["reps","time","sets"]}',
 1,1767830400000,1767830400000),

('ex_shadow_boxing','shadow-boxing','Shadow Boxing','cardio',
 '["shoulders","core","arms"]',
 '["bodyweight","no_floor","low_impact","no_sweat"]',
 '["none"]',
 '{"steps":["Stance: feet shoulder-width, slight bend in knees","Throw jab-cross combinations","Add hooks and uppercuts","Move feet between combinations"],"cues":["Stays in one spot","Good stress relief"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

-- ── MOBILITY ──────────────────────────────────────────────────────────────

('ex_hip_flexor_stretch','hip-flexor-stretch','Hip Flexor Stretch','mobility',
 '["hip_flexors","quadriceps"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Step right foot forward into lunge","Lower left knee toward floor (or keep standing)","Shift weight forward until you feel stretch in left hip","Hold, switch sides"],"cues":["Tall spine","Squeeze back glute for deeper stretch"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_quad_stretch','standing-quad-stretch','Standing Quad Stretch','mobility',
 '["quadriceps","hip_flexors"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Stand on one leg (hold wall for balance)","Bend other knee, bring heel to glute","Hold ankle","Switch sides"],"cues":["Keep knees together","Stand tall"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_shoulder_roll','shoulder-roll-stretch','Shoulder Rolls','mobility',
 '["shoulders","traps","neck"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Roll shoulders forward in large circles x10","Roll backward x10","Then cross one arm across chest, hold 20s each side"],"cues":["Slow and deliberate","Good for desk workers"]}',
 '{"supports":["reps","time"]}',
 1,1767830400000,1767830400000),

('ex_neck_stretch','neck-stretch','Neck Stretch','mobility',
 '["neck","traps"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Sit or stand tall","Tilt right ear to right shoulder, hold 20s","Tilt left ear to left shoulder, hold 20s","Drop chin to chest, hold 20s"],"cues":["No rotation — only lateral tilt","Gentle pressure only"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_forward_fold','standing-forward-fold','Standing Forward Fold','mobility',
 '["hamstrings","lower_back","calves"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Stand, feet hip-width","Hinge forward from hips","Let arms hang or grab elbows","Hold, breathe into the stretch"],"cues":["Bend knees if needed","Relax neck completely"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_pigeon_pose','pigeon-pose','Pigeon Pose','mobility',
 '["hip_flexors","glutes","piriformis"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["From all fours, bring right knee behind right wrist","Extend left leg behind","Sink hips toward floor","Hold, switch sides"],"cues":["Use folded blanket under hip if tight","Breathe deeply"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_seated_twist','seated-spinal-twist','Seated Spinal Twist','mobility',
 '["spine","obliques","hips"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Sit cross-legged or legs extended","Place right hand behind you, left on right knee","Twist right on exhale","Hold, switch sides"],"cues":["Lengthen spine on inhale","Deepen twist on exhale"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_downward_dog','downward-dog','Downward Dog','mobility',
 '["hamstrings","calves","shoulders","spine"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["From all fours, tuck toes, push hips up and back","Form inverted V shape","Press heels toward floor","Alternate bending each knee (pedalling)"],"cues":["Spread fingers wide","Relax head between arms"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_warrior_i','warrior-i-pose','Warrior I','mobility',
 '["quadriceps","hip_flexors","shoulders"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Step right foot forward, left foot back at 45°","Bend front knee to 90°","Raise both arms overhead","Hold, switch sides"],"cues":["Square hips to front","Strong back leg"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_thread_needle','thread-the-needle','Thread the Needle','mobility',
 '["thoracic_spine","shoulders","neck"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["On all fours","Slide right arm under left arm along floor","Rest right shoulder and cheek on floor","Hold, switch sides"],"cues":["Keep hips high","Great for upper back tension"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

-- ── RECOVERY ──────────────────────────────────────────────────────────────

('ex_box_breathing','box-breathing','Box Breathing','recovery',
 '["diaphragm"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Inhale for 4 counts","Hold for 4 counts","Exhale for 4 counts","Hold empty for 4 counts","Repeat 4-6 cycles"],"cues":["Used by elite athletes for stress control","Eyes closed if comfortable"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_pmr','progressive-muscle-relaxation','Progressive Muscle Relaxation','recovery',
 '["full_body"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Tense feet muscles for 5s, release","Move up: calves, thighs, core, hands, arms, shoulders, face","Notice the contrast between tension and release"],"cues":["Seated or lying down","Excellent pre-sleep recovery"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_body_scan','body-scan-meditation','Body Scan','recovery',
 '["full_body"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Lie down comfortably","Close eyes","Slowly bring attention from feet up through body","Notice sensations without judgment"],"cues":["5-10 minutes ideal","Can be done in bed"]}',
 '{"supports":["time"]}',
 1,1767830400000,1767830400000),

('ex_hip_circles','gentle-hip-circles','Gentle Hip Circles','recovery',
 '["hips","lower_back"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Stand feet shoulder-width, hands on hips","Make large circles with hips clockwise x10","Reverse direction x10"],"cues":["Move slowly","Great after sitting long periods"]}',
 '{"supports":["reps","time"]}',
 1,1767830400000,1767830400000),

('ex_wrist_circles','wrist-ankle-circles','Wrist & Ankle Circles','recovery',
 '["wrists","ankles","forearms"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["Extend arms, rotate wrists in circles x10 each direction","Lift one foot, rotate ankle x10 each direction","Switch feet"],"cues":["Good office break movement","Increases joint fluid circulation"]}',
 '{"supports":["reps","time"]}',
 1,1767830400000,1767830400000);
