-- Migration 0010: Complete 150-exercise library
-- Adds equipment_advised_json column
-- Updates existing exercises with pregnancy/postnatal/supine/prone tags
-- Inserts 100 new exercises (total: 150)

ALTER TABLE exercises ADD COLUMN equipment_advised_json TEXT;

-- ── Update existing exercises with new pregnancy/postnatal tags ───────────────

-- Supine (lying on back) — filtered after pregnancy week 16
UPDATE exercises SET tags_json = '["bodyweight","floor","low_impact","quiet","supine"]'
  WHERE slug = 'dead-bug';
UPDATE exercises SET tags_json = '["strength","bodyweight","posterior_chain","floor","quiet","low_impact","supine","postnatal_safe"]'
  WHERE slug = 'glute-bridge';
UPDATE exercises SET tags_json = '["strength","dumbbell","upper_body","push","floor","quiet","low_impact","supine"]'
  WHERE slug = 'dumbbell-floor-press';
UPDATE exercises SET tags_json = '["bodyweight","floor","low_impact","no_sweat","quiet","supine","recovery","pregnancy_safe","postnatal_safe"]'
  WHERE slug = 'body-scan-meditation';

-- Prone (lying face down) — excluded from mid/late pregnancy
UPDATE exercises SET tags_json = '["bodyweight","floor","low_impact","prone"]'
  WHERE slug = 'superman-hold';

-- ── PELVIC FLOOR (new category) ──────────────────────────────────────────────
-- 15 exercises — all pregnancy_safe + postnatal_safe

INSERT INTO exercises (id, slug, name, category, primary_muscles_json, tags_json, equipment_required_json, instructions_json, metrics_json, is_active, created_at_ms, updated_at_ms) VALUES

('ex_kegel_hold','kegel-hold','Kegel Hold','mobility',
 '["pelvic_floor"]',
 '["pelvic_floor","kegel","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit, stand, or lie comfortably","Identify your pelvic floor muscles (the ones you use to stop urination)","Squeeze and lift them upward","Hold for 5–10 seconds","Slowly release and rest for equal time","Repeat 10 times"],"cues":["Don''t hold your breath","Keep buttocks and thighs relaxed","Quality over quantity"]}',
 '{"supports":["reps","sets","time"]}',
 1,1742860800000,1742860800000),

('ex_kegel_pulses','kegel-pulses','Kegel Pulses','mobility',
 '["pelvic_floor"]',
 '["pelvic_floor","kegel","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit or stand comfortably","Quickly contract and release pelvic floor in short pulses","Aim for 1 second on, 1 second off","Do 10–20 pulses","Rest and repeat 3 times"],"cues":["Fast and light contractions","Don''t bear down on release","Breathe normally throughout"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_kegel_elevator','kegel-elevator','Kegel Elevator','mobility',
 '["pelvic_floor"]',
 '["pelvic_floor","kegel","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit comfortably","Imagine your pelvic floor is an elevator","Floor 1: gentle squeeze","Floor 2: a little more","Floor 3: maximum gentle lift","Slowly descend floor by floor","Rest completely before repeating"],"cues":["No rushing — slow and deliberate","Notice each level of engagement","Great for body awareness"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_pelvic_floor_breathing','pelvic-floor-breathing','Pelvic Floor Breathing','mobility',
 '["pelvic_floor","diaphragm"]',
 '["pelvic_floor","breathing","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit tall or lie on your side","Inhale deeply — let belly expand and pelvic floor gently descend","Exhale — gently engage pelvic floor as air leaves","Repeat for 5–10 breaths"],"cues":["Pelvic floor and breath move together","On exhale: lift, not grip","On inhale: release completely"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_360_breathing','360-breathing','360 Breathing','mobility',
 '["diaphragm","pelvic_floor","intercostals"]',
 '["pelvic_floor","breathing","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit with hands on ribcage, thumbs at back","Inhale: feel ribs expand in all directions — front, sides, back","Exhale: ribs draw in, pelvic floor gently lifts","Do 8 slow breaths"],"cues":["Think of breathing into your whole torso","Back ribs expanding is the key sensation","Calming for third trimester breathlessness"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_pelvic_tilt_lying','pelvic-tilt-lying','Pelvic Tilt (Lying)','mobility',
 '["transverse_abdominis","lower_back","pelvic_floor"]',
 '["pelvic_floor","floor","low_impact","no_sweat","quiet","supine","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on your back, knees bent, feet flat","Inhale to prepare","Exhale: gently flatten lower back into floor by tilting pelvis","Hold 3 seconds, release","Repeat 10 times"],"cues":["Small gentle movement only","Don''t squeeze glutes forcefully","Keep breathing throughout"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_heel_slides','heel-slides','Heel Slides','mobility',
 '["transverse_abdominis","hip_flexors","pelvic_floor"]',
 '["pelvic_floor","floor","low_impact","no_sweat","quiet","supine","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on back, knees bent","Exhale and brace core gently","Slowly slide one heel along the floor until leg is nearly straight","Slide back in","Alternate legs — 8 per side"],"cues":["Keep lower back still throughout","Breathe continuously","Great early postnatal core reconnection exercise"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_clamshell','clamshell','Clamshell','mobility',
 '["glutes","hip_abductors","pelvic_floor"]',
 '["pelvic_floor","floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on your side, hips stacked, knees bent to 45°","Keep feet together","Rotate top knee upward like a clamshell opening","Hold 2 seconds at the top","Lower slowly — 12 reps each side"],"cues":["Don''t let hips roll back","Think of leading with your knee","Strengthens hips and pelvic stability"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_side_lying_hip_abduction','side-lying-hip-abduction','Side-Lying Hip Abduction','mobility',
 '["hip_abductors","glutes","pelvic_floor"]',
 '["pelvic_floor","floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on side, body in a straight line","Keep top leg straight, foot flexed","Lift top leg to hip height (about 45°)","Hold 1 second","Lower slowly — 12 reps each side"],"cues":["Lead with the heel","No hip rolling forward","Supports hip stability during pregnancy"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_pelvic_tilt_standing','pelvic-tilt-standing','Standing Pelvic Tilt','mobility',
 '["transverse_abdominis","lower_back","pelvic_floor"]',
 '["pelvic_floor","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand with feet hip-width, knees slightly bent","Place one hand on belly, one on lower back","Exhale: gently draw lower belly in and tilt pelvis slightly under","Hold 3 seconds, release","Repeat 10 times"],"cues":["Tiny movement — not a big tuck","Great against a wall for feedback","Perfect third-trimester posture exercise"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_inner_thigh_squeeze','inner-thigh-squeeze','Inner Thigh Squeeze','mobility',
 '["adductors","pelvic_floor"]',
 '["pelvic_floor","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit on chair with a soft ball, rolled towel, or pillow between knees","Exhale: gently squeeze knees together","Sync the squeeze with a pelvic floor contraction","Hold 5 seconds, release fully","Repeat 10 times"],"cues":["No ball? Just imagine squeezing","Coordinate with pelvic floor lift","Good seated desk-break exercise"]}',
 '{"supports":["reps","sets","time"]}',
 1,1742860800000,1742860800000),

('ex_transverse_activation','deep-core-activation','Deep Core Activation','mobility',
 '["transverse_abdominis","pelvic_floor"]',
 '["pelvic_floor","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit or stand tall","Place fingertips just inside hip bones","Exhale slowly: feel the muscle underneath gently tighten (not suck in, not push out)","Hold gentle engagement for 5 breaths","Release completely and repeat"],"cues":["Imagine zipping up low-rise jeans very gently","Don''t hold breath","Foundation exercise for all postnatal core work"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_supported_glute_bridge','supported-glute-bridge','Supported Glute Bridge','mobility',
 '["glutes","hamstrings","pelvic_floor","transverse_abdominis"]',
 '["pelvic_floor","floor","low_impact","no_sweat","quiet","supine","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on back, knees bent, feet flat, hip-width","Exhale: engage pelvic floor and core","Press through heels to lift hips to a straight line from knees to shoulders","Hold 2 seconds at the top","Lower slowly through your spine"],"cues":["Don''t overextend the back","Squeeze glutes at top","Great postnatal posterior chain activation"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_single_leg_glute_bridge','single-leg-glute-bridge','Single Leg Glute Bridge','mobility',
 '["glutes","hamstrings","core","pelvic_floor"]',
 '["pelvic_floor","floor","low_impact","quiet","supine","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on back, knees bent","Extend one leg straight","Exhale: lift hips off floor using the bent leg","Hold 1 second","Lower and repeat — 8 each side"],"cues":["Keep hips level — don''t let one side drop","Builds single-leg stability","Progress from supported glute bridge"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_exhalation_core','exhalation-core-engagement','Exhalation Core Engagement','mobility',
 '["transverse_abdominis","pelvic_floor","intercostals"]',
 '["pelvic_floor","breathing","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit or stand","Take a natural breath in","As you exhale slowly through pursed lips, feel your lower belly gently drawing inward","Add a light pelvic floor lift on the exhale","Repeat for 8–10 breaths"],"cues":["Exhale should be 4–6 seconds","Don''t force — let exhale do the work","The exhale IS the core exercise"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000);

-- ── STRENGTH — additional bodyweight ─────────────────────────────────────────

INSERT INTO exercises (id, slug, name, category, primary_muscles_json, tags_json, equipment_required_json, instructions_json, metrics_json, is_active, created_at_ms, updated_at_ms) VALUES

('ex_side_plank','side-plank','Side Plank','strength',
 '["obliques","core","hip_abductors"]',
 '["bodyweight","floor","low_impact","quiet"]',
 '["none"]',
 '{"steps":["Lie on your side, forearm on floor under shoulder","Stack feet or stagger them","Lift hips to form a straight line head to feet","Hold position","Repeat other side"],"cues":["Keep hips stacked","Don''t let hips sag or pike","Modify: drop bottom knee to floor"]}',
 '{"supports":["time","sets"]}',
 1,1742860800000,1742860800000),

('ex_pike_push_up','pike-push-up','Pike Push-up','strength',
 '["shoulders","triceps","upper_back"]',
 '["bodyweight","floor","low_impact"]',
 '["none"]',
 '{"steps":["Start in downward dog position","Bend elbows to lower crown of head toward floor","Push back up to start","Keep hips high throughout"],"cues":["Hips stay elevated — this targets shoulders","Wider hands = easier","Builds toward handstand push-up"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_knee_push_up','knee-push-up','Knee Push-up','strength',
 '["chest","triceps","shoulders"]',
 '["bodyweight","floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Kneel on floor, hands shoulder-width, hips forward (not pike)","Lower chest to floor, elbows at 45°","Push back up","Keep body in straight line from knees to head"],"cues":["Great stepping stone to full push-up","Keep core engaged","For pregnancy: excellent alternative in T2-T3"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_sumo_squat','sumo-squat','Sumo Squat','strength',
 '["adductors","glutes","quadriceps"]',
 '["bodyweight","no_floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand with feet wider than shoulder-width, toes turned out 45°","Lower hips straight down, keeping knees tracking toes","Pause at bottom","Drive through heels to stand"],"cues":["Chest stays tall","Great inner thigh target","Very pregnancy-friendly — room for belly"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_lateral_lunge','lateral-lunge','Lateral Lunge','strength',
 '["adductors","glutes","quadriceps"]',
 '["bodyweight","no_floor","low_impact"]',
 '["none"]',
 '{"steps":["Stand with feet together","Step wide to the right, bending right knee and sitting back","Keep left leg straight","Push off right foot to return","Alternate sides"],"cues":["Keep chest tall","Knee tracks over toes","Targets often-neglected lateral strength"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_curtsy_lunge','curtsy-lunge','Curtsy Lunge','strength',
 '["glutes","quadriceps","adductors"]',
 '["bodyweight","no_floor","low_impact"]',
 '["none"]',
 '{"steps":["Stand feet hip-width","Step right foot behind and to the left (cross behind)","Bend both knees to lower into lunge","Return to start","Alternate sides"],"cues":["Keep front knee stable","Great glute med target","Modify by reducing depth"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_standing_hip_abduction','standing-hip-abduction','Standing Hip Abduction','strength',
 '["hip_abductors","glutes"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand on one foot (hold wall for balance)","Slowly raise other leg out to the side to hip height","Hold 1 second","Lower slowly","12 reps each side"],"cues":["Keep pelvis level","Foot stays flexed","Excellent for pelvic stability during pregnancy"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_donkey_kick','donkey-kick','Donkey Kick','strength',
 '["glutes","hamstrings","core"]',
 '["bodyweight","floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["On all fours, wrists under shoulders, knees under hips","Keep right knee bent 90°","Kick right foot toward ceiling, squeezing glute at top","Lower without touching floor","15 reps each side"],"cues":["Hips stay square — don''t twist","Drive heel toward ceiling","All-fours position great for pregnancy belly"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_fire_hydrant','fire-hydrant','Fire Hydrant','strength',
 '["hip_abductors","glutes","core"]',
 '["bodyweight","floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["On all fours, wrists under shoulders","Keeping knee bent, lift right knee out to the side to hip height","Hold 1 second","Lower without touching floor","15 reps each side"],"cues":["Keep core stable","Don''t rotate the spine","Great hip mobility + strength combo"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_good_morning','good-morning-bodyweight','Good Morning','strength',
 '["hamstrings","lower_back","glutes"]',
 '["bodyweight","no_floor","low_impact","quiet","pregnancy_safe"]',
 '["none"]',
 '{"steps":["Stand feet hip-width, hands behind head or crossed on chest","Soft bend in knees","Hinge forward from hips, pushing them back","Lower torso until parallel or hamstrings feel the stretch","Drive hips forward to return"],"cues":["Flat back throughout","Feel the hamstring stretch","Great hip hinge pattern for everyday movement"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_plank_shoulder_tap','plank-shoulder-tap','Plank Shoulder Tap','strength',
 '["core","shoulders","transverse_abdominis"]',
 '["bodyweight","floor","low_impact","quiet"]',
 '["none"]',
 '{"steps":["Start in high plank (push-up position)","Without rotating hips, lift right hand to tap left shoulder","Return, then tap right shoulder with left hand","Alternate — 10 per side"],"cues":["Hips stay square — resist rotation","Feet wider = easier","Core anti-rotation challenge"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_modified_plank','modified-plank','Modified Plank (Knees)','strength',
 '["core","shoulders","transverse_abdominis"]',
 '["bodyweight","floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Kneel on floor, drop to forearms","Body in straight line from knees to head","Hold position, breathe normally"],"cues":["Don''t let hips sag or pike","Brace core gently throughout","Great entry point for postnatal core work"]}',
 '{"supports":["time","sets"]}',
 1,1742860800000,1742860800000),

('ex_single_leg_calf_raise','single-leg-calf-raise','Single Leg Calf Raise','strength',
 '["calves","soleus"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand on one foot (hold wall for balance)","Rise onto the ball of your foot","Hold 1 second at the top","Lower slowly","15 reps each side"],"cues":["Full range of motion","Slow descent for maximum effect","Helps with ankle circulation during pregnancy"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_cobra_press_up','cobra-press-up','Cobra Press-up','strength',
 '["lower_back","glutes","core"]',
 '["bodyweight","floor","low_impact","prone"]',
 '["none"]',
 '{"steps":["Lie face down, hands under shoulders","Press through hands to lift chest off floor","Keep pelvis on floor","Hold 1–2 seconds","Lower slowly"],"cues":["Squeeze glutes at top","Only go as high as comfortable","Strengthens posterior chain"]}',
 '{"supports":["reps","sets","time"]}',
 1,1742860800000,1742860800000),

('ex_sphinx_hold','sphinx-hold','Sphinx Hold','strength',
 '["lower_back","core","shoulders"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet","prone"]',
 '["none"]',
 '{"steps":["Lie face down, prop on forearms, elbows under shoulders","Press forearms into floor and lift chest slightly","Look forward, neck neutral","Hold the position, breathe normally"],"cues":["Gentle backbend — not aggressive","Great for disc health","Avoid if prone position is uncomfortable"]}',
 '{"supports":["time","sets"]}',
 1,1742860800000,1742860800000);

-- ── STRENGTH — dumbbell additional ───────────────────────────────────────────

INSERT INTO exercises (id, slug, name, category, primary_muscles_json, tags_json, equipment_required_json, instructions_json, metrics_json, is_active, created_at_ms, updated_at_ms) VALUES

('ex_db_romanian_dl','dumbbell-romanian-deadlift','Dumbbell Romanian Deadlift','strength',
 '["hamstrings","glutes","lower_back"]',
 '["dumbbell","no_floor","low_impact","pregnancy_safe"]',
 '["dumbbell"]',
 '{"steps":["Stand, dumbbells in front of thighs, palms facing you","Hinge at hips, sending them back, lowering weights along legs","Stop when you feel a hamstring stretch (shin level for most)","Drive hips forward to return, squeeze glutes at top"],"cues":["Keep dumbbells close to legs","Neutral spine throughout","Lighter load appropriate during pregnancy"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_db_hammer_curl','dumbbell-hammer-curl','Dumbbell Hammer Curl','strength',
 '["biceps","brachioradialis","forearms"]',
 '["dumbbell","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["dumbbell"]',
 '{"steps":["Stand or sit, dumbbells at sides, palms facing each other (neutral grip)","Curl weights to shoulders","Squeeze at top","Lower slowly"],"cues":["Neutral grip = thumbs up","Targets outer bicep head","Keep elbows fixed at sides"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_db_rear_delt_fly','dumbbell-rear-delt-fly','Dumbbell Rear Delt Fly','strength',
 '["rear_deltoids","rhomboids","traps"]',
 '["dumbbell","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["dumbbell"]',
 '{"steps":["Hinge forward at hips 45° or sit and hinge over thighs","Arms hang down, slight elbow bend","Raise arms out to sides to shoulder height","Squeeze shoulder blades","Lower slowly"],"cues":["Lead with elbows","Light weight — this is harder than it looks","Great for counteracting forward shoulder roll in pregnancy"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_db_overhead_tricep_ext','dumbbell-overhead-tricep-ext','Dumbbell Overhead Tricep Extension','strength',
 '["triceps"]',
 '["dumbbell","no_floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["dumbbell"]',
 '{"steps":["Hold one dumbbell with both hands overhead","Bend elbows to lower dumbbell behind head","Extend arms to return","Keep elbows pointing forward"],"cues":["Elbows stay close to head","Control the descent","Keep core braced"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_db_front_raise','dumbbell-front-raise','Dumbbell Front Raise','strength',
 '["anterior_deltoids","upper_chest"]',
 '["dumbbell","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["dumbbell"]',
 '{"steps":["Stand, dumbbells in front of thighs, palms down","Raise both arms to shoulder height","Hold 1 second","Lower slowly"],"cues":["Keep a slight elbow bend","Don''t swing — control the weight","Alternative: one arm at a time"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_db_sumo_deadlift','dumbbell-sumo-deadlift','Dumbbell Sumo Deadlift','strength',
 '["adductors","glutes","hamstrings","quadriceps"]',
 '["dumbbell","no_floor","low_impact","pregnancy_safe"]',
 '["dumbbell"]',
 '{"steps":["Stand feet wide, toes turned out 45°, hold dumbbell vertically between legs","Hinge hips and bend knees to lower weight toward floor","Drive through heels and hips to stand","Squeeze glutes at top"],"cues":["Keeps weight between legs — great for pregnancy","Chest stays tall","Sumo stance gives belly room"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_db_farmers_walk','dumbbell-farmers-walk','Dumbbell Farmers Walk','strength',
 '["forearms","traps","core","legs"]',
 '["dumbbell","no_floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Hold heavy dumbbells at sides","Walk steadily for distance or time","Keep chest tall, shoulders back and down","Short, controlled steps"],"cues":["Don''t let weights pull shoulders down","Great grip + full-body challenge","Adapt to walking in place if space is limited"]}',
 '{"supports":["time","reps"]}',
 1,1742860800000,1742860800000),

('ex_db_lunge','dumbbell-lunge','Dumbbell Lunge','strength',
 '["quadriceps","glutes","hamstrings"]',
 '["dumbbell","no_floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Stand holding dumbbells at sides","Step forward with right foot, lower back knee toward floor","Push through front foot to return","Alternate legs"],"cues":["Keep front knee over ankle","Stay upright","Dumbbells add load to bodyweight lunge"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_db_shrug','dumbbell-shrug','Dumbbell Shrug','strength',
 '["traps","neck"]',
 '["dumbbell","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["dumbbell"]',
 '{"steps":["Stand holding dumbbells at sides","Elevate shoulders straight up toward ears","Hold 1 second at top","Lower slowly"],"cues":["Don''t roll shoulders — straight up and down","Squeeze traps at top","Helps with upper back tension from carrying"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_db_wood_chop','dumbbell-wood-chop','Dumbbell Wood Chop','strength',
 '["obliques","core","shoulders"]',
 '["dumbbell","no_floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Stand, hold one dumbbell with both hands at shoulder height on right side","Rotate and pull weight diagonally down to left hip","Return to start","Complete all reps then switch sides"],"cues":["Rotate through torso","Keep hips stable","Avoid after first trimester — rotational load on core"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_db_seated_press','dumbbell-seated-overhead-press','Dumbbell Seated Overhead Press','strength',
 '["shoulders","triceps"]',
 '["dumbbell","no_floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["dumbbell","chair"]',
 '{"steps":["Sit upright on a sturdy chair, dumbbells at shoulder height, palms forward","Press dumbbells overhead until arms nearly straight","Lower with control"],"cues":["Sitting removes lower back strain","Don''t arch back at the top","Safe alternative to standing press during pregnancy"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000);

-- ── CARDIO — additional ───────────────────────────────────────────────────────

INSERT INTO exercises (id, slug, name, category, primary_muscles_json, tags_json, equipment_required_json, instructions_json, metrics_json, is_active, created_at_ms, updated_at_ms) VALUES

('ex_low_impact_jacks','low-impact-jumping-jacks','Low Impact Jumping Jacks','cardio',
 '["legs","glutes","shoulders"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand with feet together, arms at sides","Step right foot out while raising arms overhead","Step right foot back in while lowering arms","Step left foot out, raise arms","Alternate in a steady rhythm"],"cues":["One foot always on the ground","No jumping — same cardio benefit, no impact","Great first-trimester and postnatal cardio"]}',
 '{"supports":["time","reps"]}',
 1,1742860800000,1742860800000),

('ex_heel_dig_march','heel-dig-march','Heel Dig March','cardio',
 '["tibialis_anterior","calves","legs"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand tall, feet hip-width","Alternate tapping your heel forward on the floor","Swing opposite arm forward","Keep a bouncy rhythm — 30–60 seconds"],"cues":["Like marching but heel-first","Good music makes this feel effortless","Gentle enough for any stage"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_grapevine','grapevine-step','Grapevine Step','cardio',
 '["legs","glutes","core"]',
 '["bodyweight","no_floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Step right foot to the right","Cross left foot behind right","Step right foot to the right again","Tap left foot next to right","Reverse direction"],"cues":["Side-to-side stepping pattern","Add arm swings for intensity","Coordination + cardio combined"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_standing_bicycle','standing-bicycle','Standing Bicycle','cardio',
 '["obliques","hip_flexors","core"]',
 '["bodyweight","no_floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand with hands behind head, elbows wide","Raise right knee while rotating left elbow toward it","Alternate sides in slow bicycle rhythm"],"cues":["Rotate from the waist, not just the elbow","Keep core gently braced","Much lower impact than floor crunches"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_modified_burpee','modified-burpee','Modified Burpee (No Jump)','cardio',
 '["full_body","legs","core","shoulders"]',
 '["bodyweight","floor","low_impact"]',
 '["none"]',
 '{"steps":["Stand, then place hands on floor","Walk feet back to plank","Walk feet back to hands","Stand up — no jumping"],"cues":["A full-body movement without the impact","Can also step with one foot at a time","Great stepping stone to full burpees"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_squat_pulse','squat-pulse','Squat Pulse','cardio',
 '["quadriceps","glutes","calves"]',
 '["bodyweight","no_floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lower into a squat position (parallel or above parallel)","Pulse up and down in small movements — about 5cm range","Keep the tension through the thighs","Pulse for 20–30 seconds"],"cues":["Don''t straighten up — stay in the range","Burns quickly!","Excellent for glute and quad endurance"]}',
 '{"supports":["time","reps"]}',
 1,1742860800000,1742860800000),

('ex_shuffle_tap','shuffle-tap','Shuffle Tap','cardio',
 '["legs","glutes","calves"]',
 '["bodyweight","no_floor","low_impact","quiet","pregnancy_safe"]',
 '["none"]',
 '{"steps":["Stand with feet hip-width","Shuffle step right (step-together-step) and tap right foot","Shuffle step left (step-together-step) and tap left foot","Keep a steady rhythm, 30–60 seconds"],"cues":["Light on your feet","Arms swing naturally","Low-impact lateral cardio"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_seated_cardio_punch','seated-cardio-punch','Seated Cardio Punches','cardio',
 '["shoulders","arms","core"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["chair"]',
 '{"steps":["Sit on the edge of a sturdy chair, feet flat","Alternate throwing punches forward — jab, cross, hook","Add speed and rhythm","30–60 seconds of continuous punching"],"cues":["Rotate torso with each punch","Elbows stay in on jab/cross","Great seated cardio option late pregnancy or early postnatal"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_standing_twist_march','standing-twist-march','Standing Twist March','cardio',
 '["obliques","hip_flexors","core"]',
 '["bodyweight","no_floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand with hands behind head","March in place, lifting knees high","As right knee comes up, rotate left shoulder gently toward it","Alternate, keeping rhythm moderate"],"cues":["Don''t crunch — rotate and march","Maintain tall posture","Excellent warm-up movement"]}',
 '{"supports":["time","reps"]}',
 1,1742860800000,1742860800000),

('ex_jump_squat','jump-squat','Jump Squat','cardio',
 '["quadriceps","glutes","calves"]',
 '["bodyweight","no_floor","high_impact","loud"]',
 '["none"]',
 '{"steps":["Lower into squat position","Explosively jump upward, arms swinging overhead","Land softly, absorbing impact through knees and hips","Flow immediately into next rep"],"cues":["Soft landing — knees bent, not locked","Land ball-heel, not heel-first","Avoid during pregnancy"]}',
 '{"supports":["reps","sets","time"]}',
 1,1742860800000,1742860800000),

('ex_tuck_jump','tuck-jump','Tuck Jump','cardio',
 '["quadriceps","calves","core"]',
 '["bodyweight","no_floor","high_impact","loud"]',
 '["none"]',
 '{"steps":["Stand with feet hip-width","Jump and drive both knees toward chest at the peak","Land softly with knees bent","Immediate next rep"],"cues":["Maximum effort jump","Very high impact — not for pregnancy or early postnatal","Great for athletic conditioning"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_jump_rope_sim','jump-rope-simulation','Jump Rope (Simulated)','cardio',
 '["calves","shoulders","calves","core"]',
 '["bodyweight","no_floor","high_impact","loud"]',
 '["none"]',
 '{"steps":["Stand with feet together, arms at sides","Simulate turning a rope with wrists while hopping lightly on balls of feet","Alternate feet or keep together"],"cues":["Great cardio without equipment","High impact — avoid in pregnancy and early postnatal","Low ceilings not an issue — no real rope!"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_lateral_knee_raise','lateral-knee-raise','Lateral Knee Raise','cardio',
 '["hip_abductors","core","legs"]',
 '["bodyweight","no_floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand tall","Shift weight left, lift right knee out to the side (hip height)","Return foot to floor, shift weight right","Lift left knee out to the side","Alternate in steady rhythm"],"cues":["Control the lift — don''t swing","Keep standing leg slightly bent","Hip stability + light cardio"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_wide_step_touch','wide-step-touch','Wide Step Touch','cardio',
 '["legs","glutes","core"]',
 '["bodyweight","no_floor","low_impact","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand tall","Step right foot wide to the right","Bring left foot to meet it, touching down briefly","Step left wide to the left","Bring right foot to meet","Add arm raises for intensity"],"cues":["Wider steps = more glute engagement","Keep chest up","Great continuous warm-up movement"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_sprint_in_place','sprint-in-place','Sprint in Place','cardio',
 '["legs","glutes","core","calves"]',
 '["bodyweight","no_floor","high_impact","loud"]',
 '["none"]',
 '{"steps":["Drive knees up quickly, pumping arms","Lean slightly forward from ankles","Maximum effort for 20–30 seconds","Rest and repeat"],"cues":["Push the pace — this should feel hard","High impact — not for pregnancy","Great HIIT finisher"]}',
 '{"supports":["time","sets"]}',
 1,1742860800000,1742860800000);

-- ── MOBILITY — additional ─────────────────────────────────────────────────────

INSERT INTO exercises (id, slug, name, category, primary_muscles_json, tags_json, equipment_required_json, instructions_json, metrics_json, is_active, created_at_ms, updated_at_ms) VALUES

('ex_ankle_mobility','ankle-mobility-circles','Ankle Mobility Circles','mobility',
 '["ankles","calves","tibialis_anterior"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit or stand, lift one foot off the floor","Draw large circles with your foot clockwise 10 times","Reverse 10 times","Switch feet"],"cues":["Point and flex through the full range","Helps with pregnancy swelling and circulation","Also do toe spells (trace letters with toes) for variety"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_thoracic_ext_chair','thoracic-extension-chair','Thoracic Extension on Chair','mobility',
 '["thoracic_spine","chest","shoulders"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["chair"]',
 '{"steps":["Sit upright in a sturdy chair","Clasp hands behind head, elbows wide","Gently arch back over the top edge of the chair back","Hold 3–5 seconds, return upright","Repeat 5–8 times, moving slightly up and down the spine"],"cues":["Supported thoracic extension — very gentle","Great for desk workers and pregnancy posture","Don''t force — just let gravity help"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_chest_opener','chest-opener-arms','Chest Opener','mobility',
 '["chest","anterior_deltoids","biceps"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand tall, feet hip-width","Interlace fingers behind back (or hold a strap or towel)","Gently squeeze shoulder blades together","Lift arms slightly and open chest upward","Hold 20–30 seconds, breathe deeply"],"cues":["Don''t hyperextend neck","Feel the front of chest and shoulders stretch","Perfect for counteracting rounded posture"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_worlds_greatest_stretch','world-greatest-stretch','World''s Greatest Stretch','mobility',
 '["hip_flexors","thoracic_spine","hamstrings","glutes"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet"]',
 '["none"]',
 '{"steps":["From push-up position, step right foot outside right hand","Drop left knee to floor","Rotate right arm toward ceiling, opening chest","Hold 2 seconds, return hand to floor","Repeat on other side — 5 per side"],"cues":["Slow and deliberate","Brilliant full-body mobility sequence","Modify: both knees on floor in lunge position"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_standing_figure_four','standing-figure-four','Standing Figure Four','mobility',
 '["glutes","piriformis","hip_abductors"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand on right foot (hold wall for balance)","Cross left ankle over right knee, forming a 4 shape","Sit back as if sitting in a chair","Feel the stretch in the left glute","Hold 20–30 seconds, switch sides"],"cues":["Stand tall — don''t hunch forward","Great alternative to pigeon pose during pregnancy","Piriformis target — helps sciatic discomfort"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_half_kneeling_hip_opener','half-kneeling-hip-opener','Half Kneeling Hip Opener','mobility',
 '["hip_flexors","adductors","glutes"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet","pregnancy_safe"]',
 '["none"]',
 '{"steps":["Kneel on right knee, left foot forward in a 90° lunge","Keep right knee on floor, left knee over ankle","Shift weight forward gently until you feel the right hip flexor stretch","Add a gentle side reach for extra thoracic opening","Hold 30 seconds each side"],"cues":["Tall spine throughout","Squeeze right glute for deeper hip flexor stretch","Great for hip flexor tightness from sitting"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_shoulder_cross_body','cross-body-shoulder-stretch','Cross-Body Shoulder Stretch','mobility',
 '["rear_deltoids","rotator_cuff"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand tall","Bring right arm straight across your chest","Use left hand or forearm to gently press right arm closer to chest","Hold 20–30 seconds","Switch sides"],"cues":["Keep shoulder down, away from ear","Don''t rotate — stay square","Good for carrying-related shoulder tension"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_side_lying_quad_stretch','side-lying-quad-stretch','Side-Lying Quad Stretch','mobility',
 '["quadriceps","hip_flexors"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on your right side","Bend left knee and hold your left foot with your left hand","Gently draw foot toward your buttock","Keep knees together and hips stacked","Hold 20–30 seconds, switch sides"],"cues":["Great pregnancy alternative to standing quad stretch","Keep core gently engaged","Side-lying is comfortable with a pregnancy pillow"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_seated_butterfly','seated-butterfly','Seated Butterfly Stretch','mobility',
 '["adductors","hip_flexors","groin"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit on floor, soles of feet together","Let knees fall naturally to the sides","Hold feet and sit tall","Gently press knees toward floor with elbows","Hold 30–60 seconds"],"cues":["Don''t force knees down — gravity is enough","Breathe into the hips","Excellent for inner thigh and groin opening — great during pregnancy"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_standing_side_stretch','standing-side-stretch','Standing Side Stretch','mobility',
 '["obliques","lats","intercostals"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand with feet hip-width","Reach right arm overhead and lean gently to the left","Feel the stretch along your right side from hip to fingertips","Hold 20 seconds, switch sides"],"cues":["Don''t rotate — pure side bend","Keep feet grounded","Feels wonderful as pregnancy belly grows"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_overhead_reach_stretch','overhead-reach-stretch','Overhead Reach Stretch','mobility',
 '["lats","shoulders","intercostals","spine"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand or sit tall","Interlace fingers, turn palms to ceiling","Reach arms overhead as high as comfortable","Lengthen the whole spine","Hold 20–30 seconds, breathing deeply"],"cues":["Feel the whole side body lengthen","Good for creating space in the torso during T3","Can also do alternating single-arm reaches"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_wall_chest_stretch','wall-chest-stretch','Wall Chest Stretch','mobility',
 '["chest","anterior_deltoids","biceps"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand sideways to wall","Place right palm flat on wall, arm straight","Gently rotate body left until you feel the chest stretch","Hold 20–30 seconds","Switch sides"],"cues":["Keep arm at shoulder height","Very gentle rotation","Great for breastfeeding posture recovery"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_seated_thoracic_rotation','seated-thoracic-rotation','Seated Thoracic Rotation','mobility',
 '["thoracic_spine","obliques"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["chair"]',
 '{"steps":["Sit sideways on a chair, feet flat on floor","Cross arms over chest or hold back of chair","Gently rotate upper body toward the chair back","Hold 2 seconds, return to centre","8 reps each side"],"cues":["Rotate only as far as comfortable","Keep hips facing forward","Safe spinal rotation — not like a crunch"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_seated_hamstring_stretch','seated-hamstring-stretch','Seated Hamstring Stretch','mobility',
 '["hamstrings","calves","lower_back"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit on floor with both legs extended straight","Sit tall from hips (use folded blanket under sit bones if tight)","Hinge forward from hips — not from the waist","Reach toward feet or shins","Hold 30–60 seconds"],"cues":["Keep back flat — this is a hip hinge, not a back round","Bend knees slightly if very tight","Flex feet for extra calf stretch"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_standing_hamstring_stretch','standing-hamstring-stretch','Standing Hamstring Stretch','mobility',
 '["hamstrings","calves"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand behind a chair for support","Extend one leg forward, heel on floor, foot flexed","Hinge forward gently from the hips with flat back","Feel the stretch behind the thigh","Hold 20–30 seconds, switch legs"],"cues":["Don''t round the back","Keep hips square","Great when bending to floor becomes uncomfortable in pregnancy"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_supported_wall_squat','supported-wall-squat','Supported Wall Squat','mobility',
 '["quadriceps","glutes","hip_flexors","inner_thighs"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand with back against wall, feet hip-width, about 30cm from wall","Slide down the wall into a seated position (thighs parallel or above parallel)","Hold position — breathe naturally","Slide back up"],"cues":["Also called ''wall squat''","Comfortable supported position for third trimester","Add a block under your heels if calves are tight"]}',
 '{"supports":["time","sets"]}',
 1,1742860800000,1742860800000),

('ex_side_lying_stretch','side-lying-full-stretch','Side-Lying Full Body Stretch','mobility',
 '["spine","lats","hips","shoulders"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on your side with hips and knees gently stacked","Reach bottom arm long overhead","Reach top arm overhead to meet it","Feel the full length of your body stretch","Hold 30 seconds each side"],"cues":["Use a pillow between knees for comfort","Perfect with a pregnancy body pillow","Great for sciatic relief"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_forearm_wrist_stretch','forearm-wrist-stretch','Forearm & Wrist Stretch','mobility',
 '["forearms","wrists","biceps"]',
 '["bodyweight","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Extend right arm straight, palm facing up","Use left hand to gently pull fingers down toward floor","Hold 20 seconds (feels the underside of forearm)","Flip palm down, pull fingers up — hold 20 seconds","Switch arms"],"cues":["Gentle pressure only","Helps with wrist swelling in pregnancy (carpal tunnel)","Essential for new parents carrying a baby"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_prone_hip_extension','prone-hip-extension','Prone Hip Extension','mobility',
 '["glutes","hamstrings","lower_back"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet","prone"]',
 '["none"]',
 '{"steps":["Lie face down on the floor, arms extended or under forehead","Keep both hips on the floor","Squeeze right glute and lift right leg a few inches","Hold 2 seconds, lower slowly","12 reps each side"],"cues":["Keep the hip of the working leg on the floor","Small range of motion is fine","Avoid in second/third trimester — use donkey kick instead"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000),

('ex_glute_piriformis_stretch','glute-piriformis-stretch','Glute & Piriformis Stretch','mobility',
 '["glutes","piriformis","hip_external_rotators"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on back, knees bent","Cross right ankle over left knee","Flex right foot","Either stay here or reach through to hold left thigh","Gently draw left leg toward chest","Hold 30–60 seconds, switch sides"],"cues":["Flex the top foot to protect the knee","A figure-four stretch lying down","Excellent for sciatic nerve tension"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000);

-- ── RECOVERY / BREATHING — additional ───────────────────────────────────────

INSERT INTO exercises (id, slug, name, category, primary_muscles_json, tags_json, equipment_required_json, instructions_json, metrics_json, is_active, created_at_ms, updated_at_ms) VALUES

('ex_4_7_8_breathing','4-7-8-breathing','4-7-8 Breathing','recovery',
 '["diaphragm","nervous_system"]',
 '["breathing","recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit comfortably, tip of tongue behind upper front teeth","Exhale completely through the mouth","Close mouth and inhale through nose for 4 counts","Hold breath for 7 counts","Exhale through mouth for 8 counts","This is one cycle — repeat 4 times"],"cues":["Powerful nervous system reset","May feel dizzy at first — reduce hold to 4-4-6","Excellent before sleep"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_alternate_nostril','alternate-nostril-breathing','Alternate Nostril Breathing','recovery',
 '["diaphragm","nervous_system"]',
 '["breathing","recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit comfortably, right hand raised to face","Close right nostril with right thumb, inhale left","Close left nostril with ring finger, release thumb, exhale right","Inhale right","Close right, release left, exhale left","That is one cycle — repeat 5–10 times"],"cues":["Balances left and right brain hemispheres","Good for anxiety and focus","Avoid retention (holding) during pregnancy"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_pursed_lip_breathing','pursed-lip-breathing','Pursed Lip Breathing','recovery',
 '["diaphragm","lungs"]',
 '["breathing","recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit or stand comfortably","Inhale slowly through the nose for 2 counts","Pucker lips as if about to whistle","Exhale slowly through pursed lips for 4 counts","Repeat 5–10 times"],"cues":["Exhale should be twice as long as inhale","Reduces breathlessness — excellent for T3 pregnancy","Used by people with respiratory conditions too"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_humming_breath','humming-bee-breath','Humming Bee Breath','recovery',
 '["diaphragm","vocal_cords","nervous_system"]',
 '["breathing","recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit comfortably, close eyes if you wish","Inhale fully through nose","On the exhale, make a gentle humming sound (like a bee)","Feel the vibration in your lips, nose, and skull","Repeat 6–8 times"],"cues":["The humming triggers the vagus nerve","Deeply calming — great for stress and nausea","Sound can be soft — you don''t need to be loud"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_ocean_breath','ocean-breath','Ocean Breath (Ujjayi)','recovery',
 '["diaphragm","throat","nervous_system"]',
 '["breathing","recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Breathe in through the nose","As you exhale through the nose, slightly constrict the back of the throat","This creates a soft ocean wave or Darth Vader sound","Slow, steady, 4–6 count inhale and exhale","Repeat for 2–5 minutes"],"cues":["The sound means you''re doing it right","Keeps the mind anchored to breath","Popular in yoga and prenatal classes"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_breath_counting','breath-counting','Breath Counting','recovery',
 '["diaphragm","nervous_system"]',
 '["breathing","recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit comfortably, eyes closed","Breathe naturally — don''t control it","Count each exhale from 1 to 10","When you reach 10, start again from 1","If you lose count, simply begin at 1 again"],"cues":["A simple mindfulness anchor","Losing count is normal — just restart without judgment","5 minutes is plenty"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_cooling_breath','cooling-breath','Cooling Breath (Sitali)','recovery',
 '["diaphragm","nervous_system"]',
 '["breathing","recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit comfortably","Roll the tongue into a tube (or if you can''t, teeth slightly apart, tongue behind)","Inhale through the rolled/open tongue — feel the cool air","Close mouth and exhale through the nose","Repeat 6–10 times"],"cues":["Genuinely cooling — good in hot weather or nausea","Works even without tongue rolling","Helps with pregnancy overheating"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_5_senses_grounding','5-senses-grounding','5 Senses Grounding','recovery',
 '["nervous_system"]',
 '["recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Notice 5 things you can see","4 things you can physically feel","3 things you can hear","2 things you can smell","1 thing you can taste","Take one long slow breath"],"cues":["Also called 5-4-3-2-1 grounding","Brings you back to the present moment","Very helpful for anxiety during pregnancy"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_tension_release_viz','tension-release-visualization','Tension Release','recovery',
 '["nervous_system","muscles"]',
 '["recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit or lie comfortably","Take a slow breath in and imagine collecting all your tension","As you exhale slowly, imagine the tension leaving your body as mist","Repeat 5–8 times with intention","Notice your body softening with each exhale"],"cues":["Simple and powerful","Works in any position — great for mid-night wakeups","Combine with progressive muscle relaxation"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_gratitude_reflection','gratitude-reflection','Gratitude Reflection','recovery',
 '["nervous_system"]',
 '["recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit comfortably with eyes closed","Bring to mind 3 specific things you are grateful for today","For each one, sit with the feeling for 10–15 seconds","Notice any physical sensation of warmth or ease","Open eyes slowly"],"cues":["Specificity matters — ''my hot coffee'' not just ''coffee''","Research shows this lowers cortisol","A powerful emotional recovery tool"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_savasana','savasana','Savasana (Corpse Pose)','recovery',
 '["nervous_system","full_body"]',
 '["recovery","floor","low_impact","no_sweat","quiet","supine","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie flat on your back, arms slightly away from body, palms up","Close your eyes","Let feet fall naturally open","Allow the floor to hold all your weight","Remain still for 5–10 minutes"],"cues":["Completely passive — just receive","Best after a workout to let the nervous system integrate","After 16 weeks pregnancy: use left side-lying instead"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_supported_side_rest','supported-side-lying-rest','Supported Side-Lying Rest','recovery',
 '["nervous_system","full_body"]',
 '["recovery","floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on your left side (preferred in pregnancy for circulation)","Place a pillow between your knees","Rest head on a pillow","Allow everything to soften","Stay 5–15 minutes"],"cues":["The pregnancy-safe savasana","Left side improves blood flow to the uterus","Great between contractions in labour too"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_legs_up_wall','legs-up-wall','Legs Up the Wall','recovery',
 '["hamstrings","lower_back","nervous_system"]',
 '["recovery","floor","low_impact","no_sweat","quiet","supine","inversion","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit sideways against a wall","Swing legs up to rest against the wall as you lie back","Arms out to sides, palms up","Stay for 5–15 minutes"],"cues":["Excellent for swollen legs and feet","Mild inversion — avoid in late pregnancy (use supported side-lying instead)","One of the most restorative postures there is"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_neck_shoulder_massage','neck-shoulder-self-massage','Neck & Shoulder Self-Massage','recovery',
 '["traps","neck","shoulders"]',
 '["recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit comfortably","Use right hand to squeeze and release left trapezius muscle (top of shoulder)","Work from the base of skull down toward the shoulder","Switch sides","Use fingertips to gently press base of skull — hold each point 10–20 seconds"],"cues":["Pressure should feel like pleasant relief","Good for feeding-posture tension in postnatal period","Can do with a warm compress first"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_self_massage_feet','self-massage-feet','Self-Massage: Feet','recovery',
 '["feet","plantar_fascia","calves"]',
 '["recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit comfortably and cross one foot over opposite knee","Use thumbs to apply firm pressure to the arch","Work from heel to ball of foot in small circles","Flex and point toes between each pass","Switch feet — 2 minutes each"],"cues":["Feels incredible after a long day or during pregnancy swelling","A tennis ball or small massage ball makes this easier","Don''t apply pressure to the ankle itself during pregnancy"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_labour_breathing','labour-breathing-prep','Labour Breathing Preparation','recovery',
 '["diaphragm","pelvic_floor","nervous_system"]',
 '["breathing","pelvic_floor","recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe"]',
 '["none"]',
 '{"steps":["Sit or kneel comfortably, or find your most comfortable position","Practice slow deep inhale through nose (4–6 counts)","Long, controlled exhale through softly open mouth (6–8 counts)","On exhale, let jaw, face, shoulders, and pelvic floor all release","Repeat for 5–10 minutes"],"cues":["This IS the most useful thing to practice in T3","Exhale is the tool — the release is everything","Practice daily from 36 weeks"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_mindful_body_check','mindful-body-check','Mindful Body Check','recovery',
 '["nervous_system"]',
 '["recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit or lie comfortably","Bring attention to your feet — what do you notice? Temperature, pressure, sensation","Slowly move attention up: ankles, calves, knees, thighs...","Continue through the whole body to the crown of the head","Notice without judgment — there''s no right or wrong to feel"],"cues":["Lighter than a body scan — just noticing","3–5 minutes is plenty","Great postural awareness practice"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_eye_palming','eye-palming','Eye Palming','recovery',
 '["eyes","nervous_system"]',
 '["recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Rub palms together briskly for 10 seconds until warm","Cup warm palms gently over closed eyes — no pressure on eyeballs","Breathe slowly and let eyes completely relax in the darkness","Hold for 60–90 seconds","Repeat 2–3 times"],"cues":["Relieves eye strain and screen fatigue","The warmth and darkness are very soothing","Add a couple drops of lavender to palms for added calm"]}',
 '{"supports":["time"]}',
 1,1742860800000,1742860800000),

('ex_yawn_sigh','yawn-sigh-breath','Yawn & Sigh Breath','recovery',
 '["diaphragm","jaw","nervous_system"]',
 '["breathing","recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Take a big exaggerated yawn — open mouth as wide as possible, inhale fully","At the top, hold for a moment","Release with a long audible sigh — ahhh or haaa","Let the face and shoulders completely drop on the sigh","Repeat 5 times"],"cues":["Yes, fake yawns often trigger real ones","One of the fastest ways to release jaw and neck tension","Excellent for anxiety and labour preparation"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000);

-- ── Additional exercises to reach 100 new total ───────────────────────────────

INSERT INTO exercises (id, slug, name, category, primary_muscles_json, tags_json, equipment_required_json, instructions_json, metrics_json, is_active, created_at_ms, updated_at_ms) VALUES

('ex_cat_cow_pregnancy','cat-cow-pregnancy','Cat-Cow (Pregnancy-Friendly)','mobility',
 '["spine","lower_back","core","pelvic_floor"]',
 '["bodyweight","floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe","pelvic_floor"]',
 '["none"]',
 '{"steps":["On all fours, wrists under shoulders, knees under hips","Inhale: gently let belly drop, lift tailbone and head (Cow)","Exhale: round spine gently toward ceiling, tuck chin and tailbone (Cat)","Move slowly and deliberately, following your breath"],"cues":["Much gentler version — do not overdo the arch","On all fours is comfortable for the belly","Syncing breath with movement calms the nervous system"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_ankle_pumps','ankle-pumps','Ankle Pumps','recovery',
 '["calves","ankles","tibialis_anterior"]',
 '["recovery","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit or lie with legs extended, or elevate feet on a pillow","Flex feet — pull toes toward you","Point feet — push toes away","Alternate in steady rhythm, 20 to 30 pumps","Then do ankle circles in each direction"],"cues":["Stimulates the calf muscle pump","Essential during pregnancy to prevent DVT","Do this every 30 to 60 minutes when sitting for long periods"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_standing_pelvic_rock','standing-pelvic-rock','Standing Pelvic Rock','mobility',
 '["lower_back","pelvic_floor","core"]',
 '["pelvic_floor","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Stand feet hip-width, knees slightly bent, hands on hips","Gently rock pelvis forward (arch lower back slightly)","Then rock pelvis backward (flatten lower back)","Find a slow, rhythmic motion","Repeat for 30 to 60 seconds"],"cues":["Think of a gentle rocking motion","Good for lower back tension in pregnancy","Also used during labour for pain relief"]}',
 '{"supports":["time","reps"]}',
 1,1742860800000,1742860800000),

('ex_seated_pelvic_roll','seated-pelvic-roll','Seated Pelvic Roll','mobility',
 '["lower_back","pelvic_floor","core","hips"]',
 '["pelvic_floor","no_floor","low_impact","no_sweat","quiet","pregnancy_safe","postnatal_safe"]',
 '["chair"]',
 '{"steps":["Sit on the edge of a chair or exercise ball, feet flat","Make large circles with your hips clockwise 10 times","Reverse direction 10 times","Try figure-8 patterns as a variation"],"cues":["Very effective on an exercise ball","Great labour preparation","Loosens hips and lower back naturally"]}',
 '{"supports":["reps","time"]}',
 1,1742860800000,1742860800000),

('ex_dumbbell_chest_press_incline','dumbbell-incline-chest-press','Dumbbell Incline Chest Press','strength',
 '["upper_chest","anterior_deltoids","triceps"]',
 '["dumbbell","floor","low_impact"]',
 '["dumbbell","chair"]',
 '{"steps":["Sit at an incline (on sofa arm, against wall, or on inclined surface)","Hold dumbbells at chest height, palms forward","Press dumbbells up and slightly in until arms nearly straight","Lower slowly to start"],"cues":["Incline targets upper chest","More comfortable than flat press for many people","Avoid flat supine press after 16 weeks pregnancy"]}',
 '{"supports":["reps","sets"]}',
 1,1742860800000,1742860800000);
