-- Migration 0020: Exercise Library v3 — 100 new exercises
-- Organized into 5 sections:
--   A. Strength — Dumbbell (15)
--   B. Strength — Bands / Kettlebell / Pull-up bar / Bodyweight (26)
--   C. Mobility (15)
--   D. Recovery — Foam rolling + breathwork (12)
--   E. Cardio — Non-running (12)
--   F. Equipment-conditional — Running / Cycling / Rowing (20)
-- Total: 100 exercises
--
-- Equipment canonical values used:
--   none, chair, dumbbell, resistance_bands, kettlebell, pull_up_bar,
--   foam_roller, running_shoes, treadmill, exercise_bike, indoor_bike,
--   road_bike, mountain_bike, rowing_machine
--
-- All cycling exercises (F-section) require any of:
--   ["road_bike","mountain_bike","indoor_bike","exercise_bike"]
-- Generic run exercises (F-section) require:
--   ["running_shoes","treadmill"] (planner OR-logic: either satisfies)

INSERT INTO exercises (id, slug, name, category, primary_muscles_json, tags_json, equipment_required_json, instructions_json, metrics_json, alternatives_json, is_active, created_at_ms, updated_at_ms) VALUES

-- ════════════════════════════════════════════════════════════════════════════
-- A. STRENGTH — DUMBBELL (15)
-- ════════════════════════════════════════════════════════════════════════════

('ex20_001','dumbbell-single-arm-row','Dumbbell Single-Arm Row','strength',
 '["lats","rhomboids","rear_deltoid","biceps"]',
 '["strength","dumbbell","pull","no_floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Hinge forward at the hips, place one hand on a bench or thigh for support, let the dumbbell hang straight down.","Pull the dumbbell toward your hip — elbow drives straight back, not flared out.","Lower slowly over 2–3 seconds, feeling the stretch in your lat before the next rep."],"cues":["💡 Keep your back flat — no rounding at the shoulder.","Think ''elbow to hip'' not ''elbow to ceiling''."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-bent-over-row","band-row-seated"]}',
 1,1744700000000,1744700000000),

('ex20_002','dumbbell-bent-over-row','Dumbbell Bent-Over Row','strength',
 '["lats","rhomboids","rear_deltoid","biceps","erector_spinae"]',
 '["strength","dumbbell","pull","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Hold a dumbbell in each hand, hinge forward until your torso is roughly 45°, knees soft.","Row both dumbbells toward your lower ribs simultaneously — elbows stay close to your sides.","Squeeze your shoulder blades together at the top, then lower with control."],"cues":["💡 Lead with the elbows, not the hands.","A flat back is non-negotiable — if it rounds, go lighter."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-single-arm-row","band-row-seated"]}',
 1,1744700000000,1744700000000),

('ex20_003','dumbbell-arnold-press','Dumbbell Arnold Press','strength',
 '["anterior_deltoid","medial_deltoid","triceps","upper_traps"]',
 '["strength","dumbbell","push","no_floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Start with dumbbells at shoulder height, palms facing you (as if at the top of a curl).","As you press overhead, rotate your palms to face forward — ending with straight arms above.","Reverse the rotation as you lower, returning to the starting palm-in position."],"cues":["💡 The rotation recruits all three deltoid heads in one movement.","Keep your core braced — avoid arching your lower back as you press."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-shoulder-press","dumbbell-seated-overhead-press"]}',
 1,1744700000000,1744700000000),

('ex20_004','dumbbell-goblet-squat','Dumbbell Goblet Squat','strength',
 '["quads","glutes","core","adductors"]',
 '["strength","dumbbell","low_impact","full_body","floor"]',
 '["dumbbell"]',
 '{"steps":["Hold one dumbbell vertically at your chest — both hands cupping the top end.","Stand feet shoulder-width, toes angled out 15–30°. Squat down keeping the dumbbell close to your chest.","Drive through your heels to stand, squeezing your glutes at the top."],"cues":["💡 Chest stays tall — the weight counterbalances you into a deep squat.","Knees track over toes throughout — push them out if they cave."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-sumo-deadlift","sumo-squat","kettlebell-goblet-squat"]}',
 1,1744700000000,1744700000000),

('ex20_005','dumbbell-bulgarian-split-squat','Dumbbell Bulgarian Split Squat','strength',
 '["quads","glutes","hamstrings","hip_flexors"]',
 '["strength","dumbbell","low_impact","unilateral","floor"]',
 '["dumbbell"]',
 '{"steps":["Hold a dumbbell in each hand, stand about 60–70 cm in front of a chair or bench.","Place your rear foot on the bench (laces down), front foot flat on the floor.","Lower your rear knee toward the floor, front shin stays near vertical, then drive back up."],"cues":["💡 Front foot far enough forward that your shin stays vertical at the bottom.","This is a unilateral move — expect the quads and glutes to work hard."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-lunge","reverse-lunge","dumbbell-side-lunge"]}',
 1,1744700000000,1744700000000),

('ex20_006','dumbbell-hip-thrust','Dumbbell Hip Thrust','strength',
 '["glutes","hamstrings","core"]',
 '["strength","dumbbell","low_impact","floor","glutes"]',
 '["dumbbell"]',
 '{"steps":["Sit on the floor with your upper back against a bench, dumbbell resting across your hips.","Plant your feet flat, roughly hip-width. Drive your hips up until your body forms a straight line from shoulders to knees.","Squeeze your glutes hard at the top for a full second, then lower under control."],"cues":["💡 Press your chin to your chest slightly to keep your core tight.","The power comes from the glutes — not the lower back."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["supported-glute-bridge","single-leg-glute-bridge"]}',
 1,1744700000000,1744700000000),

('ex20_007','dumbbell-single-leg-rdl','Dumbbell Single-Leg Romanian Deadlift','strength',
 '["hamstrings","glutes","erector_spinae"]',
 '["strength","dumbbell","low_impact","unilateral","posterior_chain"]',
 '["dumbbell"]',
 '{"steps":["Hold a dumbbell in the hand opposite to your standing leg. Shift weight onto one foot, slight knee bend.","Hinge forward at the hip, sending the free leg straight back as a counterweight — back stays flat.","Return to standing by contracting the glute and hamstring of the standing leg."],"cues":["💡 Think ''hip hinge'', not ''bend forward'' — your back stays long and neutral.","Go slow on the descent — 3 seconds down builds more strength."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-romanian-deadlift","kettlebell-single-leg-rdl","good-morning-bodyweight"]}',
 1,1744700000000,1744700000000),

('ex20_008','dumbbell-upright-row','Dumbbell Upright Row','strength',
 '["medial_deltoid","upper_traps","biceps"]',
 '["strength","dumbbell","pull","no_floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Hold dumbbells in front of your thighs, palms facing you, hands close together.","Pull the dumbbells straight up along your body, elbows leading and flaring out to the sides.","Stop when elbows reach shoulder height, then lower slowly."],"cues":["💡 Elbows must stay higher than wrists throughout the movement.","Keep the range of motion comfortable — stop if you feel shoulder impingement."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-lateral-raise","dumbbell-shrug"]}',
 1,1744700000000,1744700000000),

('ex20_009','dumbbell-renegade-row','Dumbbell Renegade Row','strength',
 '["lats","core","triceps","rear_deltoid"]',
 '["strength","dumbbell","pull","core","floor"]',
 '["dumbbell"]',
 '{"steps":["Start in a push-up position, each hand gripping a dumbbell on the floor. Feet wide for stability.","Keeping your hips square to the floor, row one dumbbell to your hip while balancing on the other arm.","Lower it, then repeat on the other side. That is one rep."],"cues":["💡 Wider feet = more stable base. Narrow feet = harder core challenge.","Resist the temptation to rotate your hips — keep them parallel to the floor."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-single-arm-row","plank-shoulder-tap"]}',
 1,1744700000000,1744700000000),

('ex20_010','dumbbell-floor-chest-fly','Dumbbell Floor Chest Fly','strength',
 '["pectorals","anterior_deltoid"]',
 '["strength","dumbbell","push","floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Lie on your back, a dumbbell in each hand, arms extended above your chest, palms facing each other.","Lower the dumbbells out to the sides in a wide arc — elbows stay slightly bent, until your upper arms touch the floor.","Reverse the arc, bringing the dumbbells back together above your chest."],"cues":["💡 Think of hugging a large barrel — the arc shape is everything.","The floor stops you at a safe range — don''t force beyond it."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-incline-chest-press","dumbbell-chest-press-floor"]}',
 1,1744700000000,1744700000000),

('ex20_011','dumbbell-chest-press-floor','Dumbbell Floor Chest Press','strength',
 '["pectorals","triceps","anterior_deltoid"]',
 '["strength","dumbbell","push","floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Lie on your back, knees bent, feet flat. Hold a dumbbell in each hand at chest level, elbows at ~45°.","Press both dumbbells up until your arms are nearly straight above your chest.","Lower slowly until your upper arms rest lightly on the floor, then press again."],"cues":["💡 The floor limits range — this protects the shoulder while still training the chest hard.","Full pause at the bottom to remove stretch reflex and build more strength."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-incline-chest-press","dumbbell-floor-chest-fly"]}',
 1,1744700000000,1744700000000),

('ex20_012','dumbbell-concentration-curl','Dumbbell Concentration Curl','strength',
 '["biceps_brachii"]',
 '["strength","dumbbell","pull","no_floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Sit on a chair, legs apart. Hold one dumbbell in your right hand, brace the back of your right upper arm against your inner right thigh.","Curl the dumbbell toward your shoulder, keeping the upper arm stationary against your thigh.","Lower fully until the arm is straight, then repeat. Switch arms after your set."],"cues":["💡 Bracing against your thigh removes momentum — pure bicep work.","Squeeze at the top and fight the weight down on the way back."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-bicep-curl","dumbbell-hammer-curl","band-bicep-curl"]}',
 1,1744700000000,1744700000000),

('ex20_013','dumbbell-reverse-curl','Dumbbell Reverse Curl','strength',
 '["brachialis","brachioradialis","forearms"]',
 '["strength","dumbbell","pull","no_floor","low_impact"]',
 '["dumbbell"]',
 '{"steps":["Stand holding dumbbells at your sides, palms facing back (overhand grip).","Keeping your elbows tucked, curl the dumbbells upward as if doing a standard curl — the motion is identical, only the grip changes.","Lower slowly, feeling the forearms and brachialis working."],"cues":["💡 Use a lighter weight than your regular curl — the forearms fatigue quickly.","Great for elbow health and grip strength — overlooked but valuable."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-bicep-curl","dumbbell-hammer-curl"]}',
 1,1744700000000,1744700000000),

('ex20_014','dumbbell-side-lunge','Dumbbell Lateral Lunge','strength',
 '["adductors","glutes","quads"]',
 '["strength","dumbbell","low_impact","unilateral","no_floor"]',
 '["dumbbell"]',
 '{"steps":["Hold a dumbbell at your chest or hanging between your legs. Stand with feet together.","Step wide to one side, pushing your hips back as you bend that knee — keep the other leg straight.","Drive through the bent leg''s heel to return to standing. Alternate sides."],"cues":["💡 Your straight leg should feel a stretch on the inner thigh at the bottom.","Keep your chest lifted — don''t let the weight pull you forward."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["lateral-lunge","dumbbell-lunge","curtsy-lunge"]}',
 1,1744700000000,1744700000000),

('ex20_015','dumbbell-suitcase-carry','Dumbbell Suitcase Carry','strength',
 '["obliques","core","hip_flexors","traps","forearms"]',
 '["strength","dumbbell","core","low_impact","no_floor"]',
 '["dumbbell"]',
 '{"steps":["Hold a single dumbbell in one hand at your side — heavier than you think you need.","Walk forward with tall posture, keeping your shoulders level and resisting the side-tilt caused by the weight.","After the prescribed distance or time, switch hands and return."],"cues":["💡 The whole point is to resist leaning — if you lean, go lighter.","This is an anti-lateral-flexion core exercise disguised as a carry."]}'  ,
 '{"supports":["time"],"base_duration_sec":40}',
 '{"substitutions":["dumbbell-farmers-walk","dumbbell-wood-chop"]}',
 1,1744700000000,1744700000000),

-- ════════════════════════════════════════════════════════════════════════════
-- B. STRENGTH — RESISTANCE BANDS (8) + KETTLEBELL (6) + PULL-UP BAR (5) + BODYWEIGHT (7)
-- ════════════════════════════════════════════════════════════════════════════

('ex20_016','band-row-seated','Resistance Band Seated Row','strength',
 '["lats","rhomboids","rear_deltoid","biceps"]',
 '["strength","pull","low_impact","no_floor"]',
 '["resistance_bands"]',
 '{"steps":["Sit on the floor with legs extended. Loop the band around your feet and hold both ends.","Pull the band toward your lower ribs, driving your elbows straight back — squeeze your shoulder blades.","Return slowly, maintaining tension throughout."],"cues":["💡 Sit tall — slouching removes the work from your lats.","The slower the return, the more you''re building."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-single-arm-row","dumbbell-bent-over-row","band-face-pull"]}',
 1,1744700000000,1744700000000),

('ex20_017','band-pull-apart','Resistance Band Pull-Apart','strength',
 '["rear_deltoid","rhomboids","lower_traps"]',
 '["strength","pull","low_impact","no_floor","shoulder_health"]',
 '["resistance_bands"]',
 '{"steps":["Hold the band with both hands shoulder-width apart in front of you at shoulder height, arms straight.","Pull the band apart by moving your arms out to the sides until it touches your chest.","Return slowly — resist the band pulling your hands back together."],"cues":["💡 Ideal as a warm-up or between push sets to balance the shoulder.","Keep the movement controlled — a floppy band means no tension."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["band-face-pull","dumbbell-rear-delt-fly"]}',
 1,1744700000000,1744700000000),

('ex20_018','band-face-pull','Resistance Band Face Pull','strength',
 '["rear_deltoid","rotator_cuff","rhomboids","mid_traps"]',
 '["strength","pull","low_impact","no_floor","shoulder_health"]',
 '["resistance_bands"]',
 '{"steps":["Anchor the band at face height (door frame or post). Hold both ends with an overhand grip, arms extended.","Pull the band toward your face, hands splitting apart — elbows flare out to the sides.","Pause when your hands are beside your ears, then return slowly."],"cues":["💡 Elbows stay at or above shoulder height — this is what makes it a face pull.","One of the best exercises for shoulder health and posture."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["band-pull-apart","dumbbell-rear-delt-fly"]}',
 1,1744700000000,1744700000000),

('ex20_019','band-bicep-curl','Resistance Band Bicep Curl','strength',
 '["biceps_brachii","brachialis"]',
 '["strength","pull","low_impact","no_floor"]',
 '["resistance_bands"]',
 '{"steps":["Stand on the middle of the band, holding one end in each hand, palms facing up.","Curl your hands toward your shoulders, keeping your elbows fixed at your sides.","Lower slowly — resist the band pulling your hands back down."],"cues":["💡 Tension is constant throughout — unlike dumbbells, the band fights you hardest at the top.","Start light — band resistance compounds quickly."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-bicep-curl","dumbbell-concentration-curl","dumbbell-hammer-curl"]}',
 1,1744700000000,1744700000000),

('ex20_020','band-lateral-walk','Resistance Band Lateral Walk','strength',
 '["glute_medius","hip_abductors","quads"]',
 '["strength","low_impact","glutes","no_floor"]',
 '["resistance_bands"]',
 '{"steps":["Place the band just above your knees (or around your ankles for more intensity). Stand with feet hip-width.","Step sideways: lead foot first, then follow with the trail foot — maintain constant band tension.","Complete your reps in one direction, then return. Stay in a quarter-squat throughout."],"cues":["💡 Small steps with tension beat large sloppy steps every time.","If the band sags, you''ve lost the point — keep it taut throughout."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["standing-hip-abduction","side-lying-hip-abduction","band-hip-abduction-standing"]}',
 1,1744700000000,1744700000000),

('ex20_021','band-overhead-press','Resistance Band Overhead Press','strength',
 '["anterior_deltoid","medial_deltoid","triceps","upper_traps"]',
 '["strength","push","low_impact","no_floor"]',
 '["resistance_bands"]',
 '{"steps":["Stand on the band with feet shoulder-width apart, hold the ends at shoulder height, palms forward.","Press both hands straight overhead until your arms are fully extended.","Lower slowly back to shoulder height — resist the band''s pull."],"cues":["💡 Brace your core — pressing overhead with a band challenges stability more than dumbbells.","Keep the wrists stacked over the elbows throughout."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-shoulder-press","dumbbell-seated-overhead-press","dumbbell-arnold-press"]}',
 1,1744700000000,1744700000000),

('ex20_022','band-squat','Resistance Band Squat','strength',
 '["quads","glutes","hamstrings"]',
 '["strength","low_impact","no_floor"]',
 '["resistance_bands"]',
 '{"steps":["Stand on the band with feet shoulder-width apart, hold both ends at shoulder height or crossed over your chest.","Squat down by pushing your hips back and bending your knees — chest stays tall.","Drive through your heels to stand, squeezing your glutes at the top."],"cues":["💡 Resistance increases as you rise — hardest at the top, unlike bodyweight squats.","Good for beginners who need extra feedback on drive mechanics."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["sumo-squat","dumbbell-goblet-squat","wall-sit"]}',
 1,1744700000000,1744700000000),

('ex20_023','band-hip-abduction-standing','Band Standing Hip Abduction','strength',
 '["glute_medius","hip_abductors","tensor_fasciae_latae"]',
 '["strength","low_impact","glutes","no_floor"]',
 '["resistance_bands"]',
 '{"steps":["Anchor the band around one ankle and fix the other end to a low anchor or step on it with the opposite foot.","Stand tall, holding a wall for balance. Lift the banded leg out to the side against resistance.","Lower slowly — don''t let the leg drop."],"cues":["💡 Keep your standing hip level — don''t hitch it up as you lift.","This targets the glute medius — critical for knee stability and hip strength."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["side-lying-hip-abduction","standing-hip-abduction","band-lateral-walk"]}',
 1,1744700000000,1744700000000),

-- KETTLEBELL (6) --

('ex20_024','kettlebell-swing','Kettlebell Swing','strength',
 '["glutes","hamstrings","erector_spinae","core","shoulders"]',
 '["strength","cardio","low_impact","full_body","posterior_chain"]',
 '["kettlebell"]',
 '{"steps":["Stand with feet slightly wider than shoulder-width, kettlebell on the floor between your feet.","Hinge at the hips, grab the bell and hike it back between your legs. Then explosively drive your hips forward to send the bell swinging to shoulder height.","Let the bell fall back, hinging your hips to receive it — don''t squat, hinge."],"cues":["💡 The power is a hip snap, not a shoulder lift — your arms are just the cable.","Squeeze your glutes hard at the top like you''re trying to crack a walnut."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-romanian-deadlift","good-morning-bodyweight","dumbbell-hip-thrust"]}',
 1,1744700000000,1744700000000),

('ex20_025','kettlebell-goblet-squat','Kettlebell Goblet Squat','strength',
 '["quads","glutes","core","adductors"]',
 '["strength","low_impact","full_body"]',
 '["kettlebell"]',
 '{"steps":["Hold the kettlebell by the horns (sides of the handle) at chest height.","Squat deep — elbows can press against the inside of your knees at the bottom to open the hips.","Drive through your heels to stand, keeping the bell close to your chest throughout."],"cues":["💡 The weight in front encourages an upright torso — great for learning squat mechanics.","Drive your knees out at the bottom using your elbows as guides."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-goblet-squat","sumo-squat","band-squat"]}',
 1,1744700000000,1744700000000),

('ex20_026','kettlebell-single-arm-press','Kettlebell Single-Arm Press','strength',
 '["anterior_deltoid","triceps","core"]',
 '["strength","push","low_impact","no_floor","core"]',
 '["kettlebell"]',
 '{"steps":["Clean the kettlebell to the rack position — bell rests on your forearm, elbow tucked at your ribs.","Press the bell straight overhead until your arm is fully locked out, bicep near your ear.","Lower the bell back to the rack position under control."],"cues":["💡 Rack position is key — bell rests on your forearm, not gripped away from your body.","The unilateral press challenges your core more than a bilateral press — brace hard."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-shoulder-press","dumbbell-arnold-press","band-overhead-press"]}',
 1,1744700000000,1744700000000),

('ex20_027','kettlebell-halo','Kettlebell Halo','strength',
 '["anterior_deltoid","medial_deltoid","triceps","rotator_cuff","core"]',
 '["strength","mobility","low_impact","no_floor","shoulder_health"]',
 '["kettlebell"]',
 '{"steps":["Hold the kettlebell by the horns at chest height, elbows slightly bent.","Circle the bell slowly around your head — keeping it close to your skull as you pass it behind.","Complete full circles in one direction, then reverse."],"cues":["💡 Go slow — this is a mobility and control drill, not a speed exercise.","Keep the movement smooth and the bell close. A large arc loses the shoulder work."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-arnold-press","shoulder-circles"]}',
 1,1744700000000,1744700000000),

('ex20_028','kettlebell-single-leg-rdl','Kettlebell Single-Leg RDL','strength',
 '["hamstrings","glutes","erector_spinae"]',
 '["strength","low_impact","unilateral","posterior_chain"]',
 '["kettlebell"]',
 '{"steps":["Hold the kettlebell in the hand opposite your standing leg. Shift weight onto one foot, slight knee bend.","Hinge forward at the hip, letting the bell lower toward the floor as your free leg rises behind you.","Return to standing by contracting the standing leg''s hamstring and glute."],"cues":["💡 The bell should travel in a straight line up and down — no swinging.","Counter-balance with the free leg — the further it extends, the easier to balance."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-single-leg-rdl","dumbbell-romanian-deadlift"]}',
 1,1744700000000,1744700000000),

('ex20_029','kettlebell-deadlift','Kettlebell Deadlift','strength',
 '["hamstrings","glutes","erector_spinae","traps","forearms"]',
 '["strength","low_impact","posterior_chain","full_body"]',
 '["kettlebell"]',
 '{"steps":["Stand over the kettlebell, feet hip-width apart, bell between your feet. Hinge at the hips, grab the handle with both hands.","Keep your chest tall and back flat. Drive through your heels to stand, squeezing glutes at the top.","Hinge back down — hips first, then knees — and place the bell back on the floor before the next rep."],"cues":["💡 The hip hinge, not the knee bend, is what creates posterior chain strength.","Reset your posture between reps — this builds better movement patterns."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-deadlift","dumbbell-romanian-deadlift","kettlebell-swing"]}',
 1,1744700000000,1744700000000),

-- PULL-UP BAR (5) --

('ex20_030','pull-up','Pull-Up','strength',
 '["lats","rhomboids","rear_deltoid","biceps","core"]',
 '["strength","pull","low_impact","no_floor"]',
 '["pull_up_bar"]',
 '{"steps":["Hang from the bar with a pronated grip (palms away) just wider than shoulder-width.","Pull your body up until your chin clears the bar — lead with your chest, not your chin.","Lower slowly over 2–3 seconds until your arms are fully extended."],"cues":["💡 Initiate by depressing your shoulder blades before you bend your elbows.","Full extension at the bottom — no partial reps, every rep from a dead hang."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["chin-up","inverted-row-table","band-row-seated"]}',
 1,1744700000000,1744700000000),

('ex20_031','chin-up','Chin-Up','strength',
 '["biceps_brachii","lats","core"]',
 '["strength","pull","low_impact","no_floor"]',
 '["pull_up_bar"]',
 '{"steps":["Hang from the bar with a supinated grip (palms toward you), hands roughly shoulder-width.","Pull your body up until your chin clears the bar, elbows driving down toward your hips.","Lower with control to a full dead hang."],"cues":["💡 Supinated grip recruits the biceps more — generally easier than pull-ups for beginners.","Same rules as pull-ups: full extension at the bottom, every rep."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["pull-up","inverted-row-table","dumbbell-single-arm-row"]}',
 1,1744700000000,1744700000000),

('ex20_032','hanging-leg-raise','Hanging Leg Raise','strength',
 '["rectus_abdominis","hip_flexors","core"]',
 '["strength","core","low_impact","no_floor"]',
 '["pull_up_bar"]',
 '{"steps":["Hang from the bar with both hands, arms fully extended. Brace your core to prevent swinging.","Keeping your legs straight (or bent for easier variation), raise them until parallel to the floor or higher.","Lower slowly — don''t let momentum swing your legs back down."],"cues":["💡 Posterior pelvic tilt as you raise — curl your tailbone up to fully engage the abs.","Bent knees = easier, straight legs = harder. Master bent before going straight."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["v-up","dead-bug","hollow-body-hold"]}',
 1,1744700000000,1744700000000),

('ex20_033','dead-hang','Dead Hang','strength',
 '["shoulder_girdle","grip","forearms","spine"]',
 '["strength","mobility","low_impact","no_floor","shoulder_health"]',
 '["pull_up_bar"]',
 '{"steps":["Grab the bar with both hands just wider than shoulder-width, palms facing away.","Let your body hang fully — allow your shoulders to rise toward your ears (passive hang) or actively depress them (active hang).","Breathe steadily, hold for the prescribed duration, then step down."],"cues":["💡 Passive hang decompresses the spine. Active hang builds shoulder stability. Both are useful.","Build grip strength progressively — start with 20-second holds."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["scapular-retraction-hang","pull-up"]}',
 1,1744700000000,1744700000000),

('ex20_034','scapular-retraction-hang','Scapular Pull (Bar Hang)','strength',
 '["lower_traps","serratus_anterior","shoulder_girdle"]',
 '["strength","mobility","low_impact","no_floor","shoulder_health"]',
 '["pull_up_bar"]',
 '{"steps":["Hang from the bar in a dead hang with arms fully extended.","Without bending your elbows, depress your shoulder blades — your body will rise slightly.","Hold for a second, then let the shoulder blades rise back to the passive hang position."],"cues":["💡 This is a small movement — 2–3 cm rise, not a full pull-up.","Builds the shoulder stability required for safe, strong pull-ups."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dead-hang","pull-up"]}',
 1,1744700000000,1744700000000),

-- BODYWEIGHT STRENGTH (7) --

('ex20_035','hollow-body-hold','Hollow Body Hold','strength',
 '["rectus_abdominis","hip_flexors","core"]',
 '["strength","core","low_impact","floor"]',
 '["none"]',
 '{"steps":["Lie on your back, arms extended overhead. Press your lower back flat into the floor.","Lift your arms, head, and legs simultaneously — legs straight, toes pointed, lower back stays flat.","Hold this banana-shaped position. Lower everything if your back lifts off the floor."],"cues":["💡 The test: you should be able to slide a hand under your lower back — if you can, you''ve broken form.","Start with legs higher (easier) and progress toward parallel over time."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["v-up","dead-bug","modified-plank"]}',
 1,1744700000000,1744700000000),

('ex20_036','v-up','V-Up','strength',
 '["rectus_abdominis","hip_flexors","core"]',
 '["strength","core","low_impact","floor"]',
 '["none"]',
 '{"steps":["Lie on your back, arms extended overhead, legs straight.","Simultaneously lift your legs and torso toward each other — arms reach toward your toes, forming a ''V'' shape.","Lower back to the floor with control."],"cues":["💡 If you can''t keep legs straight, bend your knees — maintain quality over range.","Exhale sharply as you rise; inhale as you lower."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["hollow-body-hold","hanging-leg-raise","dead-bug"]}',
 1,1744700000000,1744700000000),

('ex20_037','bear-crawl','Bear Crawl','strength',
 '["core","shoulders","quads","hip_flexors"]',
 '["strength","core","cardio","low_impact","floor"]',
 '["none"]',
 '{"steps":["Start on all fours — hands under shoulders, knees under hips. Hover knees 2–3 cm off the floor.","Move forward by stepping right hand + left knee simultaneously, then left hand + right knee.","Keep your back flat and hips level — the hover forces your core to stabilize."],"cues":["💡 Slow and controlled beats fast and sloppy — quality movement is the goal.","Reverse crawl (backward) is equally effective and challenges coordination."]}'  ,
 '{"supports":["time"],"base_duration_sec":40}',
 '{"substitutions":["plank-shoulder-tap","mountain-climber","hollow-body-hold"]}',
 1,1744700000000,1744700000000),

('ex20_038','nordic-hamstring-curl','Nordic Hamstring Curl','strength',
 '["hamstrings","glutes"]',
 '["strength","posterior_chain","floor","low_impact"]',
 '["chair"]',
 '{"steps":["Kneel on a mat with a partner holding your ankles — or hook your heels under a heavy sofa or secured bar.","With your body upright, lower your torso toward the floor as slowly as you can.","Catch yourself with your hands, then push back up to the kneeling position."],"cues":["💡 The eccentric (lowering) phase is where the hamstring strength is built — make it slow.","This is hard. Even 3–5 slow reps builds significant hamstring resilience."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-single-leg-rdl","good-morning-bodyweight","dumbbell-romanian-deadlift"]}',
 1,1744700000000,1744700000000),

('ex20_039','inverted-row-table','Inverted Row (Under Table)','strength',
 '["lats","rhomboids","rear_deltoid","biceps"]',
 '["strength","pull","low_impact","floor"]',
 '["none"]',
 '{"steps":["Lie under a sturdy table, grip the edge with both hands roughly shoulder-width apart.","Keeping your body in a straight line from head to heels, pull your chest up to the table edge.","Lower slowly until your arms are straight."],"cues":["💡 The more horizontal your body, the harder it is — start with knees bent for more upright angle.","The table version is a genuine pull-up alternative for those without a bar."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["pull-up","band-row-seated","dumbbell-bent-over-row"]}',
 1,1744700000000,1744700000000),

('ex20_040','reverse-plank','Reverse Plank','strength',
 '["glutes","hamstrings","erector_spinae","triceps","rear_deltoid"]',
 '["strength","posterior_chain","low_impact","floor"]',
 '["none"]',
 '{"steps":["Sit on the floor, hands behind you, fingers pointing forward or outward. Feet flat on the floor.","Push through your hands and heels to lift your hips until your body forms a straight line from head to heels.","Hold the position, squeezing your glutes and keeping your chin slightly tucked."],"cues":["💡 A neglected posterior chain exercise — great complement to planks and push-ups.","If wrists hurt, make fists or use push-up handles to stay neutral."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["hollow-body-hold","dumbbell-hip-thrust","supported-glute-bridge"]}',
 1,1744700000000,1744700000000),

('ex20_041','pistol-squat-assist','Assisted Pistol Squat','strength',
 '["quads","glutes","hip_flexors","core"]',
 '["strength","low_impact","unilateral","floor"]',
 '["chair"]',
 '{"steps":["Stand in front of a chair or wall for balance. Extend one leg in front of you, slightly bent.","Lower yourself slowly on the standing leg until you tap the chair or reach your comfortable depth — keep the elevated leg straight.","Drive through the standing heel to rise back to standing."],"cues":["💡 Holding a counterweight (light dumbbell) actually makes balancing easier.","This is a skill as much as a strength exercise — patience with the progression."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["dumbbell-bulgarian-split-squat","reverse-lunge","lateral-lunge"]}',
 1,1744700000000,1744700000000),

-- ════════════════════════════════════════════════════════════════════════════
-- C. MOBILITY (15)
-- ════════════════════════════════════════════════════════════════════════════

('ex20_042','ninety-ninety-hip-switch','90/90 Hip Switch','mobility',
 '["hip_external_rotators","hip_internal_rotators","glutes","adductors"]',
 '["mobility","low_impact","floor","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit on the floor with both legs bent at 90°: one knee in front, one to the side (like a butterfly leg bent behind you).","Slowly rotate through your hips to switch both legs to the mirror position — front leg goes back, back leg comes forward.","Work through your comfortable range, pausing when you feel tightness."],"cues":["💡 The goal is smooth hip rotation — not a hip hike or spine twist.","Both external and internal rotation improve with this single drill."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["half-kneeling-hip-opener","pigeon-pose","couch-stretch"]}',
 1,1744700000000,1744700000000),

('ex20_043','couch-stretch','Couch Stretch','mobility',
 '["hip_flexors","quads","psoas"]',
 '["mobility","low_impact","floor"]',
 '["none"]',
 '{"steps":["Kneel with one knee on the floor, rear foot propped up the wall or a sofa behind you.","Tuck your pelvis under and press your hips forward until you feel the stretch in the front of the rear hip.","Hold, breathing steadily. Switch sides."],"cues":["💡 One of the most effective hip flexor stretches — especially for desk workers.","Don''t arch your lower back to go further. Posterior tilt first, then move."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["hip-flexor-stretch","half-kneeling-hip-opener","ninety-ninety-hip-switch"]}',
 1,1744700000000,1744700000000),

('ex20_044','cat-cow-flow','Cat-Cow Spinal Flow','mobility',
 '["erector_spinae","core","spine"]',
 '["mobility","low_impact","floor","pregnancy_safe","postnatal_safe","breathing"]',
 '["none"]',
 '{"steps":["On all fours, wrists under shoulders, knees under hips. Neutral spine to start.","Inhale: let your belly drop toward the floor, gently lifting your tailbone and chin (cow).","Exhale: round your spine toward the ceiling, tucking your chin and tailbone (cat). Repeat slowly."],"cues":["💡 Move with your breath — inhale for cow, exhale for cat.","Move one vertebra at a time — wave through the spine rather than hinging at one spot."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["seated-thoracic-rotation","active-thoracic-rotation","cat-cow-pregnancy"]}',
 1,1744700000000,1744700000000),

('ex20_045','leg-swings-front-back','Active Leg Swings (Front/Back)','mobility',
 '["hip_flexors","hamstrings","glutes"]',
 '["mobility","low_impact","no_floor","dynamic"]',
 '["none"]',
 '{"steps":["Stand sideways to a wall, one hand touching for balance. Shift weight to the inner leg.","Swing the outer leg forward and back in a relaxed pendulum motion — gradually increasing the range.","After reps, turn and repeat on the other side."],"cues":["💡 Relaxed, not forced — let momentum build the range over successive swings.","Active warm-up for running, cycling, or any lower-body session."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["leg-swings-lateral","hip-flexor-stretch","couch-stretch"]}',
 1,1744700000000,1744700000000),

('ex20_046','leg-swings-lateral','Active Leg Swings (Side to Side)','mobility',
 '["hip_abductors","adductors","glute_medius"]',
 '["mobility","low_impact","no_floor","dynamic"]',
 '["none"]',
 '{"steps":["Face a wall, both hands lightly touching for balance. Weight on one foot.","Swing the free leg across your body and then out to the side in a wide arc.","Keep the movement controlled at the extremes — let momentum build gradually."],"cues":["💡 Swing from the hip, not the knee — think wide arc from the pelvis.","Particularly useful before lateral sports and hip-heavy strength training."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["leg-swings-front-back","ninety-ninety-hip-switch","band-lateral-walk"]}',
 1,1744700000000,1744700000000),

('ex20_047','deep-squat-hold','Deep Squat Hold (Malasana)','mobility',
 '["hip_flexors","adductors","ankles","glutes","spine"]',
 '["mobility","low_impact","floor","pregnancy_safe"]',
 '["none"]',
 '{"steps":["Stand with feet wider than shoulder-width, toes angled out 45°.","Lower into a deep squat, bringing your hips below your knees if possible. Press your elbows into your inner knees.","Hold, breathing steadily, letting gravity gradually open your hips."],"cues":["💡 Heel elevation (book, plate) helps if ankle mobility limits depth.","This single stretch addresses hip flexors, groin, ankle, and thoracic posture simultaneously."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["ninety-ninety-hip-switch","seated-butterfly","half-kneeling-hip-opener"]}',
 1,1744700000000,1744700000000),

('ex20_048','calf-stretch-wall','Calf Stretch (Wall)','mobility',
 '["gastrocnemius","soleus","achilles_tendon"]',
 '["mobility","low_impact","no_floor","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Face a wall, one foot close to it and the other 60–70 cm behind — rear heel flat on the floor.","Lean forward, pressing into the wall with your hands until you feel the stretch in the rear calf.","For the soleus (deeper calf), bend the rear knee slightly while keeping the heel flat."],"cues":["💡 Straight rear knee = upper calf (gastrocnemius). Bent rear knee = lower calf (soleus). Do both.","Hold 45–60 seconds — calves need time to release."]}'  ,
 '{"supports":["time"],"base_duration_sec":45}',
 '{"substitutions":["ankle-mobility-circles","single-leg-calf-raise","ankle-pumps"]}',
 1,1744700000000,1744700000000),

('ex20_049','active-thoracic-rotation','Active Thoracic Rotation','mobility',
 '["thoracic_spine","obliques","rotator_cuff"]',
 '["mobility","low_impact","floor","pregnancy_safe"]',
 '["none"]',
 '{"steps":["Lie on your side in a foetal position, knees stacked and bent to 90°, arms extended in front.","Keeping your knees together and lower body still, rotate your top arm open toward the ceiling and behind you.","Follow your hand with your eyes. Return and repeat. Switch sides after reps."],"cues":["💡 Breathe out as you open — the exhale relaxes the chest and allows more rotation.","The lower body stays completely still — all movement comes from the thoracic spine."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["seated-thoracic-rotation","cat-cow-flow","seated-spinal-twist"]}',
 1,1744700000000,1744700000000),

('ex20_050','supine-figure-four','Supine Figure-Four Stretch','mobility',
 '["piriformis","glutes","hip_external_rotators"]',
 '["mobility","low_impact","floor","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on your back, knees bent, feet flat. Cross your right ankle over your left knee (figure-four shape).","Option A: stay here for a passive stretch. Option B: reach through and pull your left thigh toward you.","Hold, breathing into the stretch. Switch sides."],"cues":["💡 The closer you pull the thigh, the deeper the stretch — move only as far as comfortable.","Effective for piriformis and posterior hip tightness — often the culprit in lower back pain."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["pigeon-pose","glute-piriformis-stretch","standing-figure-four"]}',
 1,1744700000000,1744700000000),

('ex20_051','lying-hamstring-stretch','Lying Hamstring Stretch','mobility',
 '["hamstrings","calves"]',
 '["mobility","low_impact","floor","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on your back. Bend one knee with foot flat. Extend the other leg and lift it, clasping behind the thigh.","Gently pull the leg toward you until you feel a comfortable stretch along the back of the thigh.","Flex your foot (toes toward your shin) to add calf and sciatic nerve stretch. Hold and switch sides."],"cues":["💡 Keep your lower back flat — don''t let it arch off the floor.","Breathing into the stretch and relaxing on the exhale helps the muscle release further."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["seated-hamstring-stretch","standing-hamstring-stretch","standing-forward-fold"]}',
 1,1744700000000,1744700000000),

('ex20_052','wrist-flexor-stretch','Wrist Flexor Stretch','mobility',
 '["forearm_flexors","wrist"]',
 '["mobility","low_impact","no_floor","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Extend one arm in front, palm facing up. With the other hand, gently bend the fingers toward the floor.","Hold the stretch until you feel it along the inside of your forearm.","Switch to palm facing down (wrist extension stretch) for the opposing muscles. Repeat on both sides."],"cues":["💡 Essential for anyone who types, grips weights, or cycles — often skipped and later regretted.","Gentle pressure only — the wrist is a complex joint."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["forearm-wrist-stretch","wrist-ankle-circles"]}',
 1,1744700000000,1744700000000),

('ex20_053','seated-straddle-stretch','Seated Straddle Stretch','mobility',
 '["adductors","hamstrings","hip_flexors"]',
 '["mobility","low_impact","floor","pregnancy_safe"]',
 '["none"]',
 '{"steps":["Sit on the floor with legs spread wide in a V shape. Sit tall with a neutral spine.","Hinge forward from the hips (not the waist), keeping your back long as you lower your chest toward the floor.","Hold at your comfortable depth. Walk your hands forward to increase the stretch."],"cues":["💡 Sit on a folded blanket if your hips tip back — this immediately improves your fold.","The goal is hip crease going forward, not spine rounding forward."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["seated-butterfly","seated-hamstring-stretch","seated-spinal-twist"]}',
 1,1744700000000,1744700000000),

('ex20_054','lunge-thoracic-rotation','Lunge with Thoracic Rotation','mobility',
 '["hip_flexors","thoracic_spine","obliques","glutes"]',
 '["mobility","low_impact","floor","dynamic"]',
 '["none"]',
 '{"steps":["Step into a lunge, front foot flat, rear knee on or near the floor.","Place both hands on your front thigh. Rotate your torso toward the front leg, reaching the top arm toward the ceiling.","Return to centre and alternate sides each rep."],"cues":["💡 This is one of the best single mobility exercises — hits hip flexors AND thoracic at once.","Move with your breath: inhale to stand tall, exhale to rotate further."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["world-greatest-stretch","active-thoracic-rotation","cat-cow-flow"]}',
 1,1744700000000,1744700000000),

('ex20_055','shoulder-circles-active','Active Shoulder Circles','mobility',
 '["rotator_cuff","deltoids","trapezius"]',
 '["mobility","low_impact","no_floor","dynamic","pregnancy_safe","postnatal_safe","shoulder_health"]',
 '["none"]',
 '{"steps":["Stand with arms at your sides. Begin making small circles forward, gradually increasing the size over 30 seconds.","Reverse the direction — large circles backward for 30 seconds.","Bring arms to a T position and make small backward circles focusing on the rear deltoids."],"cues":["💡 Slow, deliberate circles warm the shoulder capsule better than fast flailing.","Ideal before any upper body session or after a long period of sitting."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["chest-opener-arms","kettlebell-halo","shoulder-roll-stretch"]}',
 1,1744700000000,1744700000000),

('ex20_056','neck-half-circles','Neck Half-Circles','mobility',
 '["cervical_spine","upper_trapezius","sternocleidomastoid"]',
 '["mobility","low_impact","no_floor","pregnancy_safe","postnatal_safe","quiet"]',
 '["none"]',
 '{"steps":["Sit or stand tall. Drop your right ear toward your right shoulder, feeling the stretch on the left side.","Slowly roll your chin forward toward your chest, continuing to the left ear down to the left shoulder.","Reverse the arc back to neutral. Never complete a full circle by taking the head back — that compresses the cervical spine."],"cues":["💡 Front semicircle only — half-circles are safe, full circles backward are not.","Breathe into each stretch position and let the weight of your head do the work."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["neck-stretch","shoulder-roll-stretch"]}',
 1,1744700000000,1744700000000),

-- ════════════════════════════════════════════════════════════════════════════
-- D. RECOVERY — FOAM ROLLING (8) + BREATHWORK / REST (4)
-- ════════════════════════════════════════════════════════════════════════════

('ex20_057','foam-roll-quads','Foam Roll: Quads','recovery',
 '["quadriceps","rectus_femoris"]',
 '["recovery","low_impact","floor"]',
 '["foam_roller"]',
 '{"steps":["Lie face down, foam roller under your thighs. Support yourself on your forearms.","Roll slowly from the top of your knee to just below your hip, pausing on any tight spots for 10–20 seconds.","Turn 30° to one side to target the outer quad (vastus lateralis), then the inner quad."],"cues":["💡 Breathe through tight spots instead of rolling off them.","Overlap each pass slightly — systematic coverage beats random rolling."]}'  ,
 '{"supports":["time"],"base_duration_sec":90}',
 '{"substitutions":["foam-roll-it-band","side-lying-quad-stretch","foam-roll-hip-flexors"]}',
 1,1744700000000,1744700000000),

('ex20_058','foam-roll-it-band','Foam Roll: IT Band','recovery',
 '["iliotibial_band","tensor_fasciae_latae","vastus_lateralis"]',
 '["recovery","low_impact","floor"]',
 '["foam_roller"]',
 '{"steps":["Lie on your side, foam roller under your outer thigh. Support yourself on one forearm, top foot on the floor for stability.","Roll slowly from just above the knee to just below the hip — go slow; this area is often very sensitive.","Pause on tight spots, breathe, and allow the tissue to release before moving on."],"cues":["💡 The IT band itself doesn''t need direct pressure — you''re targeting the muscles that attach to it.","If too painful, stack both feet on the floor to reduce pressure."]}'  ,
 '{"supports":["time"],"base_duration_sec":90}',
 '{"substitutions":["foam-roll-quads","glute-piriformis-stretch","band-lateral-walk"]}',
 1,1744700000000,1744700000000),

('ex20_059','foam-roll-upper-back','Foam Roll: Upper Back','recovery',
 '["thoracic_spine","rhomboids","erector_spinae"]',
 '["recovery","low_impact","floor"]',
 '["foam_roller"]',
 '{"steps":["Sit in front of the foam roller and lean back onto it so it''s positioned across your mid-back.","Support your head with your hands. Gently extend over the roller, opening your chest.","Shift the roller one segment at a time from mid-back toward the top of your shoulder blades."],"cues":["💡 Do not roll the lower back or neck — mid and upper thoracic only.","This is one of the best antidotes to desk posture — spend extra time here."]}'  ,
 '{"supports":["time"],"base_duration_sec":90}',
 '{"substitutions":["thoracic-extension-chair","active-thoracic-rotation","cat-cow-flow"]}',
 1,1744700000000,1744700000000),

('ex20_060','foam-roll-calves','Foam Roll: Calves','recovery',
 '["gastrocnemius","soleus","achilles_tendon"]',
 '["recovery","low_impact","floor"]',
 '["foam_roller"]',
 '{"steps":["Sit on the floor, roller under your calves. Hands behind you for support.","Lift your hips and roll from ankle to just below the knee, pausing on tight spots.","Cross one ankle over the other to increase pressure on one calf at a time."],"cues":["💡 Rotate your foot in and out to reach different angles of the calf muscle.","Essential after running or cycling — tight calves contribute to heel and knee pain."]}'  ,
 '{"supports":["time"],"base_duration_sec":90}',
 '{"substitutions":["calf-stretch-wall","ankle-mobility-circles","foam-roll-quads"]}',
 1,1744700000000,1744700000000),

('ex20_061','foam-roll-glutes','Foam Roll: Glutes','recovery',
 '["gluteus_maximus","piriformis"]',
 '["recovery","low_impact","floor"]',
 '["foam_roller"]',
 '{"steps":["Sit on the foam roller, shifted to one side. Cross your right ankle over your left knee to target the right glute.","Lean into the right side and roll back and forth over the glute, pausing on tight spots.","Switch sides after 45 seconds."],"cues":["💡 The piriformis (deep glute) is often the real culprit in hip and back tightness.","More body weight = more pressure. Use your hands to lift slightly if too intense."]}'  ,
 '{"supports":["time"],"base_duration_sec":90}',
 '{"substitutions":["supine-figure-four","glute-piriformis-stretch","foam-roll-it-band"]}',
 1,1744700000000,1744700000000),

('ex20_062','foam-roll-hip-flexors','Foam Roll: Hip Flexors','recovery',
 '["psoas","iliacus","rectus_femoris"]',
 '["recovery","low_impact","floor"]',
 '["foam_roller"]',
 '{"steps":["Lie face down. Position the foam roller under your right hip crease area (just below the pelvis, where the hip flexor meets the thigh).","Prop yourself on your forearms and slowly explore the area just inside and below the hip bone.","Pause on tight spots and breathe. Gently bend and extend your knee to add active pressure release."],"cues":["💡 This is a small, targeted area — move slowly, the tissue is deep.","High-value for runners, cyclists, and anyone who sits for long periods."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["couch-stretch","hip-flexor-stretch","foam-roll-quads"]}',
 1,1744700000000,1744700000000),

('ex20_063','foam-roll-lats','Foam Roll: Lats','recovery',
 '["latissimus_dorsi","teres_major"]',
 '["recovery","low_impact","floor"]',
 '["foam_roller"]',
 '{"steps":["Lie on your side, roller under your armpit area. Extend the bottom arm overhead.","Roll slowly from just below the armpit to mid-rib cage, pausing on tight spots.","Rotate slightly forward to reach the serratus and rear shoulder area. Switch sides."],"cues":["💡 Tight lats pull the shoulder forward and limit overhead range — rolling here has big payoff.","Straighten and flex your elbow while on a tight spot for active release."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["foam-roll-upper-back","chest-opener-arms","dead-hang"]}',
 1,1744700000000,1744700000000),

('ex20_064','foam-roll-hamstrings','Foam Roll: Hamstrings','recovery',
 '["hamstrings","biceps_femoris"]',
 '["recovery","low_impact","floor"]',
 '["foam_roller"]',
 '{"steps":["Sit on the floor, roller under the back of one thigh. Hands behind for support, other leg crossed over for extra pressure.","Roll from just above the knee to just below the glute, pausing on tight spots.","Rotate your leg in and out to hit different fibers."],"cues":["💡 The bulk of the hamstring is in the middle of the thigh — spend most time there.","Crossing one leg over the other doubles the pressure — use this when you need it."]}'  ,
 '{"supports":["time"],"base_duration_sec":90}',
 '{"substitutions":["lying-hamstring-stretch","seated-hamstring-stretch","foam-roll-calves"]}',
 1,1744700000000,1744700000000),

('ex20_065','supine-knee-to-chest','Supine Knee-to-Chest','recovery',
 '["lower_back","hip_flexors","glutes"]',
 '["recovery","mobility","low_impact","floor","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on your back, knees bent, feet flat. Draw one knee toward your chest with both hands.","Hold the stretch in your lower back and hip. Option: gently rock side to side for a massage effect.","Switch legs after 30–45 seconds. For both legs: draw both knees to chest simultaneously."],"cues":["💡 A simple reset for a tight lower back — effective before getting up in the morning.","Keep the opposite leg relaxed and flat — or bend it if your lower back has trouble."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["pigeon-pose","supine-figure-four","legs-up-wall"]}',
 1,1744700000000,1744700000000),

('ex20_066','happy-baby-pose','Happy Baby Pose','recovery',
 '["hip_flexors","adductors","lower_back"]',
 '["recovery","mobility","low_impact","floor","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie on your back. Draw both knees toward your chest, then open them wide toward the armpits.","Flex your feet and grab the outside edges of each foot (or your ankles or shins if needed).","Gently pull down, drawing the knees toward the floor beside your torso. Rock side to side if it feels good."],"cues":["💡 This is a restorative pose — let gravity do the work over a long hold.","One of the best post-run or post-leg-day hip openers."]}'  ,
 '{"supports":["time"],"base_duration_sec":60}',
 '{"substitutions":["supine-knee-to-chest","seated-butterfly","ninety-ninety-hip-switch"]}',
 1,1744700000000,1744700000000),

('ex20_067','progressive-relaxation-body','Progressive Muscle Relaxation','recovery',
 '["whole_body"]',
 '["recovery","breathing","quiet","floor","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Lie down comfortably. Starting at your feet, tense each muscle group for 5 seconds, then release completely for 10 seconds.","Work up the body in sequence: feet → calves → thighs → glutes → abdomen → hands → forearms → shoulders → face.","Finish with 2 minutes of complete stillness."],"cues":["💡 The contrast between tension and release teaches your nervous system what ''fully relaxed'' actually feels like.","If you fall asleep, that''s fine — your body needed it."]}'  ,
 '{"supports":["time"],"base_duration_sec":600}',
 '{"substitutions":["body-scan-meditation","tension-release-visualization","mindful-body-check"]}',
 1,1744700000000,1744700000000),

('ex20_068','478-breathing','4-7-8 Breathing','recovery',
 '["diaphragm","nervous_system"]',
 '["recovery","breathing","quiet","pregnancy_safe","postnatal_safe"]',
 '["none"]',
 '{"steps":["Sit or lie comfortably. Exhale completely through your mouth.","Inhale quietly through your nose for 4 counts.","Hold your breath for 7 counts. Then exhale completely through your mouth for 8 counts. That is one cycle. Repeat 4 times."],"cues":["💡 The extended exhale activates the parasympathetic nervous system — instant calm.","If 7 counts feels too long, scale the ratio: 2-3.5-4, keeping the 1:2 exhale ratio."]}'  ,
 '{"supports":["time"],"base_duration_sec":180}',
 '{"substitutions":["box-breathing","alternate-nostril-breathing","pursed-lip-breathing"]}',
 1,1744700000000,1744700000000),

-- ════════════════════════════════════════════════════════════════════════════
-- E. CARDIO — NON-RUNNING (12)
-- ════════════════════════════════════════════════════════════════════════════

('ex20_069','speed-skater','Speed Skater','cardio',
 '["glutes","quads","hip_abductors","calves","cardiovascular_system"]',
 '["cardio","high_impact","bodyweight","dynamic","no_floor"]',
 '["none"]',
 '{"steps":["Stand on one leg with a slight bend. Push off laterally, leaping sideways to land on the opposite foot — swing the free leg behind like a speed skater.","Swing your arms across your body as you leap — same-side arm crosses toward the landing leg.","Land softly with a bent knee and immediately push back in the opposite direction."],"cues":["💡 Land as quietly as possible — soft landings protect the knee and build deceleration strength.","The further the leap, the more lateral power you develop."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["skater-hop","lateral-shuffle-drill","grapevine-step"]}',
 1,1744700000000,1744700000000),

('ex20_070','jumping-jack','Jumping Jack','cardio',
 '["cardiovascular_system","calves","shoulders","hip_abductors"]',
 '["cardio","high_impact","bodyweight","dynamic","no_floor"]',
 '["none"]',
 '{"steps":["Stand with feet together, arms at your sides.","Jump your feet out to shoulder width while simultaneously raising your arms overhead.","Jump your feet back together and lower your arms. That is one rep."],"cues":["💡 Land softly with slightly bent knees — protect your joints.","For low-impact: step side to side instead of jumping."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["low-impact-jumping-jacks","high-knees","march-in-place"]}',
 1,1744700000000,1744700000000),

('ex20_071','broad-jump','Broad Jump','cardio',
 '["quads","glutes","calves","hamstrings"]',
 '["cardio","high_impact","bodyweight","power","dynamic"]',
 '["none"]',
 '{"steps":["Stand with feet shoulder-width, knees bent in an athletic stance.","Swing your arms back and explosively drive them forward as you jump as far as possible horizontally.","Land softly with bent knees, absorbing the impact through your legs."],"cues":["💡 The arm swing generates 20–30% of the jump distance — don''t skip it.","Stick your landing for a second to build deceleration strength."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["jump-squat","tuck-jump","power-step-up-jump"]}',
 1,1744700000000,1744700000000),

('ex20_072','cross-country-ski-step','Cross-Country Ski Step','cardio',
 '["hip_flexors","glutes","shoulders","cardiovascular_system"]',
 '["cardio","low_impact","bodyweight","dynamic","no_floor"]',
 '["none"]',
 '{"steps":["Stand with feet staggered, one foot forward, one back. Arms opposite to feet (right arm forward if left foot is forward).","Simultaneously switch your feet and arms in a scissoring motion — like cross-country skiing.","Keep the movement smooth and rhythmic, driving your arms for momentum."],"cues":["💡 Low-impact version of a sprint in terms of cardiovascular demand.","Keep the step width small and quick — bigger steps are harder to sustain."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["grapevine-step","shuffle-tap","lateral-shuffle-drill"]}',
 1,1744700000000,1744700000000),

('ex20_073','alternating-front-kick','Alternating Front Kick','cardio',
 '["hip_flexors","quads","glutes","cardiovascular_system"]',
 '["cardio","low_impact","bodyweight","dynamic","no_floor","balance"]',
 '["none"]',
 '{"steps":["Stand tall, feet hip-width. Shift weight to your left leg.","Kick your right leg forward to hip height (or comfortable height), keeping it reasonably straight. Then lower and switch.","Increase tempo once you have the balance — swing your opposite arm with each kick."],"cues":["💡 Control the lowering phase — don''t let the leg drop back.","Look straight ahead, not down — balance improves immediately."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["high-knees","lateral-knee-raise","standing-bicycle"]}',
 1,1744700000000,1744700000000),

('ex20_074','speed-bag-simulation','Speed Bag Simulation','cardio',
 '["forearms","deltoids","cardiovascular_system"]',
 '["cardio","low_impact","bodyweight","upper_body","dynamic","no_floor"]',
 '["none"]',
 '{"steps":["Raise your hands to face level, elbows bent, hands in loose fists in front of you.","Circle your forearms rhythmically in a forward rolling motion — one in front of the other.","Maintain a steady pace for the duration, keeping elbows at chest height."],"cues":["💡 Excellent active recovery that keeps your heart rate up without impact.","Add small lateral footwork to increase intensity and coordination demand."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["shadow-boxing","standing-bicycle","seated-cardio-punch"]}',
 1,1744700000000,1744700000000),

('ex20_075','stair-climb-simulation','Stair Climb Simulation','cardio',
 '["quads","glutes","calves","cardiovascular_system"]',
 '["cardio","low_impact","bodyweight","dynamic"]',
 '["chair"]',
 '{"steps":["Stand in front of a step, low box, or bottom stair.","Step up with your right foot, then your left, so you''re standing on the step. Step down right, then left.","Increase pace progressively. Lead with the opposite foot each round."],"cues":["💡 Drive through the heel of the stepping foot — not the toe.","Adding a knee drive as you step up turns this into a full lower-body challenge."]}'  ,
 '{"supports":["time"],"base_duration_sec":40}',
 '{"substitutions":["box-step-up","power-step-up-jump","high-knees"]}',
 1,1744700000000,1744700000000),

('ex20_076','lateral-shuffle-drill','Lateral Shuffle Drill','cardio',
 '["glute_medius","quads","calves","cardiovascular_system"]',
 '["cardio","low_impact","bodyweight","agility","dynamic","no_floor"]',
 '["none"]',
 '{"steps":["Stand in an athletic stance, knees slightly bent, weight on the balls of your feet.","Shuffle quickly to the right for 4–5 steps by pushing off your left foot.","Immediately shuffle back to the left. Keep your hips low and your feet never crossing."],"cues":["💡 The lower you stay, the more glute and quad activation you get.","Hips face forward the whole time — this is a lateral movement, not a rotation."]}'  ,
 '{"supports":["time"],"base_duration_sec":40}',
 '{"substitutions":["shuffle-tap","grapevine-step","band-lateral-walk"]}',
 1,1744700000000,1744700000000),

('ex20_077','reverse-lunge-kick','Reverse Lunge to Front Kick','cardio',
 '["quads","glutes","hamstrings","hip_flexors","cardiovascular_system"]',
 '["cardio","low_impact","bodyweight","balance","dynamic","no_floor"]',
 '["none"]',
 '{"steps":["Stand tall. Step your right foot back into a reverse lunge, lowering your rear knee toward the floor.","Drive through your left foot to stand, immediately bringing your right knee up and extending it into a front kick.","Lower your right foot back down and repeat. Switch legs after reps."],"cues":["💡 The kick is controlled, not a wild flick — squeeze the quad at the top.","Your balance leg works hard — this is a coordination and strength challenge as much as cardio."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["reverse-lunge","alternating-front-kick","lateral-knee-raise"]}',
 1,1744700000000,1744700000000),

('ex20_078','power-step-up-jump','Power Step-Up (Explosive)','cardio',
 '["quads","glutes","calves","cardiovascular_system"]',
 '["cardio","high_impact","bodyweight","power","dynamic"]',
 '["chair"]',
 '{"steps":["Stand in front of a sturdy step or box. Place your right foot on the step.","Drive through the right heel to step up explosively, driving your left knee high at the top.","Land softly back on the floor and immediately repeat. Alternate lead legs."],"cues":["💡 The drive comes from the heel of the working leg — not a toe push.","Land with bent knees to absorb impact — quiet landings protect joints."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["box-step-up","jump-squat","broad-jump"]}',
 1,1744700000000,1744700000000),

('ex20_079','walking-lunge','Walking Lunge','cardio',
 '["quads","glutes","hamstrings","hip_flexors"]',
 '["cardio","low_impact","bodyweight","dynamic"]',
 '["none"]',
 '{"steps":["Stand tall with feet together. Step forward with your right foot into a lunge — front knee above ankle, rear knee toward the floor.","Without returning to start, step the rear foot forward to meet the front, then immediately lunge forward with the left foot.","Continue walking forward in this alternating pattern for the prescribed distance or reps."],"cues":["💡 Upright torso — resist leaning forward, even as you get tired.","Long steps challenge glutes and flexibility; shorter steps challenge quads more."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["reverse-lunge","dumbbell-lunge","dumbbell-bulgarian-split-squat"]}',
 1,1744700000000,1744700000000),

('ex20_080','boxing-combination','Boxing Combination','cardio',
 '["shoulders","triceps","core","cardiovascular_system"]',
 '["cardio","low_impact","bodyweight","upper_body","dynamic","no_floor"]',
 '["none"]',
 '{"steps":["Stand in a fighting stance: left foot slightly forward, knees soft, hands up protecting your face.","Throw a jab-cross-hook-uppercut combination: jab (left straight), cross (right straight), hook (left), uppercut (right).","Reset and repeat. Rotate your hips and pivot your feet with each power punch."],"cues":["💡 Power comes from hip rotation, not arm strength — think of the punch starting at your feet.","Light on your feet between combinations — stay in your athletic stance."]}'  ,
 '{"supports":["time"],"base_duration_sec":30}',
 '{"substitutions":["shadow-boxing","speed-bag-simulation","seated-cardio-punch"]}',
 1,1744700000000,1744700000000),

-- ════════════════════════════════════════════════════════════════════════════
-- F. EQUIPMENT-CONDITIONAL: RUNNING / CYCLING / ROWING (20)
-- ════════════════════════════════════════════════════════════════════════════

-- ── RUNNING (7) — generic or treadmill-specific ──────────────────────────

('ex20_081','zone2-easy-run','Zone 2 Easy Run','cardio',
 '["cardiovascular_system","quads","hamstrings","calves","glutes"]',
 '["cardio","low_impact","zone2","conditioning","outdoor"]',
 '["running_shoes","treadmill"]',
 '{"steps":["Set off at a fully conversational pace — you must be able to speak in full sentences throughout.","Maintain steady effort, not pace; if you feel out of breath, slow down.","Finish with a 2-minute walk to cool down."],"cues":["💡 Nasal breathing is a useful guide — if you need to open your mouth, you may be above Zone 2.","Zone 2 builds aerobic base and fat-burning capacity. Boring is the point."]}'  ,
 '{"supports":["time"],"base_duration_sec":1800}',
 '{"substitutions":["easy-run-outdoor","treadmill-run-steady","brisk-walk"]}',
 1,1744700000000,1744700000000),

('ex20_082','fartlek-run','Fartlek Run','cardio',
 '["cardiovascular_system","quads","hamstrings","calves"]',
 '["cardio","high_impact","hiit","conditioning","outdoor"]',
 '["running_shoes"]',
 '{"steps":["Start with a 5-minute easy jog warm-up.","Pick a landmark ahead (lamp post, tree, corner) and run hard to it, then jog easy until fully recovered.","Repeat the hard/easy cycle for the session, varying effort and distance randomly."],"cues":["💡 Fartlek (Swedish for ''speed play'') — unstructured intervals that build both speed and endurance.","The recovery should be genuinely easy — not a moderate jog."]}'  ,
 '{"supports":["time"],"base_duration_sec":1800}',
 '{"substitutions":["run-intervals-outdoor","tempo-run-outdoor","zone2-easy-run"]}',
 1,1744700000000,1744700000000),

('ex20_083','hill-repeats-running','Hill Repeats','cardio',
 '["quads","glutes","calves","cardiovascular_system","hamstrings"]',
 '["cardio","high_impact","hiit","conditioning","outdoor"]',
 '["running_shoes"]',
 '{"steps":["Find a moderate hill (5–8% gradient, 50–150 m long). Jog 5 minutes easy to the base as your warm-up.","Run up the hill at 85–90% effort, focusing on driving your knees and pumping your arms.","Walk or jog back down as recovery. Repeat for the prescribed number of reps."],"cues":["💡 Uphill running builds leg strength and VO2 max faster than flat running.","Lean slightly forward from the ankle, not the waist — keeps form efficient."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["run-intervals-outdoor","fartlek-run","power-step-up-jump"]}',
 1,1744700000000,1744700000000),

('ex20_084','stride-outs','Stride Outs','cardio',
 '["quads","hamstrings","calves","neuromuscular_system"]',
 '["cardio","high_impact","skill","conditioning","outdoor"]',
 '["running_shoes"]',
 '{"steps":["After a 10-minute easy jog, begin striding: gradually accelerate over 80–100 m to about 90% of your top speed.","Hold 90% for the middle third, then gradually decelerate over the final 30 m.","Walk or jog easily back to the start. Recover fully between strides."],"cues":["💡 Strides teach your neuromuscular system what fast feels like — they improve running economy.","Focus on relaxation at speed: loose hands, soft shoulders, tall posture."]}'  ,
 '{"supports":["reps","sets"]}',
 '{"substitutions":["fartlek-run","run-intervals-outdoor","zone2-easy-run"]}',
 1,1744700000000,1744700000000),

('ex20_085','treadmill-intervals','Treadmill Speed Intervals','cardio',
 '["cardiovascular_system","quads","hamstrings","calves"]',
 '["cardio","high_impact","hiit","conditioning","indoor"]',
 '["treadmill"]',
 '{"steps":["Warm up 3–4 minutes at an easy walk/jog. Set the speed to a challenging but sustainable pace.","Run at this elevated speed for 30–60 seconds, then reduce to a recovery pace for 90–120 seconds.","Repeat the work/rest cycle for the session duration. Cool down with 2 minutes of walking."],"cues":["💡 Set the pace before you step on — fumbling the controls during an interval is a distraction.","Use 1% incline throughout to better replicate outdoor running effort."]}'  ,
 '{"supports":["time"],"base_duration_sec":1200}',
 '{"substitutions":["run-intervals-outdoor","treadmill-run-steady","treadmill-hill-run"]}',
 1,1744700000000,1744700000000),

('ex20_086','treadmill-hill-run','Treadmill Hill Run','cardio',
 '["quads","glutes","calves","cardiovascular_system"]',
 '["cardio","high_impact","conditioning","indoor"]',
 '["treadmill"]',
 '{"steps":["Set the treadmill to 6–10% incline at a moderate speed. Warm up 2 minutes at flat and easy.","Run at this elevation for the duration, focusing on uphill mechanics: driving the knees and pumping the arms.","Every 5 minutes, return to flat for 1 minute to recover."],"cues":["💡 Don''t hold the handrails — it removes most of the cardiovascular benefit.","Incline running builds glutes and calves rapidly; reduce speed compared to flat runs."]}'  ,
 '{"supports":["time"],"base_duration_sec":1200}',
 '{"substitutions":["treadmill-run-steady","treadmill-intervals","hill-repeats-running"]}',
 1,1744700000000,1744700000000),

('ex20_087','brisk-walk','Brisk Walking','cardio',
 '["cardiovascular_system","quads","hamstrings","calves","glutes"]',
 '["cardio","low_impact","zone2","conditioning","outdoor"]',
 '["running_shoes","treadmill"]',
 '{"steps":["Walk at a pace that noticeably elevates your heart rate but still allows full conversation.","Swing your arms purposefully and stride forward — not a stroll, a deliberate power walk.","Maintain this effort for the full duration without stopping."],"cues":["💡 Brisk walking at Zone 2 intensity provides cardiovascular benefit with minimal joint impact.","Ideal starting point for beginners, or as active recovery for trained athletes."]}'  ,
 '{"supports":["time"],"base_duration_sec":1800}',
 '{"substitutions":["zone2-easy-run","easy-run-outdoor"]}',
 1,1744700000000,1744700000000),

-- ── CYCLING (6) — all cycling equipment ──────────────────────────────────

('ex20_088','cycling-zone2-ride','Zone 2 Cycling Ride','cardio',
 '["quads","hamstrings","glutes","calves","cardiovascular_system"]',
 '["cardio","low_impact","zone2","conditioning","indoor","quiet"]',
 '["road_bike","mountain_bike","indoor_bike","exercise_bike"]',
 '{"steps":["Set resistance so you are pedalling at 80–90 rpm at a cadence that feels like a 4–5 out of 10 effort.","Maintain this steady, conversational pace for the full duration.","If using a smart trainer: target 55–70% of FTP. On a road/exercise bike: you should be able to speak in full sentences."],"cues":["💡 Zone 2 builds your aerobic engine — more base = faster everything else later.","Nasal-only breathing is a useful real-time check that you''re in the zone."]}'  ,
 '{"supports":["time"],"base_duration_sec":2400}',
 '{"substitutions":["steady-indoor-cycle","stationary-bike-steady","cycling-tempo-effort"]}',
 1,1744700000000,1744700000000),

('ex20_089','cycling-tempo-effort','Cycling Tempo Effort','cardio',
 '["quads","hamstrings","glutes","cardiovascular_system"]',
 '["cardio","low_impact","conditioning","indoor"]',
 '["road_bike","mountain_bike","indoor_bike","exercise_bike"]',
 '{"steps":["After a 5-minute easy spin warm-up, settle into a ''comfortably hard'' effort — about 75–85% FTP or 7 out of 10 perceived effort.","Maintain this tempo for 15–30 minutes, then cool down with 5 minutes easy spinning.","Breathe rhythmically and check in on your cadence (aim for 85–95 rpm)."],"cues":["💡 Tempo = you can speak 2–3 words, not full sentences.","Focus on a smooth, powerful pedal stroke — no dead spots at top or bottom."]}'  ,
 '{"supports":["time"],"base_duration_sec":2100}',
 '{"substitutions":["cycling-zone2-ride","cycling-sweet-spot","cycling-intervals-indoor"]}',
 1,1744700000000,1744700000000),

('ex20_090','cycling-hill-climb','Cycling Hill Climb Effort','cardio',
 '["quads","glutes","hamstrings","calves","core","cardiovascular_system"]',
 '["cardio","strength","low_impact","conditioning","indoor"]',
 '["road_bike","mountain_bike","indoor_bike","exercise_bike"]',
 '{"steps":["Increase resistance to simulate a 6–10% gradient. Reduce cadence to 60–75 rpm.","Push through the pedals with power — heavier resistance, seated. You can also alternate seated and standing.","Climb for 5–10 minutes, then reduce resistance to spin easy for 3 minutes. Repeat."],"cues":["💡 Climbing builds power and muscular endurance simultaneously.","On a road bike outdoors, pick a real hill and ride tempo effort to the top."]}'  ,
 '{"supports":["time"],"base_duration_sec":1800}',
 '{"substitutions":["cycling-tempo-effort","cycling-zone2-ride","cycling-sweet-spot"]}',
 1,1744700000000,1744700000000),

('ex20_091','cycling-sprint-intervals','Cycling Sprint Intervals','cardio',
 '["quads","glutes","hamstrings","cardiovascular_system"]',
 '["cardio","high_intensity","hiit","low_impact","conditioning","indoor"]',
 '["road_bike","mountain_bike","indoor_bike","exercise_bike"]',
 '{"steps":["Warm up 5–8 minutes easy spinning. Reach 90+ rpm cadence.","Sprint all-out for 10–20 seconds — maximum effort, maximum cadence.","Recover easy spinning for 90–120 seconds. Repeat 6–10 times."],"cues":["💡 Short sprints train peak power output — the effort must be maximal or the adaptation is lost.","Stand on the pedals for the sprint if on a stationary setup; remain seated on a smart trainer."]}'  ,
 '{"supports":["time"],"base_duration_sec":1200}',
 '{"substitutions":["cycling-intervals-indoor","cycling-pyramid-effort","cycling-tempo-effort"]}',
 1,1744700000000,1744700000000),

('ex20_092','cycling-sweet-spot','Cycling Sweet Spot Training','cardio',
 '["quads","hamstrings","glutes","cardiovascular_system"]',
 '["cardio","low_impact","conditioning","indoor"]',
 '["road_bike","mountain_bike","indoor_bike","exercise_bike"]',
 '{"steps":["Target 88–93% of FTP (or perceived effort: 7–7.5 out of 10). Harder than tempo, easier than VO2 max.","Hold this ''sweet spot'' effort in blocks of 10–20 minutes with 5 minutes easy between blocks.","Cadence: 85–95 rpm. Finish with 5 minutes easy cool-down."],"cues":["💡 Sweet spot gives 80% of the adaptation of full threshold riding for 60% of the recovery cost.","Breathing is laboured but rhythmic — you can say a word or two, not sentences."]}'  ,
 '{"supports":["time"],"base_duration_sec":2400}',
 '{"substitutions":["cycling-tempo-effort","cycling-hill-climb","cycling-zone2-ride"]}',
 1,1744700000000,1744700000000),

('ex20_093','cycling-pyramid-effort','Cycling Pyramid Intervals','cardio',
 '["quads","glutes","cardiovascular_system"]',
 '["cardio","high_intensity","hiit","low_impact","conditioning","indoor"]',
 '["road_bike","mountain_bike","indoor_bike","exercise_bike"]',
 '{"steps":["After a 5-minute warm-up, build intervals in a pyramid: 1 min hard / 1 min easy, 2 min hard / 2 min easy, 3 min hard / 3 min easy, then back down: 2 min hard / 2 min easy, 1 min hard.","Hard intervals at 90–95% effort. Easy intervals genuinely easy.","Cool down 5 minutes easy."],"cues":["💡 The pyramid structure ensures variety in duration and intensity within a single session.","Mark your effort at each pyramid step and try to sustain the same perceived effort throughout."]}'  ,
 '{"supports":["time"],"base_duration_sec":1980}',
 '{"substitutions":["cycling-sprint-intervals","cycling-sweet-spot","cycling-intervals-indoor"]}',
 1,1744700000000,1744700000000),

-- ── ROWING (5) ────────────────────────────────────────────────────────────

('ex20_094','rowing-2k-time-trial','Rowing 2K Time Trial','cardio',
 '["legs","back","shoulders","arms","core","cardiovascular_system"]',
 '["cardio","strength","full_body","high_intensity","hiit","indoor","low_impact"]',
 '["rowing_machine"]',
 '{"steps":["Set the monitor to row 2000 metres. Warm up 5 minutes easy, building to a moderate pace.","Row the full 2K at maximal sustained effort. Go out at target pace, hold it through the middle, lift in the last 500 m.","After finishing, easy paddle 5 minutes to recover — your heart rate will be high."],"cues":["💡 Negative split strategy: rows 1000–1500 m feeling controlled, then build from 1500 m onward.","Record your split time and use it as your benchmark for future sessions."]}'  ,
 '{"supports":["time"],"base_duration_sec":600}',
 '{"substitutions":["rowing-intervals","rowing-pyramid-intervals","rowing-steady-state"]}',
 1,1744700000000,1744700000000),

('ex20_095','rowing-pyramid-intervals','Rowing Pyramid Intervals','cardio',
 '["legs","back","arms","core","cardiovascular_system"]',
 '["cardio","strength","full_body","high_intensity","hiit","indoor","low_impact"]',
 '["rowing_machine"]',
 '{"steps":["Warm up 3 minutes easy. Row hard intervals in a pyramid: 30s / 60s / 90s / 2 min / 90s / 60s / 30s.","Rest equals the work interval between each. Hard intervals at near-maximum effort.","Cool down 3 minutes easy."],"cues":["💡 The 2-minute peak is the hardest — pace yourself on the way up so you can sustain it.","Keep the drive sequence correct even at high intensity: legs → back → arms."]}'  ,
 '{"supports":["time"],"base_duration_sec":1500}',
 '{"substitutions":["rowing-intervals","rowing-2k-time-trial","rowing-steady-state"]}',
 1,1744700000000,1744700000000),

('ex20_096','rowing-technique-drill','Rowing Technique Drill','cardio',
 '["legs","back","core"]',
 '["cardio","skill","full_body","low_impact","indoor","quiet"]',
 '["rowing_machine"]',
 '{"steps":["Row at a very slow rate (16–18 spm) and low pressure, focusing entirely on sequence: LEGS → BACK → ARMS (drive), then ARMS → BACK → LEGS (recovery).","Pause at three positions: arms only at the finish, halfway up the slide, and at the catch (shins vertical).","After each pause, check your posture before moving to the next segment."],"cues":["💡 Correct sequencing at slow speed becomes automatic at race pace.","This is NOT about getting a cardiovascular workout — quality of movement is everything."]}'  ,
 '{"supports":["time"],"base_duration_sec":900}',
 '{"substitutions":["rowing-steady-state","rowing-pyramid-intervals"]}',
 1,1744700000000,1744700000000),

('ex20_097','rowing-power-strokes','Rowing Power Strokes','cardio',
 '["legs","back","arms","glutes","core","cardiovascular_system"]',
 '["cardio","strength","full_body","high_intensity","hiit","low_impact","indoor"]',
 '["rowing_machine"]',
 '{"steps":["Row easy for 3 minutes as a warm-up. Then, within each minute, perform 10 strokes at maximum power followed by the rest of the minute easy.","The 10 power strokes should be explosive — push your split significantly lower than normal.","Repeat this 1-minute cycle for 10 minutes. Cool down 2 minutes easy."],"cues":["💡 Count the 10 strokes carefully — after 10, immediately drop back to easy.","This develops raw power without accumulating excessive fatigue."]}'  ,
 '{"supports":["time"],"base_duration_sec":780}',
 '{"substitutions":["rowing-intervals","rowing-pyramid-intervals","rowing-2k-time-trial"]}',
 1,1744700000000,1744700000000),

('ex20_098','rowing-zone2','Rowing Zone 2 Steady','cardio',
 '["cardiovascular_system","legs","back","core"]',
 '["cardio","zone2","full_body","low_impact","indoor","quiet"]',
 '["rowing_machine"]',
 '{"steps":["Set your target split at a pace you can maintain conversationally — about 2:20–2:40 /500 m for beginners, 2:00–2:20 for intermediate.","Row at rate 18–20 strokes per minute. Focus on maintaining consistent split without drift.","Hold this for the full duration. End with 2 minutes of easy paddling."],"cues":["💡 Zone 2 rowing is particularly effective as a full-body aerobic base builder.","Check every 5 minutes that your split hasn''t crept up — if it has, that''s fatigue: adjust."]}'  ,
 '{"supports":["time"],"base_duration_sec":1800}',
 '{"substitutions":["rowing-steady-state","rowing-technique-drill","cycling-zone2-ride"]}',
 1,1744700000000,1744700000000),

-- ── OUTDOOR CYCLING + TRAIL RUNNING (2) ──────────────────────────────────

('ex20_099','cycling-outdoor-easy','Easy Outdoor Ride','cardio',
 '["quads","hamstrings","glutes","calves","cardiovascular_system"]',
 '["cardio","low_impact","zone2","conditioning","outdoor"]',
 '["road_bike","mountain_bike"]',
 '{"steps":["Set off at an easy, conversational effort — about Zone 2. Pick a flat or gently rolling route.","Maintain 80–90 rpm cadence in a gear that feels manageable but not too easy.","Cool down with a 5-minute very easy spin before stopping."],"cues":["💡 For outdoor cycling, traffic-safe awareness is a skill — plan a safe route in advance.","Shift gears to maintain cadence, not to increase resistance."]}'  ,
 '{"supports":["time"],"base_duration_sec":3600}',
 '{"substitutions":["cycling-zone2-ride","cycling-tempo-effort","brisk-walk"]}',
 1,1744700000000,1744700000000),

('ex20_100','trail-run-easy','Easy Trail Run','cardio',
 '["quads","hamstrings","calves","glutes","cardiovascular_system","proprioception"]',
 '["cardio","high_impact","outdoor","conditioning","zone2"]',
 '["running_shoes"]',
 '{"steps":["Choose a trail suitable for your fitness level — wide, well-maintained paths for beginners.","Run at an easy, conversational effort. Reduce to a walk on uphills; pick it back up on the flat.","Focus on where your feet land — uneven terrain demands present-moment attention."],"cues":["💡 Trail running strengthens the stabilisers around your ankles, knees, and hips faster than road running.","Effort over pace — hills will slow your pace; let them. The effort counts."]}'  ,
 '{"supports":["time"],"base_duration_sec":2400}',
 '{"substitutions":["easy-run-outdoor","zone2-easy-run","fartlek-run"]}',
 1,1744700000000,1744700000000);
