-- 0032_enrich_instructions.sql
-- Enriches exercises that had thin/placeholder instructions with proper
-- best-practice coaching steps and cues. Does NOT change any other columns.

-- ── Diamond Push-up ───────────────────────────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Start in a push-up position with your hands close together directly beneath your chest — thumbs and index fingers touching to form a diamond or triangle shape.","Brace your core and lower your chest toward your hands, keeping your elbows tucked close to your sides. They should brush your ribs on the way down, not flare out.","Press back up to full arm extension, squeezing your triceps hard at the top.","Maintain a rigid plank throughout — hips level, no sagging at the waist or piking at the hips."],"cues":["Triceps do most of the work here — think of this as a tricep exercise that also loads the chest.","Elbows stay close to your ribs throughout — if they flare wide, you lose the tricep emphasis entirely.","💡 💡 Beginner: elevate hands on a chair to reduce load. Advanced: use a 3-second controlled descent for maximum time under tension."]}' WHERE slug = 'diamond-push-up';

-- ── Wall Sit ──────────────────────────────────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Stand with your back flat against a smooth wall, feet roughly 60 cm out from the wall and shoulder-width apart, toes pointing forward.","Slide down the wall until your thighs are parallel to the floor and your knees form a 90-degree angle. Both your lower and upper back should stay in contact with the wall.","Press your heels into the floor and breathe steadily. Keep your arms relaxed at your sides or resting on your thighs — no pushing off with your hands.","When your knees creep above 90° or you lose contact with the wall, the set is done. Step up from the position rather than sliding further."],"cues":["Weight in your heels — you should be able to wiggle your toes without shifting forward.","Quads burning is normal and expected. Stop if you feel sharp pain in your knees, not just burn in your muscles.","💡 💡 Intermediate: hold dumbbells across your thighs to increase load. Advanced: add a slow calf raise hold while maintaining position."]}' WHERE slug = 'wall-sit';

-- ── Goblet Squat ──────────────────────────────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Hold a dumbbell vertically at chest height, both hands cupping the top end, elbows pointing down. Stand with feet shoulder-width apart, toes turned out 15-30 degrees.","Take a breath in. Push your hips back and bend your knees, lowering until your thighs reach parallel to the floor or deeper. Keep the dumbbell close to your chest throughout.","At the bottom, your elbows can press lightly against the inside of your knees — this helps keep them tracking outward over your toes.","Drive through your heels to stand. Squeeze your glutes firmly at the top and exhale. Repeat."],"cues":["The weight in front naturally counterbalances you — use it to sit into a deeper position than a regular squat.","Chest stays tall the entire way down and up. The moment the dumbbell pulls you forward, go lighter.","💡 💡 Beginner: squat only as deep as you can with a flat back. Advanced: pause 2 seconds at the bottom before driving up."]}' WHERE slug = 'goblet-squat';

-- ── Dumbbell Shoulder Press ───────────────────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Sit or stand with dumbbells at shoulder height, palms facing forward. Elbows should be at roughly 90 degrees and just below the level of your ears — not dropped too low or flared too high.","Press both dumbbells straight overhead until your arms are fully extended. Exhale on the way up. Do not lock out your elbows hard at the top.","Lower slowly and with control back to the starting position, elbows returning to 90 degrees. Inhale on the way down.","Keep your core firmly braced throughout — avoid arching your lower back as the weight goes overhead."],"cues":["Wrists stay stacked over elbows throughout — wrists bending backward increases injury risk and reduces power transfer.","If you feel pinching at the front of the shoulder, try a neutral grip (palms facing each other) — this externally rotates the shoulder into a safer position.","💡 💡 Seated removes the option to use leg drive, making it a purer shoulder challenge. Standing adds full-body stability demand."]}' WHERE slug = 'dumbbell-shoulder-press';

-- ── Dumbbell Lateral Raise ────────────────────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Stand holding dumbbells at your sides, a slight but fixed bend in your elbows. Lean forward very slightly from the hips — about 10-15 degrees. This angle is not optional — it moves the line of pull onto the lateral deltoid.","Raise both arms out to the sides in a wide arc until they reach shoulder height. As you lift, rotate your thumbs slightly downward — pinkies higher than thumbs at the top, as if pouring from a jug.","Pause for one beat at the top with full tension on the side delts, then lower slowly over 2-3 seconds. Fight the dumbbells on the way down.","If you are swinging or shrugging to get the weight up, drop to a lighter dumbbell."],"cues":["Lead with your elbows, not your hands — this cue keeps the lateral delt loaded instead of the traps.","Pinkies-up rotation at the top is not a stylistic choice — it closes the subacromial space and prevents impingement.","💡 💡 Lateral raises are notoriously weight-ego-busting. Most people use half the weight they think they need and get twice the results."]}' WHERE slug = 'dumbbell-lateral-raise';

-- ── Dumbbell Floor Press ──────────────────────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Lie on your back with knees bent, feet flat on the floor. Hold a dumbbell in each hand directly over your chest, arms extended, palms facing your feet.","Bend your elbows and lower the dumbbells in a controlled arc until your upper arms lightly contact the floor. Keep elbows at roughly 45 degrees from your torso — not straight out to your sides.","Without bouncing, press back up from the floor contact point. Exhale on the press. Squeeze your chest at the top.","The floor acts as a built-in range-of-motion limit — it protects your shoulder by preventing overstretching at the bottom."],"cues":["Wrists stay stacked over elbows throughout — wrists bending backward is a form break and injury risk.","Never bounce off the floor — the pause and press from a dead stop is what makes this version effective.","💡 💡 The shorter range of motion compared to bench press means you can often handle more volume safely. Excellent for building the upper chest."]}' WHERE slug = 'dumbbell-floor-press';

-- ── Step-Up ───────────────────────────────────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Stand in front of a stable chair, step, or bench that places your thigh at or near 90 degrees when your foot is on it. Place your entire right foot flat on the surface — heel included.","Drive through the right heel to step up, bringing your left knee up to hip height as you stand tall on the step. Avoid pushing off with the trail foot.","Stand tall at the top — fully extend the standing hip before lowering. Then lower your left foot slowly and with control back to the floor, followed by the right foot.","Complete all reps on the right side, then switch to the left, or alternate legs each rep."],"cues":["Push through the heel of the elevated foot — the glute of that leg should do the work, not a push-off from the floor foot.","Slow the descent — lowering with control builds more strength than a sloppy step-down.","💡 💡 Add dumbbells at your sides to progress once bodyweight feels easy. Increase the step height to increase the range of motion challenge."]}' WHERE slug = 'box-step-up';

-- ── Child''s Pose — add cues (was 0 cues) ─────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Kneel on a mat and sit your hips back toward your heels. Separate your knees as wide as comfortable or keep them together — both variations work.","Reach your arms forward along the floor and lower your forehead to the mat. Let your chest sink toward the ground.","Breathe slowly and deeply. With each exhale, allow your hips to settle a little further back and your spine to lengthen."],"cues":["Wider knees gives a deeper hip stretch and more space for your torso. Knees together emphasises the lower back stretch.","Breathe into your lower back — you should feel it expand laterally with each inhale. This is passive decompression.","💡 Use this as a reset between hard sets or as the final pose of any session. There is no wrong way to rest here."]}' WHERE slug = 'childs-pose';

-- ── Standing Quad Stretch ─────────────────────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Stand on one leg — rest your free hand on a wall, chair back, or doorframe for balance. Shift your weight solidly onto the supporting foot.","Bend your other knee and bring your heel toward your glute. Reach back with the same-side hand and hold your ankle — not your foot. If your hand cannot reach, use a strap or towel.","Gently pull your heel closer to your glutes while pressing your hip forward slightly on the stretching side. Your stretching knee should point straight down, not drift outward.","Hold 20-30 seconds with steady breathing, then slowly release and switch sides. Never force the range — let the stretch come to you."],"cues":["Knees together is the key cue — the stretch is significantly reduced if the bent knee drifts wide of the standing leg.","Stand tall with both hips level — hiking one hip ruins the quad alignment and reduces the stretch.","Pressing the stretching hip slightly forward adds a hip flexor component — valuable for anyone who sits for long periods."]}' WHERE slug = 'standing-quad-stretch';

-- ── Couch Stretch — improve specificity ───────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Kneel with your back to a wall or sofa. Slide your rear foot up the wall so the top of your foot and shin are resting against it — this stretches the hip flexor of that rear leg.","Bring your front foot forward and plant it flat on the floor so your front knee is directly over your ankle, thigh roughly parallel to the floor.","Squeeze the glute of the rear leg firmly and tuck your pelvis slightly. This activates the stretch — without the glute squeeze you will just feel it in your knee, not your hip flexor.","Hold for 60-90 seconds, breathing steadily. Switch sides."],"cues":["Squeezing the glute of the rear leg is not optional — it is what moves the stretch from the knee to the hip flexor where it belongs.","Upright torso throughout — if you are leaning forward, bring your front foot further out.","💡 💡 One of the most effective hip flexor stretches available — essential for runners, cyclists, and anyone who sits. 60-90 seconds per side minimum to see results."]}' WHERE slug = 'couch-stretch';

-- ── 90/90 Hip Switch — improve coaching ───────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Sit on the floor with both knees bent at 90 degrees — one leg in front of you (shin perpendicular to your torso), one leg to the side (shin parallel to your torso). Sit tall with a neutral spine.","Rotate both knees to the opposite side simultaneously — the front leg becomes the back leg and vice versa. Your hips pivot as you switch.","Pause briefly in the new position, sitting as tall as possible before switching back. That is one rep."],"cues":["Keep the rotation driven from your hips, not from leaning your torso — the goal is hip mobility, not body sway.","If you cannot get both shins to the floor without pain, sit on a folded blanket to reduce the hip angle demand.","💡 💡 This exercise builds the internal and external hip rotation range that protects the hips and lower back long-term. Slow and intentional is far more effective than fast reps."]}' WHERE slug = 'ninety-ninety-hip-switch';

-- ── Deep Squat Hold — improve coaching ───────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Stand with feet slightly wider than shoulder-width, toes turned out 30-45 degrees. Lower into a full squat — hips below knees — and hold the bottom position.","Press your elbows against the inside of your knees to gently push them outward. Keep your chest up and spine long. Heels should stay flat on the floor.","Hold for the prescribed duration, breathing steadily. If your heels rise, place a folded towel or small weight plate under them while you work on ankle mobility."],"cues":["This position is a baseline of human mobility — if it is uncomfortable, it is a signal that hips, ankles, or thoracic spine need mobility work.","Elbows pressing knees open is both a coaching cue and a stretch — it actively opens the hips from the inside.","💡 💡 Practice daily for 60-second holds. Ankle dorsiflexion is the most common limiting factor — calf stretching and raised heels bridge the gap while you build it."]}' WHERE slug = 'deep-squat-hold';

-- ── Calf Stretch Wall — improve detail ────────────────────────────────────
UPDATE exercises SET instructions_json = '{"steps":["Stand facing a wall, arms extended, hands flat on the wall at chest height. Step one foot back about 60-90 cm, keeping it pointing straight forward and the heel flat on the floor.","Lean gently into the wall by bending your front knee, keeping the rear knee straight and the rear heel grounded. Feel the stretch in the calf of the rear leg (gastrocnemius stretch).","After 20-30 seconds, slightly bend the rear knee — keeping the heel down. This shifts the stretch deeper into the lower calf (soleus). Hold another 20 seconds.","Switch legs and repeat."],"cues":["Both versions matter: straight knee targets the gastrocnemius (upper calf), bent knee targets the soleus (lower calf). Neither replaces the other.","Heel stays down throughout — if it rises, step closer to the wall.","💡 Tight calves are a major contributor to plantar fasciitis, Achilles issues, and knee pain. This stretch is worth doing daily, especially for runners."]}' WHERE slug = 'calf-stretch-wall';
