-- 0034: Enrich exercise instructions — 25 strength / mobility / recovery exercises
-- Adds proper coaching cues (💡) and detailed steps to exercises with minimal content.

-- ── Dumbbell — Back ──────────────────────────────────────────────────────────

UPDATE exercises SET instructions_json = '{"steps":["Stand with feet hip-width, hinge forward 45° keeping your back flat. Hold a dumbbell in each hand, arms hanging straight down.","Drive your elbows back toward your hips, pulling the dumbbells to your lower ribcage. Squeeze your shoulder blades together at the top.","Lower with control — resist the weight pulling your shoulders forward."],"cues":["💡 Hinge first, row second — set the flat back before you pull anything.","Think elbows to back pockets, not hands to chest. The elbow leads the movement."]}' WHERE slug = 'dumbbell-row';

UPDATE exercises SET instructions_json = '{"steps":["Place your left hand and left knee on a bench for support. Hold the dumbbell in your right hand, arm hanging straight below your shoulder.","Row the dumbbell to your hip, keeping your elbow close to your torso. At the top your upper arm should be roughly parallel to the floor.","Lower slowly until your arm is fully extended. Complete all reps, then switch sides."],"cues":["💡 Keep your working shoulder level — do not let it rotate up to help the lift.","Elbow to pocket, not elbow to ceiling. The lat does the pulling, not the shoulder."]}' WHERE slug = 'dumbbell-single-arm-row';

UPDATE exercises SET instructions_json = '{"steps":["Stand with feet shoulder-width, hinge at the hips until your torso is near parallel to the floor, knees soft. Hold both dumbbells with a neutral grip.","Row both dumbbells to your lower ribcage simultaneously, driving elbows behind you. Squeeze your upper back hard at the top.","Lower with full control — do not let gravity win the eccentric portion."],"cues":["💡 Your lower back is bracing isometrically the whole time — engage your core before every rep.","If you are bouncing or jerking, the weight is too heavy. Controlled rows build more muscle."]}' WHERE slug = 'dumbbell-bent-over-row';

UPDATE exercises SET instructions_json = '{"steps":["Brace your working arm elbow against the inside of your thigh. Hold the dumbbell hanging straight down, arm fully extended.","Curl the dumbbell toward your shoulder, keeping your upper arm completely still — only your forearm moves. Squeeze hard at the top.","Lower with full control until your arm is fully extended. Complete all reps, then switch sides."],"cues":["💡 Bracing your elbow on your thigh eliminates swinging — it is all bicep, all the time.","Slow down the lowering phase — the eccentric builds as much strength as the curl up."]}' WHERE slug = 'dumbbell-concentration-curl';

UPDATE exercises SET instructions_json = '{"steps":["Stand tall holding dumbbells with an overhand grip (palms facing down), arms fully extended at your sides.","Curl both dumbbells toward your shoulders, keeping elbows fixed at your sides. The palms-down grip targets the brachialis and forearms more than a standard curl.","Lower slowly — the eccentric with an overhand grip is demanding. Reach full extension between every rep."],"cues":["💡 Weaker here than in a standard curl? Good — you have found a real weak link. This builds forearm thickness most people neglect.","Keep your wrists neutral — do not let them roll under during the curl."]}' WHERE slug = 'dumbbell-reverse-curl';

-- ── Dumbbell — Chest ─────────────────────────────────────────────────────────

UPDATE exercises SET instructions_json = '{"steps":["Lie flat on the floor holding dumbbells above your chest, palms facing forward, upper arms resting on the floor.","Lower the dumbbells until your upper arms touch the floor, pausing briefly. Keep your wrists stacked over your elbows throughout.","Press back up explosively, stopping just before full elbow lockout to keep tension in the chest."],"cues":["💡 The pause at the bottom removes stored elastic energy — every rep starts from nothing, making this harder and more effective than a bench press.","Keep your lower back flat on the floor throughout. No arching."]}' WHERE slug = 'dumbbell-chest-press-floor';

UPDATE exercises SET instructions_json = '{"steps":["Lie flat on the floor holding a dumbbell in each hand above your chest. Maintain a slight, permanent bend in your elbows — never fully straight.","Open your arms wide, lowering in an arc until your upper arms touch the floor. Feel the stretch across your chest.","Squeeze your chest to bring the dumbbells back together above your sternum, following the same arc."],"cues":["💡 The floor acts as a natural depth stop — your arms cannot drop past it, which protects your shoulder joint.","Think hugging a large barrel: the motion is an arc, not a press. Chest drives it, not arms."]}' WHERE slug = 'dumbbell-floor-chest-fly';

-- ── Dumbbell — Shoulders ─────────────────────────────────────────────────────

UPDATE exercises SET instructions_json = '{"steps":["Sit or stand holding two dumbbells at shoulder height, palms facing your face — as if you just finished a bicep curl.","Press the weights overhead while rotating your palms to face forward. Finish with arms fully extended above your head.","Reverse: lower back to the start position, rotating palms back toward your face. That is one rep."],"cues":["💡 The rotation is the whole point — it recruits all three heads of the deltoid, not just the front like a standard press.","Brace your core at the top. Avoid arching your lower back as the dumbbells reach full extension."]}' WHERE slug = 'dumbbell-arnold-press';

UPDATE exercises SET instructions_json = '{"steps":["Stand with feet hip-width holding a dumbbell in each hand at your sides. Raise both dumbbells out to the sides until your arms are parallel to the floor, leading with your elbows slightly.","Hold briefly at the top — do not let momentum carry the weight. Your palms should face down at the top.","Lower slowly — 3 seconds down. The eccentric builds the rear and lateral deltoid far more than the lift up."],"cues":["💡 Lighter than you think — lateral raises with heavy weight turn into a trap shrug. Use a weight you can control fully.","Slight forward lean (10–15 degrees) shifts more load onto the lateral deltoid and less onto the trap."]}' WHERE slug = 'dumbbell-lateral-raise';

-- ── Dumbbell — Legs & Glutes ─────────────────────────────────────────────────

UPDATE exercises SET instructions_json = '{"steps":["Stand in front of a bench or chair. Place your rear foot on it, laces down. Hold a dumbbell in each hand. Step your front foot forward far enough that your shin stays close to vertical when you descend.","Lower your rear knee toward the floor by bending your front knee. Keep your torso tall throughout — resist the urge to lean forward.","Drive up through your front heel to full hip extension. That is one rep. Complete all reps on one side before switching."],"cues":["💡 Most of the work should be felt in the front leg glute and quad. If you feel it mainly in your knee, step your front foot further forward.","This is a balance challenge as much as a strength exercise — go light until you own the position."]}' WHERE slug = 'dumbbell-bulgarian-split-squat';

UPDATE exercises SET instructions_json = '{"steps":["Sit on the floor with your upper back against a bench, shoulder blades on the edge. Place a dumbbell horizontally across your hips. Feet flat, hip-width apart.","Drive through your heels to push your hips up until your body forms a straight line from knees to shoulders. Squeeze your glutes hard at the top.","Lower your hips back toward the floor with control. That is one rep."],"cues":["💡 The glute squeeze at the top is the whole exercise — a half-contracted glute produces half the benefit.","Tuck your chin slightly and brace your core to avoid over-extending your lower back."]}' WHERE slug = 'dumbbell-hip-thrust';

UPDATE exercises SET instructions_json = '{"steps":["Stand tall holding a dumbbell in one or both hands. Shift your weight onto one leg, keeping a soft bend in that knee.","Hinge forward at the hip, letting the dumbbell travel down your standing leg as your non-working leg extends behind you. Keep your hips square — resist rotating.","Return to standing by driving through your heel and squeezing your glute at the top. That is one rep."],"cues":["💡 Think of your back leg and torso as one rigid plank — they move together as a unit, not independently.","The range ends where your hip rotation starts. Do not chase extra depth at the cost of a square pelvis."]}' WHERE slug = 'dumbbell-single-leg-rdl';

UPDATE exercises SET instructions_json = '{"steps":["Stand tall holding a dumbbell at your side. Step wide out to one side, keeping toes pointing forward or slightly out on both feet.","Bend the stepping knee and sit into that hip. Keep the opposite leg straight. Let the dumbbell hang beside the bent knee.","Push off the bent foot to return to standing. Complete all reps on one side, then switch."],"cues":["💡 The lateral motion demands hip abductor strength and inner thigh flexibility — two things most training programs completely miss.","Keep your back flat and chest up as you sit into the lunge. If you round forward, the weight is too heavy."]}' WHERE slug = 'dumbbell-side-lunge';

UPDATE exercises SET instructions_json = '{"steps":["Hold a single dumbbell in one hand at your side — suitcase style. Stand tall with shoulders level and equal.","Walk forward for the prescribed distance or time, resisting any side-bend toward the weight. Keep your core braced, eyes forward, breathing steady.","At the halfway point, switch hands and return."],"cues":["💡 The challenge is resisting the lean — the moment you tip toward the weight, your core has lost the battle.","Slower and heavier beats fast and light. A loaded carry is a posture and bracing exercise, not a conditioning sprint."]}' WHERE slug = 'dumbbell-suitcase-carry';

-- ── Dumbbell — Core / Mixed ──────────────────────────────────────────────────

UPDATE exercises SET instructions_json = '{"steps":["Get into a high plank with a dumbbell under each hand. Feet wider than hip-width for stability. Body forms a straight line from head to heels.","Row one dumbbell to your hip while pressing the other into the floor. Keep your hips completely level — resist any rotation or tilting.","Return the dumbbell to the floor, then row the other side. Both sides equal one rep."],"cues":["💡 The anti-rotation demand is the real exercise here. A wobbling hip means your core, not your back, is the limiting factor.","Go lighter than you expect. This is not a heavy rowing movement — it is a plank with a row attached."]}' WHERE slug = 'dumbbell-renegade-row';

-- ── Resistance Bands ─────────────────────────────────────────────────────────

UPDATE exercises SET instructions_json = '{"steps":["Sit on the floor with legs extended. Loop the band around your feet or a fixed anchor. Hold both ends with arms extended, back tall.","Row your elbows back behind you, squeezing your shoulder blades together. Bring your hands to your lower ribcage.","Return with control — resist the band pulling you forward. Do not round your back on the way out."],"cues":["💡 Sit tall the entire time — a rounded spine shifts the load to your lower back instead of your lats.","Pause for a full second at peak contraction before releasing. That pause is where the muscle gets built."]}' WHERE slug = 'band-row-seated';

UPDATE exercises SET instructions_json = '{"steps":["Anchor the band at face height. Hold one end in each hand with an overhand grip, arms extended forward.","Pull the band toward your face, driving your elbows wide and high. Your hands should finish level with your ears, elbows above shoulder height.","Return to start with control. Resist the band pulling your hands back together."],"cues":["💡 Face pulls are the antidote to too much pressing — they balance the shoulder and develop the rear deltoid that most people neglect.","Elbows high and wide is the essential cue. If your elbows drop, you are doing a row, not a face pull."]}' WHERE slug = 'band-face-pull';

UPDATE exercises SET instructions_json = '{"steps":["Stand on the center of the band with feet hip-width. Hold one end in each hand with an underhand grip, arms extended at your sides.","Curl both hands toward your shoulders, keeping your elbows pinned to your sides. Maintain steady tension throughout the movement.","Lower slowly — the resistance stays on all the way down, unlike with free weights."],"cues":["💡 Band resistance peaks at full extension and is minimal at the start — the opposite of a dumbbell. Great for end-range bicep strength.","Keep your elbows locked in place. If they drift forward, the work shifts away from the bicep."]}' WHERE slug = 'band-bicep-curl';

UPDATE exercises SET instructions_json = '{"steps":["Place the band just above your knees. Stand in a half-squat position with feet hip-width — there should be constant tension in the band.","Step to the right with your right foot, then bring your left foot in to maintain the hip-width stance. Do not let feet come together.","Walk the prescribed steps in one direction, maintaining the squat depth throughout, then reverse."],"cues":["💡 Staying in the squat is the exercise — the moment you stand up, the glute work stops completely.","Feel the hip abductor activate as you step out. That is the gluteus medius — a muscle critical for knee and hip stability."]}' WHERE slug = 'band-lateral-walk';

UPDATE exercises SET instructions_json = '{"steps":["Stand on the center of the band with feet shoulder-width. Hold the ends at shoulder height, elbows forward. Create tension in the band before starting.","Press overhead until arms are fully extended. Core braced — do not let your lower back arch as the arms rise.","Lower slowly back to shoulder height, controlling the band the entire way down."],"cues":["💡 The band gets harder as it stretches — the top of the press is the most demanding portion, unlike free weights.","Keep your ribs down throughout. Overhead pressing quickly exposes any lower back weakness."]}' WHERE slug = 'band-overhead-press';

UPDATE exercises SET instructions_json = '{"steps":["Stand on the center of the band with feet shoulder-width. Hold the ends at shoulder height or crossed over your chest.","Squat down — hips back and down, chest tall, knees tracking over toes. Go to at least parallel depth.","Drive through your heels to stand, feeling the band resistance increase as you approach the top. Squeeze glutes at lockout."],"cues":["💡 Band squats load the top of the movement differently from free weights — this trains lockout strength and hip extension power.","Use the tension at the top as a cue to push your knees out. The band mimics the feedback of a barbell perfectly."]}' WHERE slug = 'band-squat';

UPDATE exercises SET instructions_json = '{"steps":["Anchor the band at ankle height. Loop the other end around one ankle. Stand with the anchor to your side or in front, holding a wall for balance if needed.","Lift your outside leg out to the side against the band, keeping it straight. Your hip drives the movement — not your lower back.","Lower slowly — resist the band pulling your leg in. Complete all reps, then switch sides."],"cues":["💡 This targets the gluteus medius — the hip stabiliser critical for knee alignment when running, landing, and squatting.","Do not tilt your torso as you lift. If you lean, the load has moved from your hip to your back."]}' WHERE slug = 'band-hip-abduction-standing';

-- ── Kettlebell ───────────────────────────────────────────────────────────────

UPDATE exercises SET instructions_json = '{"steps":["Hold the kettlebell vertically with both hands cupping the top of the bell at your chest. Stand with feet shoulder-width, toes angled out 15 to 30 degrees.","Squat down with the kettlebell close to your chest — its weight counterbalances you and pulls you into a deep, upright position.","Drive through your heels to stand, squeezing your glutes at the top. That is one rep."],"cues":["💡 The goblet position forces an upright torso and deep hip flexion — this is one of the best teaching tools for a perfect squat pattern.","Knees track over toes throughout. If they cave in, use your elbows to push them out on the way down."]}' WHERE slug = 'kettlebell-goblet-squat';

UPDATE exercises SET instructions_json = '{"steps":["Clean the kettlebell to the rack position: bell resting on your forearm, elbow close to your body, wrist neutral, fist at shoulder height.","Press straight up until your arm is fully locked out overhead. Keep your core braced and avoid side-bending.","Lower the bell back to the rack position with control. Complete all reps, then switch sides."],"cues":["💡 The rack position is a skill in itself — the bell should rest on your forearm, not dangle from your wrist.","A single-arm press reveals any imbalance between sides immediately. Start with your weaker arm."]}' WHERE slug = 'kettlebell-single-arm-press';

UPDATE exercises SET instructions_json = '{"steps":["Hold the kettlebell with both hands at chest height, arms slightly bent. Stand with feet shoulder-width.","Move the bell in a circular path around your head: left side, over the top, right side, and back to start. Keep the circle controlled and close to your head.","Complete the prescribed reps, then reverse direction for the same number."],"cues":["💡 The halo challenges shoulder mobility and stability simultaneously — go slow enough to feel the control demand.","Keep your core braced and avoid leaning. If you are tilting to follow the bell, slow down."]}' WHERE slug = 'kettlebell-halo';

UPDATE exercises SET instructions_json = '{"steps":["Stand tall holding the kettlebell in one hand at your side. Shift your weight to the opposite leg, soft bend in the knee.","Hinge at the hip, letting the kettlebell travel down your standing leg as your non-working leg extends behind you. Hips stay square.","Return to standing by driving through your heel and squeezing your glute. That is one rep. Complete all reps, then switch sides."],"cues":["💡 Think of your back leg and torso as a single rigid plank — they rotate as one unit around your hip joint.","The range ends where your pelvis rotates. Quality over depth: a square hip at 45 degrees beats a rotated hip at 90."]}' WHERE slug = 'kettlebell-single-leg-rdl';

UPDATE exercises SET instructions_json = '{"steps":["Stand with the kettlebell between your feet, feet just wider than shoulder-width. Hinge at the hips to grip it with both hands — flat back, hips above knees, chest up.","Push the floor away with your legs while driving your hips forward. Keep the bell close to your body as it rises — it should travel up your shins.","Stand tall at the top: hips and knees locked, core tight. Lower by hinging first, then bending the knees. Set the bell down under control."],"cues":["💡 This is a hinge, not a squat. Your hips descend back and behind you, not straight down.","Keep the bell directly over the mid-foot throughout. A bell that drifts forward puts unnecessary strain on your lower back."]}' WHERE slug = 'kettlebell-deadlift';

-- ── Mobility ─────────────────────────────────────────────────────────────────

UPDATE exercises SET instructions_json = '{"steps":["Start on all fours — hands under shoulders, knees under hips. Spine is neutral, no sag or arch.","Inhale: let your belly drop, lift your chest and tailbone gently toward the ceiling (cow position). Eyes look slightly forward.","Exhale: round your entire spine upward, tuck your chin to your chest and your tailbone under (cat position). Feel the stretch across your upper back."],"cues":["💡 Let your breath drive the movement — cow on the inhale, cat on the exhale. This links movement to your nervous system, not just your joints.","Move slowly and intentionally. This is mobility work, not a warm-up speed drill."]}' WHERE slug = 'cat-cow';

UPDATE exercises SET instructions_json = '{"steps":["Stand or sit tall. Roll both shoulders forward in large, slow circles — feel the full range at the top and back of each circle. Complete 10 reps forward.","Reverse: roll both shoulders backward in the same large circles. Focus on pulling the shoulder blades together and down at the back of each circle.","Finish with a chest stretch: clasp your hands behind your back, squeeze your shoulder blades together, and lift your hands gently. Hold for 20 seconds."],"cues":["💡 Most people only roll the tops of their shoulders. Exaggerate the backward phase — pulling blades back and down is where desk-worker tension lives.","Slow down. Shoulder rolls done quickly produce zero mobility benefit."]}' WHERE slug = 'shoulder-roll-stretch';

-- ── Recovery ─────────────────────────────────────────────────────────────────

UPDATE exercises SET instructions_json = '{"steps":["Lie down or sit comfortably with eyes closed. Start at your feet: curl your toes tight for 5 seconds, then release completely. Notice the difference.","Work systematically upward — calves, thighs, glutes, abdomen, hands, forearms, shoulders, face. Tense each area for 5 seconds, then let go fully.","After the final release, lie still for 60 seconds. Breathe naturally and observe the heaviness in your body."],"cues":["💡 The contrast between tension and release is the mechanism — your nervous system learns what genuine relaxation feels like, then can reproduce it.","If your mind wanders, guide it back with the question: what is the least tense part of my body right now?"]}' WHERE slug = 'progressive-muscle-relaxation';
