-- 0045: Import 103 resolved military exercises into exercises table
--
-- Source: defensie-exercise-catalogue-import-ready.json (107 entries, 4 deferred)
-- Deferred (needs_review=true, not imported):
--   optillen-vanaf-de-grond         (confidence: low — load/object unspecified)
--   til-draagtest-full-exercise     (confidence: medium — test load unspecified)
--   til-draagtest-gewicht-plaatsen-naar-heupen (confidence: medium — load unspecified)
--   hardlopen-zone-3-5-minuten      (confidence: medium — name/duration conflict)
--
-- Strategy: INSERT WHERE NOT EXISTS slug — preserves existing rows for conflicts.
-- Exercises already present from migrations 0029-0034 (push-up, squat, back-squat etc.)
-- will be SKIPPED; their existing rows take precedence.
--
-- Timestamp: 2025-05-03 UTC (1746230400000)

INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '31e428cb-06fe-58f7-b602-79a8e66ab1ff','12-minuten-loop','12 minuten loop (Cooper test)','cardio','[]','[]','["running", "fitness-test", "baseline", "endurance", "military"]','["none"]','{"steps": ["Run as many meters as possible in 12 minutes at a sustainable pace"], "cues": ["Baseline fitness test (nul-meting)", "Track total distance covered", "Pace yourself — do not sprint early"]}','{"supports": ["time", "distance"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='12-minuten-loop');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '32f881e8-689e-5a97-854a-ba9b73487b58','back-squat','Back squat','strength','["quads", "glutes"]','["hamstrings", "abs"]','["lower-body", "compound", "barbell", "military"]','["barbell"]','{"steps": ["Position barbell on upper back across trapezius", "Stand with feet shoulder-width apart", "Brace core and squat down until thighs reach parallel", "Drive through heels to return to standing"], "cues": ["Keep chest tall throughout", "Knees track over toes", "5 sets × 10 reps, 30 s rest"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='back-squat');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '8e938d23-760e-5f70-b081-0e26fc11c685','bicycle-crunch','Bicycle crunch','strength','["abs"]','["obliques"]','["core", "bodyweight", "supine", "crunch"]','["none"]','{"steps": ["Lie on back with hands behind head, knees raised to 90°", "Bring right elbow toward left knee while extending right leg", "Switch sides in a cycling motion"], "cues": ["4 sets × 10 s", "30 s rest", "Do not pull on neck"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='bicycle-crunch');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'c2b7401d-a65a-5b0d-a34f-5e9d70a30cb6','bird-dog','Bird dog','strength','["abs", "obliques"]','["glutes", "lats"]','["core", "stability", "bodyweight"]','["none"]','{"steps": ["Start on hands and knees with wrists under shoulders, knees under hips", "Extend right arm forward and left leg back simultaneously", "Hold briefly, return, switch sides"], "cues": ["4 sets × 10 s per side", "30 s rest", "Keep hips level — do not rotate", "Move slowly and deliberately"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='bird-dog');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '7bad1d09-5c86-52ba-90ce-333e508024ce','broad-jump','Broad jump','strength','["glutes", "quads"]','["calves", "abs"]','["plyometric", "power", "lower-body", "high_impact", "military"]','["none"]','{"steps": ["Stand with feet shoulder-width apart", "Swing arms back, dip hips", "Explosively drive arms forward and jump as far as possible", "Land with soft knees, absorb impact"], "cues": ["5 sets × 3 reps", "2 min rest", "Focus on maximum horizontal distance", "Land quietly — control the descent"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='broad-jump');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'c6118498-2ce0-5b30-81bb-c7c54601d5f5','burpee','Burpee','mixed','["chest", "abs"]','["delts_front", "quads", "glutes"]','["full-body", "bodyweight", "high_impact", "circuit", "military"]','["none"]','{"steps": ["Stand tall with feet hip-width apart", "Drop hands to floor, jump or step feet back to plank", "Perform a push-up (optional)", "Jump feet back to hands", "Jump up explosively with arms overhead"], "cues": ["30 s effort then 1 min rest", "Repeat circuit 3× total", "Modify by stepping instead of jumping if needed"]}','{"supports": ["time", "reps"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='burpee');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'ba374bd2-0be0-55f9-8486-19605191a2ed','clean-pull','Clean Pull','strength','["lats", "traps", "glutes"]','["delts_front", "abs", "quads"]','["power", "full-body", "compound", "military"]','["barbell"]','{"steps": ["Stand with barbell over mid-foot, feet hip-width", "Grip barbell double-overhand, hinge to bar", "Maintain straight back, pull bar up the legs explosively", "Drive hips through and shrug forcefully as bar passes thighs — do not catch"], "cues": ["3 sets × 10 reps", "30 s rest", "Keep bar close to the body throughout"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='clean-pull');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '645254e8-4dcb-52a3-b16c-9504340b1484','cooling-down','Cooling-down','recovery','[]','[]','["cool-down", "stretching", "mobility"]','["none"]','{"steps": ["Easy jog or walk for 5 minutes (zone 1 pace)", "Perform static stretches for major muscle groups (quads, hamstrings, calves, hip flexors)"], "cues": ["Low intensity", "Hold each stretch 20–30 s", "Breathe deeply throughout"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='cooling-down');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '460d4641-e048-5874-aa5c-7059483cf017','counter-movement-jump','Counter Movement Jump','strength','["quads", "glutes"]','["calves", "abs"]','["plyometric", "power", "bodyweight", "high_impact", "military"]','["none"]','{"steps": ["Stand with feet shoulder-width apart, arms at sides", "Quickly dip hips and swing arms down", "Explosively extend hips, knees and ankles while swinging arms up", "Jump as high as possible", "Land softly with bent knees"], "cues": ["30 s effort", "Reset briefly between jumps", "Focus on maximum height"]}','{"supports": ["reps", "time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='counter-movement-jump');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '52008a55-f68c-544f-ab1f-6c0dbe30ddc0','dead-bug','Dead bug','strength','["abs"]','["obliques"]','["core", "stability", "bodyweight", "supine"]','["none"]','{"steps": ["Lie on back with arms pointing to ceiling and knees bent at 90° above hips", "Slowly lower opposite arm and leg toward the floor simultaneously", "Keep lower back flat against the floor throughout", "Return and repeat on other side"], "cues": ["4 sets × 10 s per side", "30 s rest", "Breathe out as you extend", "Never let the lower back arch"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='dead-bug');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '651944bc-7774-5ad5-84dd-51aa1d1d4bae','deadlift','Deadlift','strength','["glutes", "hamstrings"]','["lats", "abs", "traps"]','["lower-body", "compound", "military"]','["barbell"]','{"steps": ["Stand with barbell (or weighted rucksack/box) over mid-foot, feet hip-width", "Hinge at hips and grip object firmly", "Brace core, keep back straight, press floor away to lift", "Lock hips and knees fully at top", "Lower with control"], "cues": ["3 sets × sustained effort", "30 s rest", "Can substitute barbell with filled rucksack or sturdy box", "Flat back throughout — do not round"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='deadlift');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '57f04eea-1efe-5d06-bd36-9ff32a89b03b','flutter-kicks','Flutter kicks','strength','["abs"]','[]','["core", "bodyweight", "supine"]','["none"]','{"steps": ["Lie on back, hands under lower back for support", "Lift both legs a few centimetres off the floor", "Alternately raise and lower each leg in small controlled movements"], "cues": ["4 sets × 10 s", "30 s rest", "Keep lower back pressed to floor", "Do not hold breath"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='flutter-kicks');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '9c4fd06a-322b-50dd-b654-2861eda7f2ea','front-squat','Front Squat','strength','["quads"]','["glutes", "abs"]','["lower-body", "compound", "barbell", "military"]','["barbell"]','{"steps": ["Position barbell on front deltoids with elbows high and forward", "Stand with feet shoulder-width apart", "Squat down keeping torso upright until thighs reach parallel", "Drive through legs to return to standing"], "cues": ["3 sets × sustained effort", "30 s rest", "Elbows high throughout — prevents bar from rolling forward"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='front-squat');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'b8c5a70f-6717-5706-b0fd-7a002c4b844a','goblet-squat','Goblet squat','strength','["quads", "glutes"]','["abs"]','["lower-body", "compound", "military"]','["dumbbell"]','{"steps": ["Hold a dumbbell or kettlebell vertically at chest height with both hands", "Stand with feet slightly wider than shoulder-width, toes slightly out", "Squat down keeping torso upright until elbows reach inside knees", "Drive through heels to return to standing"], "cues": ["3 sets × 10 reps", "30 s rest", "Chest stays tall", "Elbows push knees out at the bottom"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='goblet-squat');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'dec95c63-6b1d-5705-be5d-914cec868099','hand-release-push-up','Hand release Push up','strength','["chest"]','["delts_front", "triceps"]','["upper-body", "push", "bodyweight", "prone", "military"]','["none"]','{"steps": ["Start in push-up position with hands below shoulders", "Lower entire body to the floor under control", "Momentarily lift hands off the floor (release)", "Replace hands, push explosively back to start"], "cues": ["5 sets × 10 reps", "2 min rest", "Fast execution", "Full body in contact with floor at bottom"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hand-release-push-up');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '61e60c7f-887c-5a74-8de1-7aefbaac6aea','heup-brug','Heup brug','strength','["glutes"]','["hamstrings", "lower_back"]','["lower-body", "glutes", "bodyweight", "supine"]','["none"]','{"steps": ["Lie on back with knees bent and feet flat on floor hip-width apart", "Press through heels and drive hips upward until body forms a straight line from shoulders to knees", "Squeeze glutes at top, hold briefly", "Lower with control"], "cues": ["4 sets × 10 s", "30 s rest", "Do not hyperextend the lower back at top", "Keep core braced throughout"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='heup-brug');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'f0eee5dd-8c23-5afe-9014-1bbea2a4605a','high-pull','High Pull','strength','["traps", "delts_front", "delts_rear"]','["lats", "abs", "quads"]','["power", "full-body", "compound", "military"]','["barbell"]','{"steps": ["Stand with barbell at hip height, feet shoulder-width", "Begin as a deadlift pull, then explosively drive hips and shrug strongly", "Pull bar high with elbows leading until bar reaches chest/chin height", "Lower with control"], "cues": ["5 sets × 10 reps", "2 min rest", "Bar stays close to the body", "Elbows must stay higher than wrists"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='high-pull');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'b0e9ef04-3cda-59b1-aab9-8e1ab001f1f3','lunge','Lunge','strength','["quads", "glutes"]','["hamstrings"]','["lower-body", "unilateral", "bodyweight", "circuit", "military"]','["none"]','{"steps": ["Stand tall with feet hip-width apart", "Step one foot forward and lower the back knee toward the floor", "Keep front shin vertical and torso upright", "Push through front heel to return to start", "Alternate legs"], "cues": ["30 s effort per circuit round", "1 min rest between rounds", "Repeat circuit 3× total", "Do not let front knee collapse inward"]}','{"supports": ["time", "reps"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='lunge');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '9980d6e8-ff36-5bc9-8e4b-9167c7807790','mountain-climber','Mountain Climber','mixed','["abs", "obliques"]','["delts_front", "chest"]','["full-body", "bodyweight", "cardio", "circuit", "military"]','["none"]','{"steps": ["Start in high plank position with hands under shoulders", "Drive one knee toward chest, then quickly alternate legs in a running motion"], "cues": ["30 s effort", "1 min rest", "Repeat circuit 3× total", "Keep hips level — do not let them rise"]}','{"supports": ["time", "reps"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='mountain-climber');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'a883e6b1-9f59-5c2a-93c7-d3c4af7b5ff9','optillen-vanaf-de-grond-rugzak','Optillen vanaf de grond (rugzak)','strength','["glutes", "quads"]','["lats", "abs"]','["power", "lower-body", "weighted", "military"]','["rucksack"]','{"steps": ["Stand over a loaded rucksack on the floor", "Hinge at hips and knees with flat back, grip rucksack handles", "Lift rucksack from ground to hip height explosively", "Lower with control"], "cues": ["3 sets × 30 s", "30 s rest", "Keep back straight — do not round"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='optillen-vanaf-de-grond-rugzak');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'fabb91a7-1fc4-58db-8913-58b7d1270023','plyo-push-up','Plyo Push Up','strength','["chest"]','["delts_front", "triceps"]','["upper-body", "push", "bodyweight", "plyometric", "high_impact", "prone", "military"]','["none"]','{"steps": ["Start in push-up position", "Lower chest to floor under control", "Explode upward pushing hard enough for hands to leave the floor", "Land softly with bent elbows and immediately descend for next rep"], "cues": ["5 sets × 3–10 reps", "2 min rest", "Explosive push = maximum force", "Land with control each time"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='plyo-push-up');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '8e061b4f-b54d-537d-8ab0-fafe0ab170bb','push-up','Push Up','strength','["chest"]','["delts_front", "triceps", "abs"]','["upper-body", "push", "bodyweight", "prone", "military"]','["none"]','{"steps": ["Start in high plank with hands slightly wider than shoulders", "Lower chest toward floor keeping body rigid", "Push back to start"], "cues": ["30 s effort, 30 s rest", "Keep hips level — no sagging or piking", "Modify: knees on floor if needed"]}','{"supports": ["reps", "time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='push-up');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '2d8a7f87-6da3-5a85-a582-ea4433b1be8f','shoulder-tap','Shoulder tap','strength','["abs", "obliques"]','["delts_front"]','["core", "stability", "bodyweight"]','["none"]','{"steps": ["Start in high plank position with hands under shoulders and feet hip-width apart", "While maintaining stable hips, lift right hand and tap left shoulder", "Return and repeat with left hand to right shoulder"], "cues": ["4 sets × 10 s", "30 s rest", "Resist rotation — hips stay square", "Wider foot stance makes it easier"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='shoulder-tap');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '0c67f8f4-f8d9-545e-ac42-7ddfbe0b33dc','single-leg-deadlift','Single Leg Deadlift','strength','["glutes", "hamstrings"]','["abs"]','["lower-body", "unilateral", "balance", "bodyweight"]','["none"]','{"steps": ["Stand on one leg with a soft knee", "Hinge forward at hip while simultaneously extending the free leg back", "Lower torso until approximately parallel to floor", "Return to standing by driving the standing hip forward"], "cues": ["4 sets × 10 reps per leg", "2 min rest", "Keep hips square", "Slight bend in standing knee throughout"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='single-leg-deadlift');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '701fef69-7cfc-5b6a-916b-0c5f2887eeaa','split-squat','Split Squat','strength','["quads", "glutes"]','["hamstrings"]','["lower-body", "unilateral", "bodyweight"]','["none"]','{"steps": ["Step one foot forward into a lunge stance and stay stationary", "Lower the rear knee toward the floor keeping front shin vertical", "Drive through front foot to return to start"], "cues": ["4 sets × 10 reps per leg", "2 min rest", "Keep torso upright", "Front knee tracks over second toe"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='split-squat');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '5e70bf40-3acc-5023-bfca-ce15e7ecbfa6','squat','Squat','strength','["quads", "glutes"]','["hamstrings"]','["lower-body", "compound", "bodyweight", "military"]','["none"]','{"steps": ["Stand with feet shoulder-width apart, toes slightly out", "Brace core and descend by pushing knees out and sitting back", "Lower until thighs are parallel to floor (or as low as comfortable)", "Drive through heels to return to standing"], "cues": ["3 sets × sustained effort", "30 s rest", "Can be loaded with filled rucksack or box on shoulders", "Chest stays tall — do not lean forward excessively"]}','{"supports": ["reps", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='squat');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '3c95a4f9-ffc5-5c2b-ba80-b457fc282c06','squat-calf-raise','Squat Calf Raise','strength','["quads", "calves"]','["glutes"]','["lower-body", "compound", "bodyweight"]','["none"]','{"steps": ["Stand with feet shoulder-width apart", "Perform a squat", "As you rise back up, continue onto your toes for a calf raise", "Lower heels and immediately begin next squat"], "cues": ["30 s effort, 30 s rest", "Control the calf raise — do not bounce"]}','{"supports": ["reps", "time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='squat-calf-raise');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '3447ec47-f3da-582d-8207-22733d6f872b','squat-jump','Squat Jump','strength','["quads", "glutes"]','["calves", "abs"]','["plyometric", "power", "lower-body", "bodyweight", "high_impact", "military"]','["none"]','{"steps": ["Stand with feet shoulder-width apart", "Squat down to parallel", "Explode upward jumping off both feet", "Land softly with bent knees and immediately descend into next squat"], "cues": ["30 s effort", "1 min rest", "Repeat circuit 3× total", "Land quietly — absorb impact through legs not back"]}','{"supports": ["time", "reps"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='squat-jump');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '02924279-73f8-5057-9be7-eddb4e3a8dda','step-up','Step up','strength','["quads", "glutes"]','["hamstrings"]','["lower-body", "unilateral", "bodyweight"]','["none"]','{"steps": ["Stand in front of a step, box or bench (knee height approximately)", "Step up with one foot, drive through that heel to stand fully on the surface", "Bring the trailing foot up to join, then step back down", "Alternate lead leg"], "cues": ["30 s effort", "Controlled descent", "Keep chest up throughout"]}','{"supports": ["time", "reps"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='step-up');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '395795cd-b354-5456-9473-4e1ec12adbf2','tuck-jump','Tuck Jump','strength','["glutes", "quads"]','["abs", "calves"]','["plyometric", "power", "bodyweight", "high_impact", "military"]','["none"]','{"steps": ["Stand with feet shoulder-width apart", "Explosively jump upward", "Pull both knees toward chest at peak of jump", "Extend legs and land softly with bent knees"], "cues": ["5 sets × 10 s", "2 min rest", "Land quietly — absorb through knees and ankles", "Fast execution"]}','{"supports": ["time", "reps"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='tuck-jump');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '0176a457-5a1e-5c63-9499-a9d071099431','voorwaartse-plank','Voorwaartse plank','strength','["abs", "obliques"]','["delts_front", "glutes"]','["core", "stability", "bodyweight"]','["none"]','{"steps": ["Support body on forearms and toes in a straight line from head to heels", "Forearms flat on floor, elbows directly under shoulders"], "cues": ["4 sets × 10 s", "30 s rest", "Squeeze glutes and abs", "Do not let hips drop or rise"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='voorwaartse-plank');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '068e51c0-7c11-5c1a-bf61-97f4467659f8','walking-lunges','Walking Lunges','strength','["quads", "glutes"]','["hamstrings"]','["lower-body", "unilateral", "bodyweight", "military"]','["none"]','{"steps": ["Step forward with right leg into a lunge, lowering back knee toward floor", "Push through front heel to rise and immediately step forward with left leg into next lunge", "Continue walking forward"], "cues": ["30 s effort", "Keep torso upright", "Controlled descent each rep"]}','{"supports": ["reps", "time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='walking-lunges');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'a46be110-e86b-5abb-9000-a6aa84c51184','warming-up','Warming-up','recovery','[]','[]','["warm-up", "mobility"]','["none"]','{"steps": ["Perform dynamic stretching and movement preparation for 5–10 minutes"], "cues": ["Include: leg swings, arm circles, hip rotations, high knees, butt kicks", "Progressive intensity — start gentle, build to workout pace"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='warming-up');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '86766191-db95-54af-be15-3046fee4bfec','wissel-sprongen','Wissel sprongen','strength','["glutes", "quads"]','["calves", "abs"]','["plyometric", "power", "bodyweight", "high_impact", "military"]','["none"]','{"steps": ["Stand in a split stance with one foot forward, one back", "Jump explosively and switch foot positions in mid-air", "Land softly with opposite foot forward and immediately repeat"], "cues": ["4 sets × 10 s", "30 s rest", "Land softly each rep", "Stay on balls of feet throughout"]}','{"supports": ["time", "reps"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='wissel-sprongen');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'afad7a10-01bb-5d56-ada6-743c01b0500a','zijwaartse-plank','Zijwaartse plank','strength','["obliques"]','["abs", "glutes"]','["core", "stability", "bodyweight"]','["none"]','{"steps": ["Lie on your side and prop up on one forearm with elbow directly below shoulder", "Stack feet or stagger them for stability", "Lift hips so body forms a straight diagonal line from head to feet", "Hold, then repeat on other side"], "cues": ["4 sets × 10 s per side", "30 s rest", "Do not let hips sag or rotate forward", "Squeeze obliques throughout"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='zijwaartse-plank');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '0add4e6a-f1a5-57b2-b601-ff1c14cdd4f2','hardlopen-zone-1-5-minuten-warmup','Hardlopen zone 1 - 5 minuten (inlopen)','cardio','[]','[]','["running", "zone-1", "warm-up", "military"]','["none"]','{"steps": ["Run at a very easy conversational pace for 5 minutes as warm-up"], "cues": ["Zone 1 = very light effort, able to hold a full conversation", "Used specifically as pre-workout warm-up (inlopen)"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-1-5-minuten-warmup');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '556dab9b-101b-5c2e-abfd-03544a130bd2','hardlopen-zone-1-1x5-minuten','Hardlopen zone 1 - 1x5 minuten','cardio','[]','[]','["running", "zone-1", "endurance", "military"]','["none"]','{"steps": ["Run at zone 1 intensity for 5 minutes", "1 set"], "cues": ["Zone 1 = easy/recovery pace, very low heart rate", "Can hold a full conversation"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-1-1x5-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '577806e6-1e71-5b88-892e-49dc113fbf73','hardlopen-zone-1-7-minuten','Hardlopen zone 1 - 7 minuten','cardio','[]','[]','["running", "zone-1", "endurance", "military"]','["none"]','{"steps": ["Run at zone 1 intensity for 7 minutes"], "cues": ["Zone 1 = easy/recovery pace"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-1-7-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '886c63db-e3af-5a6e-8d90-77b0a2d9af59','hardlopen-zone-1-10-minuten','Hardlopen zone 1 - 10 minuten','cardio','[]','[]','["running", "zone-1", "endurance", "military"]','["none"]','{"steps": ["Run at zone 1 intensity for 10 minutes"], "cues": ["Zone 1 = easy/recovery pace, low heart rate"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-1-10-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '29dec8b7-545f-59fe-a3e2-0d32a720ab46','hardlopen-zone-1-2200-meter','Hardlopen zone 1 - 2200 meter','cardio','[]','[]','["running", "zone-1", "endurance", "distance-target", "military"]','["none"]','{"steps": ["Run 2200 meters at zone 1 intensity"], "cues": ["Zone 1 = easy/recovery pace", "Approximately 10–13 minutes at typical zone 1 pace"]}','{"supports": ["distance", "time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-1-2200-meter');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'be523eb2-c0f1-5a4f-9628-c0b966de9b27','hardlopen-zone-1-2700-meter','Hardlopen zone 1 - 2700 meter','cardio','[]','[]','["running", "zone-1", "endurance", "distance-target", "military"]','["none"]','{"steps": ["Run 2700 meters at zone 1 intensity"], "cues": ["Zone 1 = easy/recovery pace", "Approximately 13–16 minutes at typical zone 1 pace"]}','{"supports": ["distance", "time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-1-2700-meter');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'ce265645-2b84-5531-b2b2-2754afde171a','hardlopen-zone-2-6-minuten','Hardlopen zone 2 - 6 minuten','cardio','[]','[]','["running", "zone-2", "military"]','["none"]','{"steps": ["Run at zone 2 intensity for 6 minutes"], "cues": ["Zone 2 = moderate effort, aerobic base pace", "Should be able to speak short sentences"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-6-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '49dbe0ce-6c90-565a-b1be-75b71e195ce9','hardlopen-zone-2-8-minuten','Hardlopen zone 2 - 8 minuten','cardio','[]','[]','["running", "zone-2", "military"]','["none"]','{"steps": ["Run at zone 2 intensity for 8 minutes"], "cues": ["Zone 2 = moderate effort, aerobic base"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-8-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'f2006464-7f95-57a1-bac4-85ef809bca3a','hardlopen-zone-2-10-minuten','Hardlopen zone 2 - 10 minuten','cardio','[]','[]','["running", "zone-2", "military"]','["none"]','{"steps": ["Run at zone 2 intensity for 10 minutes", "Follow with 2 minutes easy recovery (zone 1) if prescribed"], "cues": ["Zone 2 = moderate effort"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-10-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '4a3f1f27-eeb3-55fc-8549-5c3574dc093d','hardlopen-zone-2-12-minuten','Hardlopen zone 2 - 12 minuten','cardio','[]','[]','["running", "zone-2", "military"]','["none"]','{"steps": ["Run at zone 2 intensity for 12 minutes", "Follow with 2 minutes easy recovery (zone 1) if prescribed"], "cues": ["Zone 2 = moderate effort"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-12-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '2161348d-2454-5953-830f-76595fb9a9cd','hardlopen-zone-2-30-minuten','Hardlopen zone 2 - 30 minuten','cardio','[]','[]','["running", "zone-2", "steady-state", "military"]','["none"]','{"steps": ["Run at zone 2 intensity for 30 minutes at a steady pace"], "cues": ["Zone 2 = aerobic base — controlled effort throughout"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-30-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'e51ffb70-c567-5e76-abef-7019537f7791','hardlopen-zone-2-35-minuten','Hardlopen zone 2 - 35 minuten','cardio','[]','[]','["running", "zone-2", "steady-state", "military"]','["none"]','{"steps": ["Run at zone 2 intensity for 35 minutes at a steady pace"], "cues": ["Zone 2 = aerobic base — controlled effort throughout"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-35-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '2bf856e4-e406-589d-bb2c-a391d8a3cf8b','hardlopen-zone-2-40-minuten','Hardlopen zone 2 - 40 minuten','cardio','[]','[]','["running", "zone-2", "steady-state", "long-run", "military"]','["none"]','{"steps": ["Run at zone 2 intensity for 40 minutes at a steady pace"], "cues": ["Zone 2 = aerobic base", "Long-duration effort — nutrition/hydration relevant"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-40-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'ba801165-a68b-5f17-bca8-fd209c17ee7a','hardlopen-zone-2-45-minuten','Hardlopen zone 2 - 45 minuten','cardio','[]','[]','["running", "zone-2", "steady-state", "long-run", "military"]','["none"]','{"steps": ["Run at zone 2 intensity for 45 minutes at a steady pace"], "cues": ["Zone 2 = aerobic base", "Long-duration effort"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-45-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'cfe550a9-9968-5d93-893c-3bbb8e716591','hardlopen-zone-2-50-minuten','Hardlopen zone 2 - 50 minuten','cardio','[]','[]','["running", "zone-2", "steady-state", "long-run", "military"]','["none"]','{"steps": ["Run at zone 2 intensity for 50 minutes at a steady pace"], "cues": ["Zone 2 = aerobic base", "Longest zone-2 steady-state in this programme"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-50-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '74e19a44-c34a-5bbf-b818-6d3628ef010f','hardlopen-zone-2-2x8-minuten','Hardlopen zone 2 - 2x8 minuten','cardio','[]','[]','["running", "zone-2", "intervals", "military"]','["none"]','{"steps": ["Run 8 minutes at zone 2 intensity", "Recover 2 minutes at zone 1", "Repeat for 2 sets total"], "cues": ["Zone 2 = moderate effort", "Zone 1 recovery = easy jogging"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-2x8-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '5c5275e3-c4f7-576e-bc5c-249b1a617cb1','hardlopen-zone-2-2x10-minuten','Hardlopen zone 2 - 2x10 minuten','cardio','[]','[]','["running", "zone-2", "intervals", "military"]','["none"]','{"steps": ["Run 10 minutes at zone 2 intensity", "Recover 2 minutes at zone 1", "Repeat for 2 sets total"], "cues": ["Zone 2 = moderate effort"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-2x10-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '14b7954f-26af-599d-9ba2-e6b56e45a3bf','hardlopen-zone-2-3x2-minuten','Hardlopen zone 2 - 3x2 minuten','cardio','[]','[]','["running", "zone-2", "intervals", "military"]','["none"]','{"steps": ["Run 2 minutes at zone 2 intensity", "Recover 2 minutes at zone 1", "Repeat for 3 sets total"], "cues": ["Short zone-2 repeats", "Zone 2 = moderate effort"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-3x2-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '2600fe06-86f8-5ebe-8d5d-ae992d574ca9','hardlopen-zone-2-5x1-5-minuten','Hardlopen zone 2 - 5x1.5 minuten','cardio','[]','[]','["running", "zone-2", "intervals", "military"]','["none"]','{"steps": ["Run 1.5 minutes at zone 2 intensity", "Recover 1.5 minutes at zone 1", "Repeat for 5 sets total"], "cues": ["Short equal work:rest intervals", "Zone 2 = moderate effort"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-5x1-5-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '674ecd27-0ceb-582e-b98e-8c28a6ce3426','hardlopen-zone-2-2700-meter','Hardlopen zone 2 - 2700 meter','cardio','[]','[]','["running", "zone-2", "intervals", "distance-target", "military"]','["none"]','{"steps": ["2 sets of 8-minute zone 2 running efforts covering 2700 meters total", "2 minutes rest between sets"], "cues": ["Moderate effort", "Pace to cover distance within interval window"]}','{"supports": ["distance", "time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-2-2700-meter');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '07983d47-7b02-53f7-9fd5-8a5d5d47da40','hardlopen-zone-3-2-minuten','Hardlopen zone 3 - 2 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run at zone 3 (threshold) intensity for 2 minutes", "1 minute rest/recovery"], "cues": ["Zone 3 = comfortably hard — speech limited to short phrases"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-2-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '4d0c9e0d-a597-546e-badf-4b5734532958','hardlopen-zone-3-3-minuten','Hardlopen zone 3 - 3 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run at zone 3 intensity for 3 minutes", "2 minutes rest"], "cues": ["Zone 3 = threshold, comfortably hard"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-3-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'ce556d17-e4b7-597f-8d55-036d746addef','hardlopen-zone-3-4-minuten','Hardlopen zone 3 - 4 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run at zone 3 intensity for 4 minutes", "2 minutes rest"], "cues": ["Zone 3 = threshold, comfortably hard"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-4-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '0ea0fa8c-55d5-5d0e-993a-46b4a28186a6','hardlopen-zone-3-8-minuten','Hardlopen zone 3 - 8 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run at zone 3 intensity for 8 minutes", "2 minutes zone 1 recovery"], "cues": ["Zone 3 = threshold, comfortably hard"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-8-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '36a26d13-3a6d-5fdd-9aa1-fed6822b9d27','hardlopen-zone-3-12-minuten','Hardlopen zone 3 - 12 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run at zone 3 intensity for 12 minutes", "2 minutes rest"], "cues": ["Zone 3 = threshold", "Longest single zone-3 effort in this programme"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-12-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '354f6ee6-b46d-53b1-b5d3-c66af9adcdc0','hardlopen-zone-3-1x2-minuten','Hardlopen zone 3 - 1x 2 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run at zone 3 intensity for 2 minutes", "2 minutes zone 1 recovery"], "cues": ["Zone 3 = threshold, comfortably hard"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-1x2-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '0f5bd3d9-2f33-5795-87a2-d99dd6d89dac','hardlopen-zone-3-1x3-minuten','Hardlopen zone 3 - 1x 3 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run at zone 3 intensity for 3 minutes", "2 minutes zone 1 recovery"], "cues": ["Zone 3 = threshold, comfortably hard"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-1x3-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '3822eb9a-870b-5b15-a4a8-a238640c41cb','hardlopen-zone-3-1x4-minuten','Hardlopen zone 3 - 1x 4 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run at zone 3 intensity for 4 minutes", "2 minutes zone 1 recovery"], "cues": ["Zone 3 = threshold"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-1x4-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '850b4f8a-63f6-5b9c-bd2a-c22129a11bdc','hardlopen-zone-3-2x3-minuten','Hardlopen zone 3 - 2x3 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run 3 minutes at zone 3 intensity", "2 minutes zone 1 recovery", "Repeat for 2 sets total"], "cues": ["Zone 3 = threshold"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-2x3-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '34ea3485-c217-5447-8386-02755f76fa90','hardlopen-zone-3-2x5-minuten','Hardlopen zone 3 - 2x 5 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run 5 minutes at zone 3 intensity", "2 minutes zone 1 recovery", "Repeat for 2 sets total"], "cues": ["Zone 3 = threshold"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-2x5-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '821089c1-a95d-5d9c-9ced-92dbf65da41f','hardlopen-zone-3-2x6-minuten','Hardlopen zone 3 - 2x 6 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run 6 minutes at zone 3 intensity", "2 minutes zone 1 recovery", "Repeat for 2 sets total"], "cues": ["Zone 3 = threshold"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-2x6-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '3ce72d26-7359-582b-9af5-adc6dd8c7248','hardlopen-zone-3-3x1-minuut','Hardlopen zone 3 - 3x1 minuut','cardio','[]','[]','["running", "zone-3", "threshold", "repeats", "military"]','["none"]','{"steps": ["Run 1 minute at zone 3 intensity", "1 minute zone 1 recovery", "Repeat for 3 sets total"], "cues": ["Short hard repeats", "Zone 3 = threshold"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-3x1-minuut');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '91acb0d9-192a-50d1-8e1d-faaecac60b14','hardlopen-zone-3-3x2-minuten','Hardlopen zone 3 - 3x2 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run 2 minutes at zone 3 intensity", "2 minutes zone 1 recovery", "Repeat for 3 sets total"], "cues": ["Zone 3 = threshold"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-3x2-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '84870bfc-2713-58e9-b285-9f1efce192b1','hardlopen-zone-3-3x3-minuten','Hardlopen zone 3 - 3x3 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run 3 minutes at zone 3 intensity", "2 minutes zone 1 recovery", "Repeat for 3 sets total"], "cues": ["Zone 3 = threshold"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-3x3-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '14d59027-ca54-5921-bb84-6cedb0135e79','hardlopen-zone-3-3x6-minuten','Hardlopen zone 3 - 3x 6 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run 6 minutes at zone 3 intensity", "2 minutes zone 1 recovery", "Repeat for 3 sets total"], "cues": ["Zone 3 = threshold", "Longer threshold effort"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-3x6-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '48f95e13-bcd0-500a-9112-1dce6b007825','hardlopen-zone-3-3x8-minuten','Hardlopen zone 3 - 3x 8 minuten','cardio','[]','[]','["running", "zone-3", "threshold", "military"]','["none"]','{"steps": ["Run 8 minutes at zone 3 intensity", "2 minutes zone 1 recovery", "Repeat for 3 sets total"], "cues": ["Zone 3 = threshold", "Demanding long threshold work"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-3x8-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '070724eb-4196-5a8d-819d-0d6afc853e1e','hardlopen-zone-3-2700-meter','Hardlopen zone 3 - 2700 meter','cardio','[]','[]','["running", "zone-3", "threshold", "distance-target", "military"]','["none"]','{"steps": ["3 sets of 2-minute zone 3 efforts covering 2700 meters total", "2 minutes rest between sets"], "cues": ["Zone 3 = threshold", "Pace to cover distance target"]}','{"supports": ["distance", "time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-3-2700-meter');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '5584c7ed-f268-50e9-a99d-899a45c3e7cb','hardlopen-zone-4-3x2-minuten','Hardlopen zone 4 - 3x2 minuten','cardio','[]','[]','["running", "zone-4", "vo2max", "intervals", "military"]','["none"]','{"steps": ["Run 2 minutes at zone 4 (VO2max) intensity", "2 minutes zone 1 recovery", "Repeat for 3 sets total"], "cues": ["Zone 4 = very hard, near maximal effort", "2 min rest is critical — do not cut short"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-4-3x2-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '4b153b2d-7046-52a9-b9e9-7064d90f84fd','hardlopen-zone-4-4x1-minuut','Hardlopen zone 4 - 4x1 minuut','cardio','[]','[]','["running", "zone-4", "vo2max", "repeats", "military"]','["none"]','{"steps": ["Run 1 minute at zone 4 (VO2max) intensity", "1 minute zone 1 recovery", "Repeat for 4 sets total"], "cues": ["Zone 4 = very hard, near maximal", "Short hard repeats"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-4-4x1-minuut');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'b768cc3e-55a9-59a7-a256-e97521cd6ac5','hardlopen-zone-4-4x45-seconden','Hardlopen zone 4 - 4x45 seconden','cardio','[]','[]','["running", "zone-4", "vo2max", "repeats", "military"]','["none"]','{"steps": ["Run 45 seconds at zone 4 (VO2max) intensity", "45 seconds rest", "Repeat for 4 sets total"], "cues": ["Zone 4 = very hard, near maximal", "Short equal work:rest ratio"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-4-4x45-seconden');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'b80ef622-73d7-5aef-b16d-596c918aee33','hardlopen-zone-4-5x1-minuut','Hardlopen zone 4 - 5x1 minuut','cardio','[]','[]','["running", "zone-4", "vo2max", "repeats", "military"]','["none"]','{"steps": ["Run 1 minute at zone 4 (VO2max) intensity", "1 minute zone 1 recovery", "Repeat for 5 sets total"], "cues": ["Zone 4 = very hard, near maximal"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-4-5x1-minuut');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '9cd1f7a1-ee8e-58a2-8f33-772de8ec64dd','hardlopen-zone-4-6x1-minuten','Hardlopen zone 4 - 6x 1 minuten','cardio','[]','[]','["running", "zone-4", "vo2max", "repeats", "military"]','["none"]','{"steps": ["Run 1 minute at zone 4 (VO2max) intensity", "1 minute zone 1 recovery", "Repeat for 6 sets total"], "cues": ["Zone 4 = very hard, near maximal", "High volume of zone-4 work — requires good base fitness"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-4-6x1-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '1f4deb67-ffff-5b3d-9820-fd10a8c995e2','hardlopen-zone-4-2700-meter','Hardlopen zone 4 - 2700 meter','cardio','[]','[]','["running", "zone-4", "vo2max", "intervals", "distance-target", "military"]','["none"]','{"steps": ["4 sets of 1-minute zone 4 efforts", "1 minute rest between sets", "Total distance target: 2700 meters"], "cues": ["Zone 4 = VO2max effort, very hard", "Pace appropriately for distance target"]}','{"supports": ["distance", "time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-4-2700-meter');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'f41ae049-e869-5765-ac96-c99be7e93df8','hardlopen-zone-5-4x30-seconden','Hardlopen zone 5 - 4x30 seconden','cardio','[]','[]','["running", "zone-5", "max-effort", "repeats", "high_impact", "military"]','["none"]','{"steps": ["Sprint at maximum effort for 30 seconds", "30 seconds complete rest", "Repeat for 4 sets total"], "cues": ["Zone 5 = maximal sprint effort", "Full recovery between efforts is essential"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-5-4x30-seconden');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'c5950b20-8666-5837-9756-bf2c2125fa89','hardlopen-zone-5-6x30-seconden','Hardlopen zone 5 - 6x30 seconden','cardio','[]','[]','["running", "zone-5", "max-effort", "repeats", "high_impact", "military"]','["none"]','{"steps": ["Sprint at maximum effort for 30 seconds", "Rest (zone 1 or full rest) for 30 seconds or 2 minutes as prescribed", "Repeat for 6 sets total"], "cues": ["Zone 5 = maximal sprint", "Source prescribes either 30 s or 2 min rest — confirm per session plan"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-5-6x30-seconden');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '6e9f1202-6167-5cba-9baa-0fe75a57f8e5','hardlopen-zone-5-6x45-seconden','Hardlopen zone 5 - 6x45 seconden','cardio','[]','[]','["running", "zone-5", "max-effort", "repeats", "high_impact", "military"]','["none"]','{"steps": ["Sprint at maximum effort for 45 seconds", "45 seconds rest", "Repeat for 6 sets total"], "cues": ["Zone 5 = maximal effort"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-5-6x45-seconden');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '01fe0b19-cb6e-5ded-837d-2f7bc94e3fbf','hardlopen-zone-5-2700-meter','Hardlopen zone 5 - 2700 meter','cardio','[]','[]','["running", "zone-5", "max-effort", "intervals", "distance-target", "high_impact", "military"]','["none"]','{"steps": ["6 sets of 30-second zone 5 (maximal) sprint efforts", "30 seconds rest between sets", "Total distance target: 2700 meters"], "cues": ["Zone 5 = maximal sprint", "Demanding high-speed session — only for trained individuals"]}','{"supports": ["distance", "time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='hardlopen-zone-5-2700-meter');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'e4deae06-9330-50b1-af7c-7a16ec188d99','marsen-5-5-km-u-25-minuten','Marsen (5,5 km/u) - 25 minuten','cardio','[]','[]','["walking", "march", "steady-state", "military"]','["none"]','{"steps": ["March at 5.5 km/h for 25 minutes maintaining steady pace"], "cues": ["Controlled cadence", "No pack weight for this variant"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-5-5-km-u-25-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '755bd6bc-ce2d-588a-bcec-74dba250f813','marsen-5-5-km-u-10-minuten-rugzak-35kg','Marsen (5,5 km/u) - 10 minuten (rugzak 35 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 5.5 km/h for 10 minutes carrying a 35 kg rucksack"], "cues": ["Steady pace", "Maintain posture under heavy load"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-5-5-km-u-10-minuten-rugzak-35kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'bc38345e-70a5-5677-a963-52f079ddcc96','marsen-5-5-km-u-2x10-minuten-rugzak-25kg','Marsen (5,5 km/u) - 2x10 minuten (rugzak 25 kg)','cardio','[]','[]','["walking", "march", "weighted", "intervals", "military"]','["rucksack"]','{"steps": ["March at 5.5 km/h for 10 minutes with 25 kg rucksack", "2 minutes rest", "Repeat for 2 sets total"], "cues": ["Steady pace under load", "25 kg pack"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-5-5-km-u-2x10-minuten-rugzak-25kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '7289cb0e-1d14-597d-93a0-cba4f7f97a49','marsen-5-5-km-u-20-minuten-rugzak-25kg','Marsen (5,5 km/u) - 20 minuten (rugzak 25 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 5.5 km/h for 20 minutes with 25 kg rucksack"], "cues": ["Steady pace under load"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-5-5-km-u-20-minuten-rugzak-25kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'dda0483d-0550-5a13-99e9-542be5467d39','marsen-5-5-km-u-20-minuten-rugzak-35kg','Marsen (5,5 km/u) - 20 minuten (rugzak 35 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 5.5 km/h for 20 minutes with 35 kg rucksack"], "cues": ["Steady pace under heavy load"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-5-5-km-u-20-minuten-rugzak-35kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '2cd7eebe-f26f-5ac8-86a1-82ac5345690a','marsen-5-5-km-u-25-minuten-rugzak-25kg','Marsen (5,5 km/u) - 25 minuten (rugzak 25 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 5.5 km/h for 25 minutes with 25 kg rucksack"], "cues": ["Steady pace under load"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-5-5-km-u-25-minuten-rugzak-25kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '29ab883b-bbc0-5730-94e1-11c3a3cb921e','marsen-5-5-km-u-30-minuten-rugzak-25kg','Marsen (5,5 km/u) - 30 minuten (rugzak 25 kg)','cardio','[]','[]','["walking", "march", "weighted", "long-duration", "military"]','["rucksack"]','{"steps": ["March at 5.5 km/h for 30 minutes with 25 kg rucksack"], "cues": ["Steady pace under load", "Longest variant at this speed — nutrition/hydration may be relevant"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-5-5-km-u-30-minuten-rugzak-25kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '69b691b5-0391-5371-99ad-52737ad6d8ea','marsen-5-5-km-u-5-minuten-rugzak-35kg','Marsen (5,5 km/u) - 5 minuten (rugzak 35 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 5.5 km/h for 5 minutes with 35 kg rucksack"], "cues": ["Short loaded march — typically used as part of an interval block"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-5-5-km-u-5-minuten-rugzak-35kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '0d740255-de5a-504c-a5ee-800d0fe4ce16','marsen-5-5-km-u-3x5-minuten-rugzak-35kg','Marsen (5,5 km/u) - 3x5 minuten (rugzak 35 kg)','cardio','[]','[]','["walking", "march", "weighted", "intervals", "military"]','["rucksack"]','{"steps": ["March at 5.5 km/h for 5 minutes with 35 kg rucksack", "2 minutes rest", "Repeat for 3 sets total"], "cues": ["Heavy loaded interval march", "35 kg pack"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-5-5-km-u-3x5-minuten-rugzak-35kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '2c4db897-559e-59a4-8315-3798dcb37073','marsen-6-km-u-30-minuten','Marsen (6 km/u) - 30 minuten','cardio','[]','[]','["walking", "march", "steady-state", "military"]','["none"]','{"steps": ["March at 6 km/h for 30 minutes"], "cues": ["Steady pace", "No pack for this variant"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-30-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '12ba2f1c-0f20-525a-aad1-d8e956b681b7','marsen-6-km-u-2x10-minuten-rugzak-25kg','Marsen (6 km/u) - 2x10 minuten (rugzak 25 kg)','cardio','[]','[]','["walking", "march", "weighted", "intervals", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 10 minutes with 25 kg rucksack", "2 minutes rest", "Repeat for 2 sets total"], "cues": ["Steady pace under load"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-2x10-minuten-rugzak-25kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '19a64cc2-365e-5503-b90d-08ef3fab5feb','marsen-6-km-u-20-minuten-rugzak-25kg','Marsen (6 km/u) - 20 minuten (rugzak 25 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 20 minutes with 25 kg rucksack"], "cues": ["Steady pace under load"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-20-minuten-rugzak-25kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '87a5ffa7-7e69-5c61-98a7-a29d95c673c1','marsen-6-km-u-20-minuten-rugzak-35kg','Marsen (6 km/u) - 20 minuten (rugzak 35 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 20 minutes with 35 kg rucksack"], "cues": ["Steady pace under heavier load"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-20-minuten-rugzak-35kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '85950047-f22f-5179-9c49-23f06c3d050a','marsen-6-km-u-2x8-minuten-rugzak-35kg','Marsen (6 km/u) - 2x8 minuten (rugzak 35 kg)','cardio','[]','[]','["walking", "march", "weighted", "intervals", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 8 minutes with 35 kg rucksack", "2 minutes rest", "Repeat for 2 sets total"], "cues": ["Heavy loaded interval march", "35 kg pack"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-2x8-minuten-rugzak-35kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '165b4008-cbf8-59bc-9e1d-a736ad7c235c','marsen-6-km-u-8-minuten-rugzak-45kg','Marsen (6 km/u) - 8 minuten (rugzak 45 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 8 minutes with 45 kg rucksack"], "cues": ["Very heavy loaded march — caution with posture and lower back", "45 kg pack"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-8-minuten-rugzak-45kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'f65b10e1-ba17-5744-b390-a8c5cffb24e1','marsen-6-km-u-20-minuten-rugzak-10kg','Marsen (6 km/u) - 20 minuten (rugzak 10 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 20 minutes with 10 kg rucksack"], "cues": ["Light pack — introductory loaded march", "10 kg pack"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-20-minuten-rugzak-10kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'e117b10f-e34e-50ed-ac52-4170f52efec2','marsen-6-km-u-40-minuten','Marsen (6 km/u) - 40 minuten','cardio','[]','[]','["walking", "march", "steady-state", "long-duration", "military"]','["none"]','{"steps": ["March at 6 km/h for 40 minutes"], "cues": ["Steady pace", "Long-duration march — longest no-load variant at this speed"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-40-minuten');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '47797a9c-1ab4-5d83-bedf-33cd1e0b7364','marsen-6-km-u-25-minuten-rugzak-10kg','Marsen (6 km/u) - 25 minuten (rugzak 10 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 25 minutes with 10 kg rucksack"], "cues": ["Light pack", "10 kg pack"]}','{"supports": ["time"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-25-minuten-rugzak-10kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'ce06a9bf-52d7-5fbf-8d79-2b4f42293747','marsen-6-km-u-4x5-minuten-rugzak-10kg','Marsen (6 km/u) - 4x5 minuten (rugzak 10 kg)','cardio','[]','[]','["walking", "march", "weighted", "intervals", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 5 minutes with 10 kg rucksack", "2 minutes rest", "Repeat for 4 sets total"], "cues": ["Light loaded interval march", "10 kg pack"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-4x5-minuten-rugzak-10kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT 'a33b7483-442e-5216-89f1-e77ec86b2111','marsen-6-km-u-2x10-minuten-rugzak-35kg','Marsen (6 km/u) - 2x10 minuten (rugzak 35 kg)','cardio','[]','[]','["walking", "march", "weighted", "intervals", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 10 minutes with 35 kg rucksack", "2 minutes rest", "Repeat for 2 sets total"], "cues": ["Heavy loaded interval march", "35 kg pack"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-2x10-minuten-rugzak-35kg');
INSERT INTO exercises (id,slug,name,category,primary_muscles_json,secondary_muscles_json,tags_json,equipment_required_json,instructions_json,metrics_json,is_active,created_at_ms,updated_at_ms)
SELECT '000db6e8-e910-5318-9006-37d109f3ee45','marsen-6-km-u-6-minuten-rugzak-45kg','Marsen (6 km/u) - 6 minuten (rugzak 45 kg)','cardio','[]','[]','["walking", "march", "weighted", "military"]','["rucksack"]','{"steps": ["March at 6 km/h for 6 minutes with 45 kg rucksack", "2 minutes rest"], "cues": ["Maximum loaded march — 45 kg pack", "Monitor posture carefully under this load"]}','{"supports": ["time", "sets"]}',1,1746230400000,1746230400000
WHERE NOT EXISTS (SELECT 1 FROM exercises WHERE slug='marsen-6-km-u-6-minuten-rugzak-45kg');