-- Migration 0102: Batch 1 of the exercise-library enrichment — PULL
--
-- Roadmap X-35 / X-38. The `pull` axis is one of six the planner biases toward
-- (R551) and the radar displays, but the library held exactly one genuine
-- bodyweight pulling movement (`inverted-row-table`), and `pull_up_bar` — an
-- onboarding option — had five exercises. A user whose weakest axis was pull got
-- biased toward work that did not exist, so the axis never moved. It is also why
-- the fitness assessment renders pull as "not measured".
--
-- 14 exercises: 7 need nothing or a band (so the axis becomes trainable for
-- everyone), 3 use a pull-up bar, 4 use gym machines. Four more were drafted and
-- dropped — band-pull-apart, band-face-pull, chin-up and dead-hang already exist. Machine equipment is also
-- selectable in ALL_EQUIPMENT, so a home owner unlocks them without gym_today.
--
-- Every row carries its loads_* injury tags — R563 filters on them, and a row
-- without them silently bypasses the safety filter.

INSERT INTO exercises
  (id, slug, name, category, primary_muscles_json, secondary_muscles_json,
   tags_json, equipment_required_json, instructions_json, metrics_json,
   is_active, visibility, created_at_ms, updated_at_ms)
VALUES
('ex_pull_band_pulldown','band-lat-pulldown','Band Lat Pulldown','strength','["lats", "upper_back"]','["biceps", "rear_delts"]','["strength", "pull", "upper_body", "resistance_bands", "no_floor", "quiet", "low_impact", "loads_shoulder"]','["resistance_bands"]','{"steps": ["Anchor a band above head height \u2014 a door anchor or closed door hinge works.", "Kneel or sit tall, arms overhead, holding one end in each hand.", "Pull your elbows down and back until your hands reach chest height.", "Control the band all the way back up."], "cues": ["Lead with the elbows, not the hands", "Squeeze your shoulder blades down and together", "\ud83d\udca1 If the band snaps back fast, step closer to the anchor"]}','{"supports": ["reps", "sets", "tempo"]}',1,'global',1789300000000,1789300000000),
('ex_pull_band_row','band-bent-over-row','Band Bent-Over Row','strength','["lats", "upper_back", "rhomboids"]','["biceps", "core"]','["strength", "pull", "upper_body", "resistance_bands", "no_floor", "quiet", "low_impact", "loads_lower_back"]','["resistance_bands"]','{"steps": ["Stand on the middle of the band, feet hip-width.", "Hinge forward about 45\u00b0 with a flat back, band ends in each hand.", "Row both hands to your lower ribs.", "Lower under control until your arms are straight."], "cues": ["Keep your back flat \u2014 hinge from the hips, not the spine", "Elbows brush past your sides", "\ud83d\udca1 Stand wider on the band for more resistance"]}','{"supports": ["reps", "sets", "tempo"]}',1,'global',1789300000000,1789300000000),
('ex_pull_band_seated_row','band-seated-row','Band Seated Row','strength','["upper_back", "rhomboids", "lats"]','["biceps"]','["strength", "pull", "upper_body", "resistance_bands", "floor", "quiet", "low_impact"]','["resistance_bands"]','{"steps": ["Sit on the floor, legs straight, band looped around both feet.", "Sit tall with a long spine, holding one end in each hand.", "Pull your hands to your waist, elbows close to your body.", "Straighten the arms slowly."], "cues": ["Chest up throughout", "Do not lean back to move the band", "\ud83d\udca1 Bend the knees slightly if your hamstrings are tight"]}','{"supports": ["reps", "sets", "tempo"]}',1,'global',1789300000000,1789300000000),
('ex_pull_band_single_row','band-single-arm-row','Band Single-Arm Row','strength','["lats", "upper_back"]','["biceps", "core"]','["strength", "pull", "upper_body", "resistance_bands", "no_floor", "quiet", "low_impact", "unilateral"]','["resistance_bands"]','{"steps": ["Anchor a band at waist height, or stand on one end.", "Stand side-on, holding the band in one hand, arm extended.", "Row the hand to your ribs, keeping your torso still.", "Repeat, then change sides."], "cues": ["Do not rotate your torso to help the pull", "Even reps both sides", "\ud83d\udca1 Catches the side-to-side difference a two-arm row hides"]}','{"supports": ["reps", "sets"]}',1,'global',1789300000000,1789300000000),
('ex_pull_door_iso','doorway-isometric-row','Doorway Isometric Row','strength','["lats", "upper_back", "rhomboids"]','["biceps"]','["strength", "pull", "upper_body", "bodyweight", "no_floor", "quiet", "low_impact", "isometric"]','["none"]','{"steps": ["Stand facing a door frame, feet either side of it.", "Grip both sides at chest height, arms straight, lean back.", "Pull yourself towards the frame and hold, squeezing the shoulder blades.", "Hold, then release slowly."], "cues": ["Body stays in a straight line from heel to head", "Breathe through the hold", "\ud83d\udca1 The simplest way to train pulling with nothing at all"]}','{"supports": ["time", "sets"]}',1,'global',1789300000000,1789300000000),
('ex_pull_towel_row','towel-door-row','Towel Row (Door)','strength','["lats", "upper_back", "rhomboids"]','["biceps", "core"]','["strength", "pull", "upper_body", "bodyweight", "no_floor", "low_impact"]','["none"]','{"steps": ["Loop a towel around a secure door handle on a closed, latched door.", "Hold one end in each hand and walk your feet towards the door, leaning back.", "Pull your chest towards the handle.", "Lower under control."], "cues": ["Test the door holds your weight first", "The further your feet, the harder it gets", "\ud83d\udca1 Keep the hips in line \u2014 do not let them sag"]}','{"supports": ["reps", "sets"]}',1,'global',1789300000000,1789300000000),
('ex_pull_inverted_elev','inverted-row-feet-elevated','Inverted Row (Feet Elevated)','strength','["lats", "rhomboids", "upper_back"]','["biceps", "core"]','["strength", "pull", "upper_body", "bodyweight", "floor", "low_impact"]','["none"]','{"steps": ["Set up under a sturdy table as for an inverted row, with your feet on a chair.", "Grip the edge, body straight from heels to head.", "Pull your chest to the edge.", "Lower slowly."], "cues": ["Harder than the floor version \u2014 progress here once table rows feel easy", "Squeeze the shoulder blades at the top", "\ud83d\udca1 Stop the set when your hips start to drop"]}','{"supports": ["reps", "sets"]}',1,'global',1789300000000,1789300000000),
('ex_pull_scap','scapular-pull-up','Scapular Pull-Up','strength','["lats", "upper_back", "rhomboids"]','["traps"]','["strength", "pull", "upper_body", "pull_up_bar", "no_floor", "low_impact", "loads_shoulder"]','["pull_up_bar"]','{"steps": ["Hang from the bar with straight arms.", "Without bending your elbows, pull your shoulder blades down and together so your body rises slightly.", "Lower back to a full hang."], "cues": ["The elbows stay straight the whole time", "Small movement \u2014 a few centimetres is right", "\ud83d\udca1 This is the missing step between a hang and a pull-up"]}','{"supports": ["reps", "sets"]}',1,'global',1789300000000,1789300000000),
('ex_pull_negative','negative-pull-up','Negative Pull-Up','strength','["lats", "upper_back", "biceps"]','["core", "forearms"]','["strength", "pull", "upper_body", "pull_up_bar", "no_floor", "low_impact", "loads_shoulder"]','["pull_up_bar"]','{"steps": ["Use a chair to get your chin above the bar.", "Take your feet off and lower yourself as slowly as you can.", "Step back up and repeat."], "cues": ["Aim for a 3-5 second descent", "Stop the set when you can no longer control the lowering", "\ud83d\udca1 The fastest honest route to a first pull-up"]}','{"supports": ["reps", "sets"]}',1,'global',1789300000000,1789300000000),
('ex_pull_assisted_band','assisted-pull-up-band','Band-Assisted Pull-Up','strength','["lats", "upper_back", "biceps"]','["core", "forearms"]','["strength", "pull", "upper_body", "pull_up_bar", "resistance_bands", "no_floor", "low_impact", "loads_shoulder"]','["pull_up_bar", "resistance_bands"]','{"steps": ["Loop a band over the bar and put one knee or foot in the loop.", "Grip the bar shoulder-width.", "Pull until your chin clears the bar.", "Lower under control."], "cues": ["A thicker band gives more help \u2014 drop down as you get stronger", "Chest to the bar, not chin craned over it", "\ud83d\udca1 Keep the ribs down so it does not become a swing"]}','{"supports": ["reps", "sets"]}',1,'global',1789300000000,1789300000000),
('ex_pull_lat_pulldown','lat-pulldown','Lat Pulldown','strength','["lats", "upper_back"]','["biceps", "rear_delts"]','["strength", "pull", "upper_body", "machine", "gym", "no_floor", "low_impact", "loads_shoulder"]','["lat_pulldown"]','{"steps": ["Set the thigh pad so your legs are held down.", "Grip the bar wider than shoulder-width, palms away.", "Pull the bar to your upper chest, leaning back very slightly.", "Let it rise slowly until your arms are straight."], "cues": ["Lead with the elbows", "Do not pull behind your neck", "\ud83d\udca1 The most scalable pull there is \u2014 start light and add weight weekly"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789300000000,1789300000000),
('ex_pull_seated_cable_row','seated-cable-row','Seated Cable Row','strength','["upper_back", "rhomboids", "lats"]','["biceps", "rear_delts"]','["strength", "pull", "upper_body", "machine", "gym", "no_floor", "low_impact", "loads_lower_back"]','["seated_row_machine"]','{"steps": ["Sit with your feet on the platform and knees slightly bent.", "Take the handle with a long spine and chest up.", "Pull to your waist, elbows close to your sides.", "Return slowly without letting your back round."], "cues": ["Move the weight with your back, not by rocking", "Pause for a beat at the squeeze", "\ud83d\udca1 If your lower back rounds, drop the weight"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789300000000,1789300000000),
('ex_pull_assisted_machine','assisted-pull-up-machine','Assisted Pull-Up (Machine)','strength','["lats", "upper_back", "biceps"]','["core"]','["strength", "pull", "upper_body", "machine", "gym", "no_floor", "low_impact", "loads_shoulder"]','["machine"]','{"steps": ["Set the assistance weight \u2014 more weight means more help.", "Kneel or stand on the pad and grip the handles.", "Pull until your chin clears the bar.", "Lower under control."], "cues": ["Reduce the assistance as you get stronger", "Full range every rep", "\ud83d\udca1 Lets you train the real movement long before an unassisted rep"]}','{"supports": ["weight", "reps", "sets"]}',1,'global',1789300000000,1789300000000),
('ex_pull_straight_arm','straight-arm-pulldown','Straight-Arm Pulldown','strength','["lats"]','["core", "rear_delts"]','["strength", "pull", "upper_body", "machine", "gym", "no_floor", "low_impact", "loads_shoulder"]','["cable"]','{"steps": ["Stand facing a high cable, bar or rope in both hands.", "Keep your arms straight and hinge very slightly at the hips.", "Sweep the bar down to your thighs.", "Return slowly overhead."], "cues": ["The elbows stay straight \u2014 this is not a triceps pushdown", "Feel it along the side of your back", "\ud83d\udca1 Good for learning to feel the lats before heavier pulling"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789300000000,1789300000000);
