-- Migration 0103: Batch 2 of the exercise-library enrichment — BARBELL / RACK
--
-- Roadmap X-38. `barbell` had exactly one exercise, so a strength-goal user who
-- ticked "at the gym" was still served bodyweight work. These are the compound
-- lifts a gym session is actually built around.
--
-- Equipment uses the canonical vocabulary (barbell, squat_rack, bench,
-- bench_press_rack, weight_plates, ez_bar), all of which are selectable in
-- ALL_EQUIPMENT, so a home rack owner unlocks them without gym_today.
--
-- Every row carries loads_* injury tags (R563) and safety cues: these are the
-- movements where a bad rep costs the most.

INSERT INTO exercises
  (id, slug, name, category, primary_muscles_json, secondary_muscles_json,
   tags_json, equipment_required_json, instructions_json, metrics_json,
   is_active, visibility, created_at_ms, updated_at_ms)
VALUES
('ex_bb_back_squat','barbell-back-squat','Barbell Back Squat','strength','["quads", "glutes"]','["hamstrings", "core", "lower_back"]','["strength", "legs", "barbell", "gym", "no_floor", "loads_knee", "loads_lower_back"]','["barbell", "squat_rack"]','{"steps": ["Set the bar at upper-chest height in the rack. Step under it, bar resting across your upper back \u2014 not your neck.", "Brace, stand it up, step back two steps.", "Sit down and back until your thighs reach parallel.", "Drive through the whole foot to stand."], "cues": ["Knees track over the toes", "Chest stays proud out of the hole", "\ud83d\udca1 Always use the safety pins \u2014 set them just below your bottom position"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000),
('ex_bb_front_squat','barbell-front-squat','Barbell Front Squat','strength','["quads"]','["glutes", "core", "upper_back"]','["strength", "legs", "barbell", "gym", "no_floor", "loads_knee"]','["barbell", "squat_rack"]','{"steps": ["Rest the bar across the front of your shoulders, elbows high.", "Stand it up and step back.", "Squat down with an upright torso until your thighs reach parallel.", "Stand, keeping the elbows up throughout."], "cues": ["Elbows drop, bar drops \u2014 keep them high", "More upright than a back squat", "\ud83d\udca1 Easier on the lower back than a back squat at the same effort"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000),
('ex_bb_bench','barbell-bench-press','Barbell Bench Press','strength','["chest"]','["triceps", "front_delts"]','["strength", "push", "upper_body", "barbell", "gym", "no_floor", "loads_shoulder"]','["barbell", "bench_press_rack", "bench"]','{"steps": ["Lie on the bench, eyes under the bar, feet flat on the floor.", "Grip slightly wider than shoulder-width and unrack.", "Lower to your mid-chest, elbows about 45\u00b0 from your body.", "Press back up."], "cues": ["Shoulder blades pinched into the bench the whole set", "Wrists stacked over the elbows", "\ud83d\udca1 Never bench heavy alone without safety arms or a spotter"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000),
('ex_bb_ohp','barbell-overhead-press','Barbell Overhead Press','strength','["shoulders"]','["triceps", "core", "upper_back"]','["strength", "push", "upper_body", "barbell", "gym", "no_floor", "loads_shoulder", "loads_lower_back"]','["barbell", "squat_rack"]','{"steps": ["Take the bar at collarbone height, hands just outside the shoulders.", "Squeeze your glutes and brace so you do not lean back.", "Press overhead, moving your head back slightly to let the bar pass.", "Lower under control to the collarbone."], "cues": ["Finish with the bar over the middle of your foot", "Ribs down \u2014 do not arch the lower back", "\ud83d\udca1 If you have to lean back to finish, it is too heavy"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000),
('ex_bb_deadlift','barbell-deadlift','Barbell Deadlift','strength','["hamstrings", "glutes", "lower_back"]','["lats", "traps", "core"]','["strength", "hinge", "barbell", "gym", "floor", "loads_lower_back", "loads_knee"]','["barbell", "weight_plates"]','{"steps": ["Stand with the bar over your mid-foot, feet hip-width.", "Hinge and grip just outside your legs; drop the hips until your shins touch the bar.", "Take the slack out, brace, and stand by pushing the floor away.", "Lower by hinging back, keeping the bar close."], "cues": ["Flat back from first pull to lockout", "The bar stays in contact with your legs", "\ud83d\udca1 Stop the set the moment your back rounds \u2014 this is not a lift to grind"]}','{"supports": ["weight", "reps", "sets"]}',1,'global',1789301000000,1789301000000),
('ex_bb_rdl','barbell-romanian-deadlift','Barbell Romanian Deadlift','strength','["hamstrings", "glutes"]','["lower_back", "core"]','["strength", "hinge", "barbell", "gym", "no_floor", "loads_lower_back"]','["barbell"]','{"steps": ["Stand tall holding the bar at your thighs, knees softly bent.", "Push your hips back, letting the bar slide down your legs.", "Stop when you feel a strong hamstring stretch \u2014 usually mid-shin.", "Drive the hips forward to stand."], "cues": ["The knees barely move \u2014 this is a hip movement", "Bar stays against the legs", "\ud83d\udca1 Range is set by your hamstrings, not by touching the floor"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000),
('ex_bb_row','barbell-bent-over-row','Barbell Bent-Over Row','strength','["lats", "upper_back", "rhomboids"]','["biceps", "lower_back"]','["strength", "pull", "upper_body", "barbell", "gym", "no_floor", "loads_lower_back"]','["barbell"]','{"steps": ["Hold the bar with an overhand grip, hands shoulder-width.", "Hinge to roughly 45\u00b0, flat back, bar hanging at your shins.", "Row to your lower ribs.", "Lower under control without letting the back round."], "cues": ["Torso angle stays fixed \u2014 do not row by standing up", "Elbows drive back, not out", "\ud83d\udca1 Lighter than you think; form breaks fast on this one"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000),
('ex_bb_hip_thrust','barbell-hip-thrust','Barbell Hip Thrust','strength','["glutes"]','["hamstrings", "core"]','["strength", "hinge", "barbell", "gym", "floor", "loads_lower_back"]','["barbell", "bench", "weight_plates"]','{"steps": ["Sit on the floor with your upper back against a bench, bar across your hips on a pad.", "Feet flat, shins vertical at the top.", "Drive through your heels until your hips are level with your knees.", "Lower under control."], "cues": ["Tuck the chin and keep the ribs down", "Squeeze the glutes hard at the top for a beat", "\ud83d\udca1 Shins vertical at lockout \u2014 walk the feet in or out until they are"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000),
('ex_bb_lunge','barbell-reverse-lunge','Barbell Reverse Lunge','strength','["quads", "glutes"]','["hamstrings", "core"]','["strength", "legs", "barbell", "gym", "no_floor", "unilateral", "loads_knee"]','["barbell", "squat_rack"]','{"steps": ["Bar on your upper back as for a squat.", "Step one foot back and lower until the back knee is just off the floor.", "Drive through the front heel to stand.", "Alternate legs."], "cues": ["Front shin close to vertical", "Step back far enough that the front knee does not shoot forward", "\ud83d\udca1 Kinder to the knees than a forward lunge"]}','{"supports": ["weight", "reps", "sets"]}',1,'global',1789301000000,1789301000000),
('ex_ez_curl','ez-bar-biceps-curl','EZ-Bar Biceps Curl','strength','["biceps"]','["forearms"]','["strength", "pull", "upper_body", "barbell", "gym", "no_floor", "quiet"]','["ez_bar"]','{"steps": ["Hold the EZ bar at the angled grips, arms straight.", "Curl to shoulder height, keeping the elbows pinned to your sides.", "Lower slowly to full extension."], "cues": ["The elbows do not travel forward", "Full extension at the bottom each rep", "\ud83d\udca1 The angled grip is easier on the wrists than a straight bar"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000),
('ex_bb_calf','barbell-calf-raise','Barbell Calf Raise','strength','["calves"]','[]','["strength", "legs", "barbell", "gym", "no_floor", "loads_ankle"]','["barbell", "squat_rack"]','{"steps": ["Bar on your upper back, standing tall \u2014 on a step if you have one.", "Rise onto the balls of your feet as high as you can.", "Pause at the top.", "Lower slowly until you feel a stretch."], "cues": ["Slow on the way down \u2014 that is where the work is", "Do not bounce", "\ud83d\udca1 Calf capacity is the main protector against running injuries"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000),
('ex_bb_good_morning','barbell-good-morning','Barbell Good Morning','strength','["hamstrings", "lower_back"]','["glutes", "core"]','["strength", "hinge", "barbell", "gym", "no_floor", "loads_lower_back"]','["barbell", "squat_rack"]','{"steps": ["Bar on your upper back, feet hip-width, knees softly bent.", "Hinge forward at the hips with a flat back until your torso is near parallel.", "Drive the hips forward to stand."], "cues": ["Very light to start \u2014 this loads the lower back directly", "Back stays flat throughout", "\ud83d\udca1 Skip this if you have any lower-back history; use an RDL instead"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789301000000,1789301000000);
