-- Migration 0104: Batch 3 of the exercise-library enrichment — MACHINES & CABLE
--
-- Roadmap X-38. `machine` and `cable` had zero exercises, so the entire machine
-- half of R518's gym vocabulary was empty.
--
-- These matter beyond the gym: fixed-path machines are the safest way to load a
-- beginner, and they give R563 (injury filtering) loaded alternatives to fall
-- back on when a free-weight pattern is excluded. Several are tagged
-- beginner_friendly for exactly that reason.

INSERT INTO exercises
  (id, slug, name, category, primary_muscles_json, secondary_muscles_json,
   tags_json, equipment_required_json, instructions_json, metrics_json,
   is_active, visibility, created_at_ms, updated_at_ms)
VALUES
('ex_m_leg_press','leg-press','Leg Press','strength','["quads", "glutes"]','["hamstrings"]','["strength", "legs", "machine", "gym", "no_floor", "low_impact", "beginner_friendly", "loads_knee"]','["leg_press"]','{"steps": ["Sit with your back flat against the pad, feet shoulder-width on the platform.", "Release the safety catches.", "Lower until your knees reach about 90\u00b0.", "Press back without locking the knees out hard."], "cues": ["Keep your lower back against the pad the whole way", "Do not let the knees cave inward", "\ud83d\udca1 A safe way to load the legs heavily without balancing a bar"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000),
('ex_m_leg_curl','leg-curl-machine','Leg Curl (Machine)','strength','["hamstrings"]','["calves"]','["strength", "legs", "machine", "gym", "no_floor", "low_impact", "beginner_friendly"]','["leg_curl_machine"]','{"steps": ["Set the pad just above your heels.", "Curl your heels towards your glutes.", "Pause briefly at the top.", "Lower slowly to a straight leg."], "cues": ["Hips stay down on the bench", "Slow on the lowering", "\ud83d\udca1 Directly trains the muscle most often strained in sprinting"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000),
('ex_m_leg_ext','leg-extension-machine','Leg Extension (Machine)','strength','["quads"]','[]','["strength", "legs", "machine", "gym", "no_floor", "low_impact", "beginner_friendly", "loads_knee"]','["leg_extension_machine"]','{"steps": ["Sit with your knees at the machine''s pivot, pad on your shins.", "Extend until your legs are almost straight.", "Pause, then lower under control."], "cues": ["Do not swing the weight up", "Stop short of snapping the knee straight", "\ud83d\udca1 Go light if your knees are sensitive \u2014 this loads them directly"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000),
('ex_m_chest_press','chest-press-machine','Chest Press (Machine)','strength','["chest"]','["triceps", "front_delts"]','["strength", "push", "upper_body", "machine", "gym", "no_floor", "low_impact", "beginner_friendly", "loads_shoulder"]','["chest_press_machine"]','{"steps": ["Set the seat so the handles are at mid-chest height.", "Press forward until your arms are almost straight.", "Return slowly until you feel a stretch across the chest."], "cues": ["Shoulder blades stay back against the pad", "Do not lock the elbows hard", "\ud83d\udca1 The safest way to press heavy with nobody spotting you"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000),
('ex_m_pec_deck','pec-deck-fly','Pec Deck Fly','strength','["chest"]','["front_delts"]','["strength", "push", "upper_body", "machine", "gym", "no_floor", "low_impact", "loads_shoulder"]','["pec_deck"]','{"steps": ["Set the seat so the handles are at chest height.", "Bring the handles together in front of your chest with a soft elbow bend.", "Open slowly until you feel a stretch, no further."], "cues": ["Do not force the stretch behind the body line", "Move from the shoulder, not the elbow", "\ud83d\udca1 Stop if you feel it in the front of the shoulder joint"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000),
('ex_m_cable_curl','cable-biceps-curl','Cable Biceps Curl','strength','["biceps"]','["forearms"]','["strength", "pull", "upper_body", "machine", "gym", "no_floor", "low_impact", "quiet"]','["cable"]','{"steps": ["Attach a bar to a low pulley, hold with palms up.", "Curl to shoulder height, elbows pinned to your sides.", "Lower slowly to full extension."], "cues": ["The cable keeps tension at the bottom, unlike a dumbbell", "Elbows do not drift forward", "\ud83d\udca1 Good finisher when free weights have tired the grip"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000),
('ex_m_triceps_pushdown','cable-triceps-pushdown','Cable Triceps Pushdown','strength','["triceps"]','[]','["strength", "push", "upper_body", "machine", "gym", "no_floor", "low_impact", "quiet", "loads_shoulder"]','["cable"]','{"steps": ["Attach a bar or rope to a high pulley.", "Elbows tucked at your sides, push down until your arms are straight.", "Return to about 90\u00b0 under control."], "cues": ["Only the forearms move", "Do not lean over the bar to press it down", "\ud83d\udca1 Rope attachment lets the wrists sit more naturally"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000),
('ex_m_calf_press','machine-calf-press','Calf Press (Machine)','strength','["calves"]','[]','["strength", "legs", "machine", "gym", "no_floor", "low_impact", "loads_ankle"]','["leg_press"]','{"steps": ["Sit in the leg press with the balls of your feet on the bottom edge of the platform.", "Press out and release the safeties.", "Push through the toes to full extension, then lower into a stretch."], "cues": ["Full range \u2014 deep stretch, full squeeze", "Slow tempo beats heavy weight here", "\ud83d\udca1 Do not let the platform drop uncontrolled"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000),
('ex_m_cable_woodchop','cable-woodchop','Cable Woodchop','strength','["obliques", "core"]','["shoulders"]','["strength", "core", "machine", "gym", "no_floor", "low_impact", "rotation"]','["cable"]','{"steps": ["Set the pulley high, stand side-on, both hands on the handle.", "Pull diagonally across your body towards the opposite hip, pivoting the back foot.", "Return under control. Repeat, then change sides."], "cues": ["Rotate through the torso, not just the arms", "Keep the arms fairly straight", "\ud83d\udca1 One of the few trainable anti-rotation patterns in the library"]}','{"supports": ["weight", "reps", "sets"]}',1,'global',1789302000000,1789302000000),
('ex_m_dip','dip-station-dip','Dip (Parallel Bars)','strength','["chest", "triceps"]','["front_delts"]','["strength", "push", "upper_body", "gym", "no_floor", "loads_shoulder"]','["dip_station"]','{"steps": ["Grip the parallel bars and press up to straight arms.", "Lower until your upper arms are roughly parallel to the floor.", "Press back to the top."], "cues": ["Lean slightly forward for the chest, stay upright for the triceps", "Do not drop below a comfortable shoulder position", "\ud83d\udca1 Stop the set well before the shoulders start to ache"]}','{"supports": ["reps", "sets"]}',1,'global',1789302000000,1789302000000),
('ex_m_seated_shoulder','machine-shoulder-press','Shoulder Press (Machine)','strength','["shoulders"]','["triceps"]','["strength", "push", "upper_body", "machine", "gym", "no_floor", "low_impact", "beginner_friendly", "loads_shoulder"]','["multi_gym"]','{"steps": ["Set the seat so the handles start at shoulder height.", "Press overhead until your arms are almost straight.", "Lower under control to the start."], "cues": ["Ribs down, back against the pad", "Do not lock out sharply", "\ud83d\udca1 The fixed path makes this far safer than a barbell press when training alone"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000),
('ex_m_hack_squat','machine-hack-squat','Hack Squat (Machine)','strength','["quads", "glutes"]','["hamstrings"]','["strength", "legs", "machine", "gym", "no_floor", "low_impact", "loads_knee"]','["multi_gym"]','{"steps": ["Stand on the platform with your back and shoulders against the pads.", "Release the safeties and lower until your thighs reach parallel.", "Drive back up through the whole foot."], "cues": ["Feet slightly forward to spare the knees", "Back stays flat on the pad", "\ud83d\udca1 Loads the quads hard without asking your spine to stabilise it"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789302000000,1789302000000);
