-- Migration 0105: Batch 4 of the exercise-library enrichment — DEAD HOME OPTIONS
--
-- Roadmap X-36 / X-38. Six equipment options could be selected in onboarding and
-- had zero exercises behind them, so ticking them changed nothing: jump_rope,
-- stability_ball, adjustable_bench/bench, yoga_mat, exercise_mat, trail_shoes.
-- A broken promise at the first interaction.
--
-- yoga_mat and exercise_mat are duplicates of each other; these seed yoga_mat and
-- ALL_EQUIPMENT should drop exercise_mat rather than seed it twice.

INSERT INTO exercises
  (id, slug, name, category, primary_muscles_json, secondary_muscles_json,
   tags_json, equipment_required_json, instructions_json, metrics_json,
   is_active, visibility, created_at_ms, updated_at_ms)
VALUES
('ex_jr_basic','jump-rope-basic','Jump Rope — Steady','cardio','["calves", "conditioning"]','["shoulders", "core"]','["cardio", "conditioning", "jump_rope", "high_impact", "no_floor", "loads_ankle", "loads_knee"]','["jump_rope"]','{"steps": ["Rope handles at hip height, elbows close to your sides.", "Turn the rope from the wrists, not the shoulders.", "Small bounces \u2014 just enough to clear the rope.", "Keep a steady rhythm."], "cues": ["Land softly through the balls of the feet", "Stay tall \u2014 do not pike at the hips", "\ud83d\udca1 Stop if your calves start cramping rather than pushing on"]}','{"supports": ["time", "sets"]}',1,'global',1789303000000,1789303000000),
('ex_jr_intervals','jump-rope-intervals','Jump Rope — Intervals','cardio','["conditioning", "calves"]','["shoulders"]','["cardio", "conditioning", "hiit", "jump_rope", "high_impact", "no_floor", "loads_ankle", "loads_knee"]','["jump_rope"]','{"steps": ["Skip hard for the work interval.", "Rest or step in place for the recovery.", "Repeat for the prescribed rounds."], "cues": ["Pace the first round \u2014 it always feels easy", "Trips are normal; pick the rope straight back up", "\ud83d\udca1 High impact: swap for march-in-place if your knees complain"]}','{"supports": ["time", "sets"]}',1,'global',1789303000000,1789303000000),
('ex_sb_plank','stability-ball-plank','Stability Ball Plank','strength','["core", "abs"]','["shoulders"]','["strength", "core", "stability_ball", "floor", "low_impact", "isometric"]','["stability_ball"]','{"steps": ["Place your forearms on the ball, feet back, body in a straight line.", "Brace and hold, resisting the ball''s wobble.", "Keep breathing."], "cues": ["Squeeze the glutes so the hips do not sag", "Small circles with the forearms make it harder", "\ud83d\udca1 Far more demanding than a floor plank \u2014 start with less time"]}','{"supports": ["time", "sets"]}',1,'global',1789303000000,1789303000000),
('ex_sb_hamstring_curl','stability-ball-hamstring-curl','Stability Ball Hamstring Curl','strength','["hamstrings", "glutes"]','["core"]','["strength", "hinge", "stability_ball", "floor", "low_impact"]','["stability_ball"]','{"steps": ["Lie on your back, heels on the ball, arms flat on the floor.", "Lift your hips into a bridge.", "Pull the ball towards you by bending the knees.", "Push it back out slowly, keeping the hips up."], "cues": ["Hips stay lifted the whole set", "Slow on the way out", "\ud83d\udca1 One of the best hamstring exercises needing no weight at all"]}','{"supports": ["reps", "sets"]}',1,'global',1789303000000,1789303000000),
('ex_sb_deadbug','stability-ball-dead-bug','Stability Ball Dead Bug','strength','["core", "abs"]','["hip_flexors"]','["strength", "core", "stability_ball", "floor", "low_impact", "beginner_friendly"]','["stability_ball"]','{"steps": ["Lie on your back holding the ball between your hands and knees.", "Press into the ball to create tension.", "Extend the opposite arm and leg away, keeping the ball pinned.", "Return and alternate."], "cues": ["Lower back stays flat on the floor", "Move slowly \u2014 the tension is the point", "\ud83d\udca1 Stop extending where your back would start to arch"]}','{"supports": ["reps", "sets"]}',1,'global',1789303000000,1789303000000),
('ex_bench_step_up','bench-step-up','Bench Step-Up','strength','["quads", "glutes"]','["hamstrings", "calves"]','["strength", "legs", "bench", "no_floor", "unilateral", "loads_knee"]','["bench"]','{"steps": ["Stand facing a flat bench.", "Step one foot fully onto it and drive up to standing.", "Step down under control with the same leg leading.", "Complete the reps, then change sides."], "cues": ["Drive through the heel of the top foot", "Do not push off the bottom foot", "\ud83d\udca1 Lower the step if your knee travels far past your toes"]}','{"supports": ["reps", "sets", "weight"]}',1,'global',1789303000000,1789303000000),
('ex_bench_hip_thrust_bw','bench-hip-thrust-bodyweight','Bench Hip Thrust (Bodyweight)','strength','["glutes"]','["hamstrings", "core"]','["strength", "hinge", "bench", "floor", "low_impact", "beginner_friendly"]','["bench"]','{"steps": ["Sit on the floor with your upper back against a bench.", "Feet flat, hip-width, shins vertical at the top.", "Drive through your heels until your hips are level with your knees.", "Lower under control."], "cues": ["Chin tucked, ribs down", "Hold the top for a beat", "\ud83d\udca1 Learn the pattern here before adding a barbell"]}','{"supports": ["reps", "sets", "time"]}',1,'global',1789303000000,1789303000000),
('ex_mat_hip_bridge_march','mat-hip-bridge-march','Hip Bridge March','strength','["glutes", "core"]','["hamstrings"]','["strength", "hinge", "yoga_mat", "floor", "low_impact", "beginner_friendly", "unilateral"]','["yoga_mat"]','{"steps": ["Lie on your back on the mat, knees bent, feet flat.", "Lift into a bridge and hold it there.", "Without dropping the hips, lift one knee towards your chest.", "Replace and alternate."], "cues": ["The hips must not tilt when the foot leaves the floor", "Slow and even", "\ud83d\udca1 Exposes a weak side quickly \u2014 expect one to feel harder"]}','{"supports": ["reps", "sets"]}',1,'global',1789303000000,1789303000000),
('ex_mat_supine_twist','mat-supine-spinal-twist','Supine Spinal Twist','mobility','["lower_back", "obliques"]','["glutes"]','["mobility", "stretch", "yoga_mat", "floor", "low_impact", "recovery"]','["yoga_mat"]','{"steps": ["Lie on your back on the mat, arms out in a T.", "Draw one knee to your chest, then let it fall across your body.", "Turn your head the other way and breathe.", "Hold, then change sides."], "cues": ["Both shoulders stay on the mat", "Do not force the knee down", "\ud83d\udca1 Good last thing at night"]}','{"supports": ["time", "sets"]}',1,'global',1789303000000,1789303000000),
('ex_mat_prone_swimmer','mat-prone-swimmer','Prone Swimmer','strength','["lower_back", "rear_delts"]','["glutes", "upper_back"]','["mobility", "strength", "yoga_mat", "floor", "low_impact", "shoulder_health"]','["yoga_mat"]','{"steps": ["Lie face down on the mat, arms overhead.", "Lift your chest and arms slightly.", "Sweep the arms back towards your hips and return, as if swimming backstroke.", "Stay lifted throughout."], "cues": ["Small lift \u2014 this is not a big back extension", "Keep the neck long, eyes down", "\ud83d\udca1 Counteracts hours of sitting forward"]}','{"supports": ["reps", "sets"]}',1,'global',1789303000000,1789303000000),
('ex_trail_hike_steady','trail-hike-steady','Trail Hike — Steady','cardio','["legs", "conditioning"]','["glutes", "calves"]','["cardio", "conditioning", "outdoor", "trail_shoes", "low_impact", "zone2", "loads_ankle"]','["trail_shoes"]','{"steps": ["Head out on uneven ground at a pace you could hold a conversation at.", "Shorten your stride on the climbs.", "Take the descents slowly \u2014 that is where ankles turn."], "cues": ["Watch your footing rather than the view when moving", "Poles help on longer descents", "\ud83d\udca1 Zone 2 work that does not feel like training"]}','{"supports": ["time", "distance"]}',1,'global',1789303000000,1789303000000),
('ex_trail_hill_repeats','trail-hill-repeats','Trail Hill Repeats','cardio','["legs", "conditioning"]','["glutes", "calves"]','["cardio", "conditioning", "hiit", "outdoor", "trail_shoes", "high_impact", "loads_knee", "loads_ankle"]','["trail_shoes"]','{"steps": ["Find a hill that takes 60\u201390 seconds to climb at effort.", "Work hard to the top.", "Walk down to recover fully.", "Repeat for the prescribed rounds."], "cues": ["Short strides, quick feet on the climb", "Walk \u2014 do not run \u2014 the descent", "\ud83d\udca1 Builds running strength with far less impact than flat speed work"]}','{"supports": ["time", "sets"]}',1,'global',1789303000000,1789303000000);
