-- Migration 0106: Batch 5 — CORE, CALF/LOWER LEG, KETTLEBELL
--
-- Roadmap X-37. The three groups from the Strava gap analysis that were genuine
-- capability gaps rather than naming granularity.
--
-- CORE (12). 54 exercises listed core as a primary muscle, but most were compounds
-- (goblet squat, push-up, pull-up). Dedicated core work was ~20 and almost entirely
-- anti-extension: plank variants. Missing outright were anti-rotation (no Pallof
-- press existed), loaded anti-lateral-flexion, and lower-ab flexion. Core drives a
-- whole progression axis, so the axis was being trained by one pattern.
--
-- CALF / LOWER LEG (8). Only 5 true calf-loading exercises, all straight-knee
-- (gastrocnemius). Absent: soleus work (bent knee), eccentric loading, and the
-- tibialis anterior. Those three are the ones that matter for running injuries,
-- and this app has two running coaches.
--
-- KETTLEBELL (10). A selectable equipment option with 6 exercises.
--
-- Every row carries loads_* injury tags (R563). Skill-heavy kettlebell lifts carry
-- explicit "learn it light first" cues.

INSERT INTO exercises
  (id, slug, name, category, primary_muscles_json, secondary_muscles_json,
   tags_json, equipment_required_json, instructions_json, metrics_json,
   is_active, visibility, created_at_ms, updated_at_ms)
VALUES
('ex_core_pallof_band','band-pallof-press','Band Pallof Press','strength','["core", "obliques"]','["shoulders"]','["strength", "core", "anti_rotation", "resistance_bands", "no_floor", "low_impact", "quiet"]','["resistance_bands"]','{"steps": ["Anchor a band at chest height. Stand side-on, both hands on the band at your sternum.", "Step out until the band is taut.", "Press your hands straight out in front of you and hold \u2014 the band will try to rotate you.", "Return to the chest. Complete the reps, then change sides."], "cues": ["Do not let your torso twist \u2014 that is the whole exercise", "Squeeze the glutes to stop the hips rotating", "\ud83d\udca1 Anti-rotation was missing entirely; this is the core''s most transferable pattern"]}','{"supports": ["reps", "sets", "time"]}',1,'global',1789400000000,1789400000000),
('ex_core_pallof_cable','cable-pallof-press','Cable Pallof Press','strength','["core", "obliques"]','["shoulders"]','["strength", "core", "anti_rotation", "machine", "gym", "no_floor", "low_impact"]','["cable"]','{"steps": ["Set a cable to chest height and stand side-on, both hands on the handle at your sternum.", "Step away until there is tension.", "Press straight out and hold.", "Return under control, then change sides."], "cues": ["Resist the pull \u2014 do not rotate", "Heavier is not better here; control is", "\ud83d\udca1 Add a pause at full extension to make it much harder"]}','{"supports": ["weight", "reps", "sets", "time"]}',1,'global',1789400000000,1789400000000),
('ex_core_side_plank_dip','side-plank-hip-dip','Side Plank Hip Dip','strength','["obliques", "core"]','["glutes", "shoulders"]','["strength", "core", "anti_lateral_flexion", "bodyweight", "floor", "low_impact"]','["none"]','{"steps": ["Set up in a side plank on your forearm, body in a straight line.", "Lower your hip towards the floor without touching.", "Drive back up until your body is straight again.", "Complete the reps, then change sides."], "cues": ["Stack the shoulders and hips \u2014 do not roll forward", "Small controlled range beats a big sloppy one", "\ud83d\udca1 Progresses the static side plank once 45 seconds feels easy"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_core_suitcase_carry','suitcase-carry','Suitcase Carry','strength','["obliques", "core"]','["forearms", "traps"]','["strength", "core", "carry", "anti_lateral_flexion", "dumbbell", "no_floor", "low_impact", "unilateral"]','["dumbbell"]','{"steps": ["Hold one heavy dumbbell at your side.", "Stand tall \u2014 shoulders level, ribs down.", "Walk in a straight line for the prescribed time.", "Change sides."], "cues": ["Do not lean away from the weight", "Shoulders stay square the whole walk", "\ud83d\udca1 If you are leaning, the weight is too heavy"]}','{"supports": ["weight", "time", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_core_reverse_crunch','reverse-crunch','Reverse Crunch','strength','["abs", "core"]','["hip_flexors"]','["strength", "core", "flexion", "bodyweight", "floor", "low_impact", "crunch"]','["none"]','{"steps": ["Lie on your back, hands by your sides, knees bent over your hips.", "Curl your pelvis off the floor, bringing the knees towards your chest.", "Lower slowly without letting your feet touch down."], "cues": ["The movement is the pelvis lifting, not the legs swinging", "Lower back presses into the floor", "\ud83d\udca1 Targets the lower abs the plank family misses"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_core_deadbug_band','band-dead-bug','Band Dead Bug','strength','["core", "abs"]','["hip_flexors"]','["strength", "core", "anti_extension", "resistance_bands", "floor", "low_impact"]','["resistance_bands"]','{"steps": ["Anchor a band low behind your head. Lie on your back holding it with straight arms over your chest.", "Knees over hips, shins parallel to the floor.", "Extend one leg away while holding the band steady.", "Return and alternate."], "cues": ["The band pulls your arms back \u2014 resist it", "Lower back stays flat on the floor", "\ud83d\udca1 Adds load to a movement that gets easy fast"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_core_copenhagen','copenhagen-plank','Copenhagen Plank','strength','["adductors", "obliques", "core"]','["glutes"]','["strength", "core", "anti_lateral_flexion", "bodyweight", "floor", "low_impact", "groin_health"]','["none"]','{"steps": ["Lie on your side with your top foot resting on a chair or bench.", "Prop up on your forearm and lift your hips so your body is straight.", "Hold, keeping the bottom leg off the floor if you can.", "Change sides."], "cues": ["Start with the bottom knee down \u2014 it is much easier", "Stop the moment the hips drop", "\ud83d\udca1 The best-evidenced groin-injury preventer there is"]}','{"supports": ["time", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_core_stir_pot','stability-ball-stir-the-pot','Stability Ball Stir the Pot','strength','["core", "abs"]','["shoulders"]','["strength", "core", "anti_extension", "stability_ball", "floor", "low_impact"]','["stability_ball"]','{"steps": ["Forearms on the ball in a plank position.", "Keeping your body rigid, draw slow circles with your forearms.", "Reverse direction halfway through."], "cues": ["The hips must not move at all", "Small circles first, wider as you get stronger", "\ud83d\udca1 One of the hardest anti-extension drills once the circles widen"]}','{"supports": ["reps", "sets", "time"]}',1,'global',1789400000000,1789400000000),
('ex_core_hanging_knee','hanging-knee-raise','Hanging Knee Raise','strength','["abs", "core"]','["hip_flexors", "forearms"]','["strength", "core", "flexion", "pull_up_bar", "no_floor", "low_impact", "loads_shoulder"]','["pull_up_bar"]','{"steps": ["Hang from a bar with straight arms, shoulders active.", "Curl your knees up towards your chest.", "Lower slowly without swinging."], "cues": ["Tuck the pelvis at the top \u2014 do not just lift the legs", "If you swing, pause between reps", "\ud83d\udca1 The step below a hanging leg raise"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_core_plank_pull','plank-pull-through','Plank Pull-Through','strength','["core", "obliques"]','["shoulders", "back"]','["strength", "core", "anti_rotation", "dumbbell", "floor", "low_impact"]','["dumbbell"]','{"steps": ["High plank with a dumbbell on the floor just outside one hand.", "Reach under your body with the opposite hand and drag it across.", "Replace the hand and repeat the other way."], "cues": ["Widen the feet for stability", "Hips stay dead level \u2014 no rocking", "\ud83d\udca1 Anti-rotation with a load, without needing a cable"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_core_bear_hold','bear-crawl-hold','Bear Crawl Hold','strength','["core", "abs"]','["shoulders", "quads"]','["strength", "core", "anti_extension", "bodyweight", "floor", "low_impact", "isometric", "beginner_friendly"]','["none"]','{"steps": ["On hands and knees, toes tucked, knees an inch off the floor.", "Hold with a flat back.", "Breathe."], "cues": ["Back stays flat enough to balance a glass on", "Knees hover \u2014 do not rest them down", "\ud83d\udca1 A gentler entry to core work than a full plank"]}','{"supports": ["time", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_core_wood_chop_band','band-wood-chop','Band Wood Chop','strength','["obliques", "core"]','["shoulders"]','["strength", "core", "rotation", "resistance_bands", "no_floor", "low_impact"]','["resistance_bands"]','{"steps": ["Anchor a band high. Stand side-on, both hands on the end.", "Pull diagonally across your body to the opposite hip, pivoting the back foot.", "Return under control. Change sides."], "cues": ["Rotate through the ribs, not just the arms", "Keep the arms fairly straight", "\ud83d\udca1 Pairs with the Pallof press: one trains rotation, the other resists it"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_calf_seated','seated-calf-raise','Seated Calf Raise (Soleus)','strength','["calves"]','[]','["strength", "legs", "calf", "soleus", "bench", "no_floor", "low_impact", "loads_ankle"]','["bench"]','{"steps": ["Sit with your knees bent at 90\u00b0, balls of the feet on a step or block.", "Rest a weight on your thighs if you have one.", "Rise onto the toes, pause, lower into a stretch."], "cues": ["Bent knee targets the soleus \u2014 the calf muscle running matters most to", "Slow lowering is the point", "\ud83d\udca1 The library had no bent-knee calf work at all before this"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789400000000,1789400000000),
('ex_calf_eccentric','eccentric-calf-raise-step','Eccentric Calf Raise (Step)','strength','["calves"]','["achilles"]','["strength", "legs", "calf", "eccentric", "bodyweight", "no_floor", "low_impact", "loads_ankle", "rehab"]','["none"]','{"steps": ["Stand with the balls of both feet on a step, heels hanging off.", "Rise onto both toes.", "Shift your weight to one leg and lower that heel slowly below the step over 3-5 seconds.", "Use both legs to rise again."], "cues": ["Up with two, down with one", "The slow lowering is the whole exercise", "\ud83d\udca1 The best-evidenced protocol for Achilles tendon resilience"]}','{"supports": ["reps", "sets", "tempo"]}',1,'global',1789400000000,1789400000000),
('ex_calf_bent_knee_bw','bent-knee-calf-raise','Bent-Knee Calf Raise','strength','["calves"]','[]','["strength", "legs", "calf", "soleus", "bodyweight", "no_floor", "low_impact", "quiet", "loads_ankle"]','["none"]','{"steps": ["Stand with knees bent about 20\u00b0, feet hip-width.", "Keeping the knees bent, rise onto the balls of your feet.", "Lower slowly."], "cues": ["Do not straighten the knees \u2014 that turns it back into a standard raise", "Hold a wall for balance", "\ud83d\udca1 No equipment needed to train the soleus"]}','{"supports": ["reps", "sets", "time"]}',1,'global',1789400000000,1789400000000),
('ex_calf_soleus_wallsit','soleus-wall-sit','Soleus Wall Sit','strength','["calves"]','["quads"]','["strength", "legs", "calf", "soleus", "isometric", "bodyweight", "no_floor", "low_impact", "loads_knee"]','["none"]','{"steps": ["Sit against a wall with knees at 90\u00b0.", "Lift both heels and hold them up.", "Keep the heels raised for the full hold."], "cues": ["Heels stay up the whole time \u2014 that is the exercise", "Quads will burn too; that is fine", "\ud83d\udca1 Builds the endurance that fails late in a long run"]}','{"supports": ["time", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_calf_tib_raise','tibialis-raise','Tibialis Raise','strength','["tibialis", "shins"]','[]','["strength", "legs", "shin", "bodyweight", "no_floor", "low_impact", "quiet", "rehab", "loads_ankle"]','["none"]','{"steps": ["Stand with your back against a wall, feet a step forward.", "Keeping the heels down, pull your toes up towards your shins as far as possible.", "Lower slowly."], "cues": ["Slow on the way down", "Expect it to burn quickly \u2014 that is normal", "\ud83d\udca1 Trains the muscle that fails in shin splints; nothing else in the library did"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_calf_toe_walk','toe-walk','Toe Walk','strength','["calves"]','["tibialis"]','["strength", "legs", "calf", "bodyweight", "no_floor", "low_impact", "quiet", "loads_ankle"]','["none"]','{"steps": ["Rise onto the balls of your feet.", "Walk forward staying as high as you can.", "Keep going for the prescribed time."], "cues": ["Stay tall \u2014 do not shuffle", "Turn around rather than lowering the heels", "\ud83d\udca1 Easy calf volume you can do in a hallway"]}','{"supports": ["time", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_calf_heel_walk','heel-walk','Heel Walk','strength','["tibialis", "shins"]','[]','["strength", "legs", "shin", "bodyweight", "no_floor", "low_impact", "quiet", "rehab", "loads_ankle"]','["none"]','{"steps": ["Lift your toes so you are standing on your heels.", "Walk forward keeping the toes off the floor.", "Continue for the prescribed time."], "cues": ["Toes stay up throughout", "Short bouts \u2014 this fatigues fast", "\ud83d\udca1 Pairs with the tibialis raise for shin resilience"]}','{"supports": ["time", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_calf_pogo','pogo-hops','Pogo Hops','cardio','["calves"]','["conditioning"]','["cardio", "plyometric", "legs", "calf", "bodyweight", "high_impact", "no_floor", "loads_ankle", "loads_knee"]','["none"]','{"steps": ["Stand tall, knees almost straight.", "Hop on the spot using only the ankles, staying off the heels.", "Keep the contacts short and springy."], "cues": ["Stiff ankles, quiet landings", "Knees barely bend \u2014 this is an ankle drill", "\ud83d\udca1 Builds the tendon stiffness that makes running economical"]}','{"supports": ["reps", "sets", "time"]}',1,'global',1789400000000,1789400000000),
('ex_calf_db_raise','dumbbell-calf-raise','Dumbbell Calf Raise','strength','["calves"]','[]','["strength", "legs", "calf", "dumbbell", "no_floor", "low_impact", "loads_ankle"]','["dumbbell"]','{"steps": ["Hold a dumbbell in each hand, standing on a step if you have one.", "Rise onto the toes as high as you can.", "Lower slowly into a stretch."], "cues": ["Full range beats heavy weight", "Pause at the top", "\ud83d\udca1 The simplest way to progress calf raises once bodyweight is easy"]}','{"supports": ["weight", "reps", "sets", "tempo"]}',1,'global',1789400000000,1789400000000),
('ex_kb_tgu','kettlebell-turkish-get-up','Kettlebell Turkish Get-Up','strength','["shoulders", "core"]','["glutes", "quads", "obliques"]','["strength", "kettlebell", "full_body", "floor", "low_impact", "skill", "loads_shoulder"]','["kettlebell"]','{"steps": ["Lie on your back, one kettlebell pressed straight up, same-side knee bent.", "Roll to your elbow, then your hand.", "Bridge the hips, sweep the straight leg back to a lunge, and stand.", "Reverse every step to return."], "cues": ["The bell stays locked overhead and your eyes on it the whole time", "Learn it with no weight first, then a shoe, then a bell", "\ud83d\udca1 Slow and deliberate \u2014 this is a skill, not a conditioning drill"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_kb_clean','kettlebell-clean','Kettlebell Clean','strength','["glutes", "hamstrings"]','["shoulders", "core", "forearms"]','["strength", "kettlebell", "hinge", "power", "no_floor", "loads_lower_back"]','["kettlebell"]','{"steps": ["Start with the bell between your feet, hinge and grip it.", "Hike it back, then drive the hips to bring it up the body.", "Guide it around the wrist into the front rack rather than letting it flip over.", "Lower back into the hinge."], "cues": ["Keep the bell close \u2014 it should not swing away from you", "A banged wrist means you let it travel too far", "\ud83d\udca1 Learn the swing first; the clean is a swing that finishes in the rack"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_kb_clean_press','kettlebell-clean-and-press','Kettlebell Clean & Press','strength','["shoulders", "glutes"]','["core", "triceps", "hamstrings"]','["strength", "kettlebell", "full_body", "no_floor", "loads_shoulder", "loads_lower_back"]','["kettlebell"]','{"steps": ["Clean the bell to the front rack.", "Brace, then press it overhead.", "Lower to the rack, then back to the hinge."], "cues": ["Full breath before each press", "Do not lean back to finish the press", "\ud83d\udca1 A complete strength session in one movement when time is short"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_kb_snatch','kettlebell-snatch','Kettlebell Snatch','strength','["shoulders", "glutes", "hamstrings"]','["core", "forearms"]','["strength", "kettlebell", "power", "hinge", "no_floor", "loads_shoulder", "loads_lower_back"]','["kettlebell"]','{"steps": ["Hike the bell back between your legs.", "Drive the hips hard and pull the bell up close to the body.", "Punch your hand through at the top so the bell settles rather than flips.", "Lower under control back into the hinge."], "cues": ["Power comes from the hips, not the arm", "Build up slowly \u2014 this is hard on the shoulder if rushed", "\ud83d\udca1 Learn the clean and the high pull first"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_kb_windmill','kettlebell-windmill','Kettlebell Windmill','strength','["obliques", "shoulders"]','["hamstrings", "core"]','["strength", "kettlebell", "core", "mobility", "no_floor", "low_impact", "loads_shoulder"]','["kettlebell"]','{"steps": ["Press a bell overhead and turn your feet away from that side.", "Keeping the arm locked and your eyes on the bell, hinge sideways and reach the free hand towards the floor.", "Stand back up under control."], "cues": ["The overhead arm stays vertical throughout", "Go only as low as you can without the shoulder shifting", "\ud83d\udca1 Mobility and strength at once \u2014 start very light"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_kb_row','kettlebell-row','Kettlebell Row','strength','["lats", "upper_back"]','["biceps", "core"]','["strength", "kettlebell", "pull", "upper_body", "no_floor", "low_impact", "loads_lower_back"]','["kettlebell"]','{"steps": ["Hinge forward with a flat back, one hand supported on a chair.", "Let the bell hang, then row it to your ribs.", "Lower under control. Change sides."], "cues": ["Do not rotate the torso to lift it higher", "Elbow brushes past your side", "\ud83d\udca1 More pull work \u2014 the axis the library was thinnest in"]}','{"supports": ["reps", "sets", "tempo"]}',1,'global',1789400000000,1789400000000),
('ex_kb_front_squat','kettlebell-front-rack-squat','Kettlebell Front Rack Squat','strength','["quads", "glutes"]','["core", "upper_back"]','["strength", "kettlebell", "legs", "no_floor", "loads_knee"]','["kettlebell"]','{"steps": ["Clean one or two bells into the front rack.", "Squat down with an upright torso until your thighs reach parallel.", "Drive up through the whole foot."], "cues": ["Elbows stay in, bells resting on the forearms", "Chest tall \u2014 the rack position will try to fold you forward", "\ud83d\udca1 The rack position makes your core work far harder than a goblet squat"]}','{"supports": ["reps", "sets", "tempo"]}',1,'global',1789400000000,1789400000000),
('ex_kb_carry','kettlebell-farmers-carry','Kettlebell Farmer''s Carry','strength','["forearms", "traps", "core"]','["glutes"]','["strength", "kettlebell", "carry", "no_floor", "low_impact", "grip"]','["kettlebell"]','{"steps": ["Hold a bell in each hand at your sides.", "Stand tall and walk for the prescribed time.", "Set them down under control."], "cues": ["Shoulders back and down", "Breathe normally \u2014 do not hold your breath", "\ud83d\udca1 Grip usually fails first; that is the adaptation"]}','{"supports": ["weight", "time", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_kb_high_pull','kettlebell-high-pull','Kettlebell High Pull','strength','["upper_back", "shoulders"]','["glutes", "hamstrings", "traps"]','["strength", "kettlebell", "pull", "power", "no_floor", "loads_shoulder", "loads_lower_back"]','["kettlebell"]','{"steps": ["Set up as for a swing, bell hiked back.", "Drive the hips and pull the elbow high and wide as the bell rises.", "Let it fall back into the hinge."], "cues": ["Elbow leads, above the wrist", "The hips do the work; the arm only steers", "\ud83d\udca1 The bridge between a swing and a snatch"]}','{"supports": ["reps", "sets"]}',1,'global',1789400000000,1789400000000),
('ex_kb_press','kettlebell-strict-press','Kettlebell Strict Press','strength','["shoulders"]','["triceps", "core"]','["strength", "kettlebell", "push", "upper_body", "no_floor", "loads_shoulder"]','["kettlebell"]','{"steps": ["Hold a bell in the front rack, elbow tucked.", "Press overhead without leaning back.", "Lower under control to the rack."], "cues": ["Squeeze the glutes to stop the lower back arching", "The bell finishes over the middle of your foot", "\ud83d\udca1 The offset weight makes this harder than a dumbbell press"]}','{"supports": ["reps", "sets", "tempo"]}',1,'global',1789400000000,1789400000000);
