// ─── WORKOUT FILE EXPORT GENERATORS ──────────────────────────────────────────
// Pure functions — no React, no external deps.
// Imported by App.jsx (cycling & running coach export buttons).

export function generateCyclingTcx(sessionName, intervals, ftpWatts, maxHr) {
  const useHr = !ftpWatts || ftpWatts <= 0;
  let stepId = 0;
  const steps = intervals.flatMap(iv => {
    const sets = iv.sets ?? 1;
    const isRest = (iv.power_pct_high ?? 0) <= 62;
    const intensity = isRest ? 'Rest' : 'Active';
    const out = [];
    for (let s = 0; s < sets; s++) {
      stepId++;
      const label = sets > 1 ? `${iv.label} ${s + 1}` : iv.label;
      let target;
      if (useHr && maxHr) {
        const lo = Math.round(maxHr * iv.power_pct_low / 100);
        const hi = Math.round(maxHr * iv.power_pct_high / 100);
        target = `<Target xsi:type="HeartRate_t"><HeartRateZone xsi:type="CustomHeartRateZone_t"><LowBpm>${lo}</LowBpm><HighBpm>${hi}</HighBpm></HeartRateZone></Target>`;
      } else if (ftpWatts) {
        const lo = Math.round(ftpWatts * iv.power_pct_low / 100);
        const hi = Math.round(ftpWatts * iv.power_pct_high / 100);
        target = `<Target xsi:type="Power_t"><PowerZone xsi:type="CustomPowerZone_t"><LowWatts>${lo}</LowWatts><HighWatts>${hi}</HighWatts></PowerZone></Target>`;
      } else {
        target = `<Target xsi:type="None_t"/>`;
      }
      out.push(`    <Step xsi:type="Step_t"><StepId>${stepId}</StepId><Name>${label}</Name><Duration xsi:type="Time_t"><Seconds>${iv.duration_sec}</Seconds></Duration><Intensity>${intensity}</Intensity>${target}</Step>`);
    }
    return out;
  });
  const today = new Date().toISOString().slice(0, 10);
  return `<?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd">
  <Workouts>
    <Workout Sport="Biking">
      <Name>${sessionName}</Name>
${steps.join('\n')}
      <ScheduledOn>${today}</ScheduledOn>
    </Workout>
  </Workouts>
</TrainingCenterDatabase>`;
}

export function triggerFileDownload(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}

// ─── ZWO EXPORT (Zwift) ───────────────────────────────────────────────────────
export function generateZwoFile(sessionName, intervals, _ftpWatts) {
  const elements = [];
  for (const iv of intervals) {
    const sets = iv.sets ?? 1;
    const lo = (iv.power_pct_low ?? 60) / 100;
    const hi = (iv.power_pct_high ?? 70) / 100;
    const mid = ((lo + hi) / 2).toFixed(2);
    const label = (iv.label ?? '').toLowerCase();
    if (label.includes('warm')) {
      elements.push(`    <Warmup Duration="${iv.duration_sec}" PowerLow="${lo.toFixed(2)}" PowerHigh="${hi.toFixed(2)}"/>`);
    } else if (label.includes('cool')) {
      elements.push(`    <Cooldown Duration="${iv.duration_sec}" PowerLow="${lo.toFixed(2)}" PowerHigh="${hi.toFixed(2)}"/>`);
    } else if (sets > 1 && iv.rest_sec) {
      elements.push(`    <IntervalsT Repeat="${sets}" OnDuration="${iv.duration_sec}" OffDuration="${iv.rest_sec}" OnPower="${hi.toFixed(2)}" OffPower="0.50"/>`);
    } else {
      for (let s = 0; s < sets; s++) {
        elements.push(`    <SteadyState Duration="${iv.duration_sec}" Power="${mid}"/>`);
        if (s < sets - 1 && iv.rest_sec) {
          elements.push(`    <SteadyState Duration="${iv.rest_sec}" Power="0.50"/>`);
        }
      }
    }
  }
  return `<?xml version="1.0" encoding="utf-8"?>
<workout_file>
  <author>JustFit.cc</author>
  <name>${sessionName}</name>
  <description>Generated by JustFit.cc · ${new Date().toISOString().slice(0, 10)}</description>
  <sportType>bike</sportType>
  <workout>
${elements.join('\n')}
  </workout>
</workout_file>`;
}

// ─── ERG EXPORT (Wahoo / smart trainers) ─────────────────────────────────────
export function generateErgFile(sessionName, intervals, ftpWatts) {
  const ftp = ftpWatts ?? 200;
  const segments = [];
  let elapsed = 0;
  for (const iv of intervals) {
    const sets = iv.sets ?? 1;
    const pct = ((iv.power_pct_low ?? 60) + (iv.power_pct_high ?? 70)) / 2;
    const watts = Math.round(ftp * pct / 100);
    const recWatts = Math.round(ftp * 0.50);
    const durMin = iv.duration_sec / 60;
    const restMin = (iv.rest_sec ?? 0) / 60;
    for (let s = 0; s < sets; s++) {
      segments.push({ startMin: elapsed, endMin: elapsed + durMin, watts });
      elapsed += durMin;
      if (s < sets - 1 && iv.rest_sec) {
        segments.push({ startMin: elapsed, endMin: elapsed + restMin, watts: recWatts });
        elapsed += restMin;
      }
    }
  }
  const lines = [];
  for (const seg of segments) {
    lines.push(`${seg.startMin.toFixed(2)}\t${seg.watts}`);
    lines.push(`${seg.endMin.toFixed(2)}\t${seg.watts}`);
  }
  return `[COURSE HEADER]
VERSION = 2
UNITS = METRIC
DESCRIPTION = ${sessionName}
FILE NAME = ${sessionName}
MINUTES WATTS

[COURSE DATA]
${lines.join('\n')}

[END COURSE DATA]`;
}

// ─── RUNNING TCX EXPORT (Garmin) ─────────────────────────────────────────────
export function generateRunningTcx(sessionName, steps, maxHr) {
  const hrMax = maxHr ?? 180;
  let stepId = 0;
  const tcxSteps = [];
  for (const step of steps) {
    const sets = step.sets ?? 1;
    const dur = step.target_duration_sec ?? 300;
    const name = step.name ?? 'Run';
    const slug = step.exercise_slug ?? '';
    const tags = JSON.parse(step.tags_json ?? '[]');
    let loHr, hiHr, intensity;
    if (tags.includes('session_phase') && (slug.includes('jog') || slug.includes('warm'))) {
      loHr = Math.round(hrMax * 0.50); hiHr = Math.round(hrMax * 0.65); intensity = 'Warmup';
    } else if (tags.includes('session_phase') || slug.includes('cool') || slug.includes('walk')) {
      loHr = Math.round(hrMax * 0.50); hiHr = Math.round(hrMax * 0.62); intensity = 'Rest';
    } else {
      loHr = Math.round(hrMax * 0.65); hiHr = Math.round(hrMax * 0.80); intensity = 'Active';
    }
    const target = `<Target xsi:type="HeartRate_t"><HeartRateZone xsi:type="CustomHeartRateZone_t"><LowBpm>${loHr}</LowBpm><HighBpm>${hiHr}</HighBpm></HeartRateZone></Target>`;
    for (let s = 0; s < sets; s++) {
      stepId++;
      const label = sets > 1 ? `${name} ${s + 1}` : name;
      tcxSteps.push(`    <Step xsi:type="Step_t"><StepId>${stepId}</StepId><Name>${label}</Name><Duration xsi:type="Time_t"><Seconds>${dur}</Seconds></Duration><Intensity>${intensity}</Intensity>${target}</Step>`);
      if (s < sets - 1 && step.rest_sec) {
        stepId++;
        const restLo = Math.round(hrMax * 0.50); const restHi = Math.round(hrMax * 0.62);
        tcxSteps.push(`    <Step xsi:type="Step_t"><StepId>${stepId}</StepId><Name>Walk recovery</Name><Duration xsi:type="Time_t"><Seconds>${step.rest_sec}</Seconds></Duration><Intensity>Rest</Intensity><Target xsi:type="HeartRate_t"><HeartRateZone xsi:type="CustomHeartRateZone_t"><LowBpm>${restLo}</LowBpm><HighBpm>${restHi}</HighBpm></HeartRateZone></Target></Step>`);
      }
    }
  }
  const today = new Date().toISOString().slice(0, 10);
  return `<?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd">
  <Workouts>
    <Workout Sport="Running">
      <Name>${sessionName}</Name>
${tcxSteps.join('\n')}
      <ScheduledOn>${today}</ScheduledOn>
    </Workout>
  </Workouts>
</TrainingCenterDatabase>`;
}
