import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

// Generates dist/sw.js after every build with the exact hashed asset filenames
// baked in — so the cache list is always correct and the cache name changes on
// every deploy (forcing browsers to pick up new assets immediately).
function generateSW() {
  return {
    name: 'generate-sw',
    writeBundle(options, bundle) {
      const assets = Object.keys(bundle)
        .filter(f => /^assets\/.+\.(js|css)$/.test(f))
        .map(f => `/${f}`)
      const buildId = Date.now().toString(36)
      const shell   = JSON.stringify(['/', '/index.html', ...assets], null, 2)

      const sw = `/* JustFit shell service worker — generated by Vite at build time */
/* CACHE name changes on every deploy; old caches are deleted on activate */
const CACHE = 'jf-shell-${buildId}';
const SHELL = ${shell};

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const { pathname } = new URL(e.request.url);
  // API calls always go to the network — never intercept
  if (pathname.startsWith('/api/')) return;

  e.respondWith(
    caches.match(e.request).then(cached => {
      // Navigation (index.html): serve from cache instantly, revalidate in background
      if (cached && e.request.mode === 'navigate') {
        fetch(e.request).then(r => {
          if (r.ok) caches.open(CACHE).then(c => c.put(e.request, r.clone()));
        }).catch(() => {});
        return cached;
      }
      if (cached) return cached;
      // Not yet cached — fetch and store shell assets for next time
      return fetch(e.request).then(r => {
        if (r.ok && (pathname.startsWith('/assets/') || pathname === '/')) {
          caches.open(CACHE).then(c => c.put(e.request, r.clone()));
        }
        return r;
      });
    })
  );
});
`
      writeFileSync(join(options.dir, 'sw.js'), sw)
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), generateSW()],
})
